@ graphics assets ROM sections.
@ Generated by tools/split.py; section names preserve ROM order.

@ ROM 1C9E00..1CF7A1 (gfx)
	.section .rom.001C9E00, "a"
	.incbin "build/graphics/backgrounds/AD0_P_0A.KCG.lz"

@ ROM 1CF7B0..1CF8F0 (palette)
	.section .rom.001CF7B0, "a"
	.incbin "build/graphics/palettes/AD0_P_0A.KCL.bin"

@ ROM 237570..23BF12 (gfx)
	.section .rom.00237570, "a"
	.incbin "build/graphics/backgrounds/AD1_P_0A.KCG.lz"

@ ROM 23BF20..23C000 (palette)
	.section .rom.0023BF20, "a"
	.incbin "build/graphics/palettes/AD1_P_0A.KCL.bin"

@ ROM 2A3C80..2A8908 (gfx)
	.section .rom.002A3C80, "a"
	.incbin "build/graphics/backgrounds/AD3_P_0A.KCG.lz"

@ ROM 2A8910..2A89D0 (palette)
	.section .rom.002A8910, "a"
	.incbin "build/graphics/palettes/AD3_P_0A.KCL.bin"

@ ROM 310650..313D8A (gfx)
	.section .rom.00310650, "a"
	.incbin "build/graphics/backgrounds/AD4_P_0A.KCG.lz"

@ ROM 313D90..313DF0 (palette)
	.section .rom.00313D90, "a"
	.incbin "build/graphics/palettes/AD4_P_0A.KCL.bin"

@ ROM 3759B0..37772F (gfx)
	.section .rom.003759B0, "a"
	.incbin "build/graphics/backgrounds/AD_BG01.KCG.lz"

@ ROM 377730..377750 (palette)
	.section .rom.00377730, "a"
	.incbin "build/graphics/palettes/AD_BG01.KCL.bin"

@ ROM 378010..378951 (gfx)
	.section .rom.00378010, "a"
	.incbin "build/graphics/backgrounds/AD_BG02.KCG.lz"

@ ROM 378960..378980 (palette)
	.section .rom.00378960, "a"
	.incbin "build/graphics/palettes/AD_BG02.KCL.bin"

@ ROM 379240..37B323 (gfx)
	.section .rom.00379240, "a"
	.incbin "build/graphics/backgrounds/AL_BG01.KCG.lz"

@ ROM 37B330..37B350 (palette)
	.section .rom.0037B330, "a"
	.incbin "build/graphics/palettes/AL_BG01.KCL.bin"

@ ROM 37BC10..37C692 (gfx)
	.section .rom.0037BC10, "a"
	.incbin "build/graphics/backgrounds/AL_BG02.KCG.lz"

@ ROM 37C6A0..37C6C0 (palette)
	.section .rom.0037C6A0, "a"
	.incbin "build/graphics/palettes/AL_BG02.KCL.bin"

@ ROM 37CF80..37F2B7 (gfx)
	.section .rom.0037CF80, "a"
	.incbin "build/graphics/backgrounds/AS_BG01.KCG.lz"

@ ROM 37F2C0..37F2E0 (palette)
	.section .rom.0037F2C0, "a"
	.incbin "build/graphics/palettes/AS_BG01.KCL.bin"

@ ROM 37FBA0..380FB8 (gfx)
	.section .rom.0037FBA0, "a"
	.incbin "build/graphics/backgrounds/AS_BG02.KCG.lz"

@ ROM 380FC0..380FE0 (palette)
	.section .rom.00380FC0, "a"
	.incbin "build/graphics/palettes/AS_BG02.KCL.bin"

@ ROM 3818A0..3835C5 (gfx)
	.section .rom.003818A0, "a"
	.incbin "build/graphics/backgrounds/AT_BG01.KCG.lz"

@ ROM 3835D0..3835F0 (palette)
	.section .rom.003835D0, "a"
	.incbin "build/graphics/palettes/AT_BG01.KCL.bin"

@ ROM 383EB0..386CF4 (gfx)
	.section .rom.00383EB0, "a"
	.incbin "build/graphics/backgrounds/BA06.TCG.lz"

@ ROM 386D00..386D60 (palette)
	.section .rom.00386D00, "a"
	.incbin "build/graphics/palettes/BA06.TCL.bin"

@ ROM 386D60..387560 (tilemap)
	.section .rom.00386D60, "a"
	.incbin "build/graphics/tilemaps/nfp/BA06_00.TSC.bin"

@ ROM 387560..387D60 (tilemap)
	.section .rom.00387560, "a"
	.incbin "build/graphics/tilemaps/nfp/BA06_01.TSC.bin"

@ ROM 387D60..38AC5A (gfx)
	.section .rom.00387D60, "a"
	.incbin "build/graphics/backgrounds/BA06_BG.TCG.lz"

@ ROM 38AC60..38ACC0 (palette)
	.section .rom.0038AC60, "a"
	.incbin "build/graphics/palettes/BA06_BG.TCL.bin"

@ ROM 38ACC0..38B4C0 (tilemap)
	.section .rom.0038ACC0, "a"
	.incbin "build/graphics/tilemaps/nfp/BA06_BG0.TSC.bin"

@ ROM 38B4C0..38BCC0 (tilemap)
	.section .rom.0038B4C0, "a"
	.incbin "build/graphics/tilemaps/nfp/BA06_BG1.TSC.bin"

@ ROM 38BCC0..38C4C0 (tilemap)
	.section .rom.0038BCC0, "a"
	.incbin "build/graphics/tilemaps/nfp/BA06_BG2.TSC.bin"

@ ROM 38C4C0..38CEF4 (gfx)
	.section .rom.0038C4C0, "a"
	.incbin "build/graphics/backgrounds/BA07.TCG.lz"

@ ROM 38CF00..38CF60 (palette)
	.section .rom.0038CF00, "a"
	.incbin "build/graphics/palettes/BA07.TCL.bin"

@ ROM 38CF60..38D760 (tilemap)
	.section .rom.0038CF60, "a"
	.incbin "build/graphics/tilemaps/nfp/BA07.TSC.bin"

@ ROM 39FFD0..5683C0 (sprites)
	.section .rom.0039FFD0, "a"
	.incbin "build/graphics/ncd/CHR.ncd"

@ ROM 56DB30..56E58E (gfx)
	.section .rom.0056DB30, "a"
	.incbin "build/graphics/backgrounds/CLPASS.KCG.lz"

@ ROM 56E590..56E5B0 (palette)
	.section .rom.0056E590, "a"
	.incbin "build/graphics/palettes/CLPASS.KCL.bin"

@ ROM 56EE70..570763 (gfx)
	.section .rom.0056EE70, "a"
	.incbin "build/graphics/backgrounds/CM_BG01.KCG.lz"

@ ROM 570770..570790 (palette)
	.section .rom.00570770, "a"
	.incbin "build/graphics/palettes/CM_BG01.KCL.bin"

@ ROM 571050..572165 (gfx)
	.section .rom.00571050, "a"
	.incbin "build/graphics/backgrounds/CM_BG02.KCG.lz"

@ ROM 572170..572190 (palette)
	.section .rom.00572170, "a"
	.incbin "build/graphics/palettes/CM_BG02.KCL.bin"

@ ROM 5A6FA0..5AA28A (gfx)
	.section .rom.005A6FA0, "a"
	.incbin "build/graphics/backgrounds/DS_BG01.KCG.lz"

@ ROM 5AA290..5AA2B0 (palette)
	.section .rom.005AA290, "a"
	.incbin "build/graphics/palettes/DS_BG01.KCL.bin"

@ ROM 5AAB70..5ABAA3 (gfx)
	.section .rom.005AAB70, "a"
	.incbin "build/graphics/backgrounds/DS_BG02.KCG.lz"

@ ROM 5ABAB0..5ABAD0 (palette)
	.section .rom.005ABAB0, "a"
	.incbin "build/graphics/palettes/DS_BG02.KCL.bin"

@ ROM 7BA990..7CA370 (font)
	.section .rom.007BA990, "a"
	.incbin "build/graphics/fonts/font.nft"

@ ROM 7CA760..7CCDBA (gfx)
	.section .rom.007CA760, "a"
	.incbin "build/graphics/tilesets/GA08.TCG.lz"

@ ROM 7CCDC0..7CCE20 (palette)
	.section .rom.007CCDC0, "a"
	.incbin "build/graphics/palettes/GA08.TCL.bin"

@ ROM 7CCE20..7CDE20 (tilemap)
	.section .rom.007CCE20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_00.TSC.bin"

@ ROM 7CDE20..7CEE20 (tilemap)
	.section .rom.007CDE20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_01.TSC.bin"

@ ROM 7CEE20..7CFE20 (tilemap)
	.section .rom.007CEE20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_02.TSC.bin"

@ ROM 7CFE20..7D0E20 (tilemap)
	.section .rom.007CFE20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_03.TSC.bin"

@ ROM 7D0E20..7D1E20 (tilemap)
	.section .rom.007D0E20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_10.TSC.bin"

@ ROM 7D1E20..7D2E20 (tilemap)
	.section .rom.007D1E20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_11.TSC.bin"

@ ROM 7D2E20..7D3E20 (tilemap)
	.section .rom.007D2E20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_12.TSC.bin"

@ ROM 7D3E20..7D4E20 (tilemap)
	.section .rom.007D3E20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA08_13.TSC.bin"

@ ROM 7D4E20..7D611A (gfx)
	.section .rom.007D4E20, "a"
	.incbin "build/graphics/backgrounds/GA13.TCG.lz"

@ ROM 7D6120..7D6180 (palette)
	.section .rom.007D6120, "a"
	.incbin "build/graphics/palettes/GA13.TCL.bin"

@ ROM 7D6180..7D6980 (tilemap)
	.section .rom.007D6180, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_00.TSC.bin"

@ ROM 7D6980..7D7180 (tilemap)
	.section .rom.007D6980, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_01.TSC.bin"

@ ROM 7D7180..7D7980 (tilemap)
	.section .rom.007D7180, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_02.TSC.bin"

@ ROM 7D7980..7D8180 (tilemap)
	.section .rom.007D7980, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_03.TSC.bin"

@ ROM 7D8180..7D8980 (tilemap)
	.section .rom.007D8180, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_04.TSC.bin"

@ ROM 7D8980..7D9180 (tilemap)
	.section .rom.007D8980, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_05.TSC.bin"

@ ROM 7D9180..7D9980 (tilemap)
	.section .rom.007D9180, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_06.TSC.bin"

@ ROM 7D9980..7DA180 (tilemap)
	.section .rom.007D9980, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_10.TSC.bin"

@ ROM 7DA180..7DA980 (tilemap)
	.section .rom.007DA180, "a"
	.incbin "build/graphics/tilemaps/nfp/GA13_11.TSC.bin"

@ ROM 7DA980..7DC77B (gfx)
	.section .rom.007DA980, "a"
	.incbin "build/graphics/backgrounds/GA24.TCG.lz"

@ ROM 7DC780..7DC7E0 (palette)
	.section .rom.007DC780, "a"
	.incbin "build/graphics/palettes/GA24.TCL.bin"

@ ROM 7DC7E0..7DCFE0 (tilemap)
	.section .rom.007DC7E0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_00.TSC.bin"

@ ROM 7DCFE0..7DD7E0 (tilemap)
	.section .rom.007DCFE0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_01.TSC.bin"

@ ROM 7DD7E0..7DDFE0 (tilemap)
	.section .rom.007DD7E0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_02.TSC.bin"

@ ROM 7DDFE0..7DE7E0 (tilemap)
	.section .rom.007DDFE0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_03.TSC.bin"

@ ROM 7DE7E0..7DEFE0 (tilemap)
	.section .rom.007DE7E0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_10.TSC.bin"

@ ROM 7DEFE0..7DF7E0 (tilemap)
	.section .rom.007DEFE0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_11.TSC.bin"

@ ROM 7DF7E0..7DFFE0 (tilemap)
	.section .rom.007DF7E0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_12.TSC.bin"

@ ROM 7DFFE0..7E07E0 (tilemap)
	.section .rom.007DFFE0, "a"
	.incbin "build/graphics/tilemaps/nfp/GA24_13.TSC.bin"

@ ROM 7E07E0..7E2814 (gfx)
	.section .rom.007E07E0, "a"
	.incbin "build/graphics/backgrounds/GA25.TCG.lz"

@ ROM 7E2820..7E2880 (palette)
	.section .rom.007E2820, "a"
	.incbin "build/graphics/palettes/GA25.TCL.bin"

@ ROM 7E2880..7E3080 (tilemap)
	.section .rom.007E2880, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_00.TSC.bin"

@ ROM 7E3080..7E3880 (tilemap)
	.section .rom.007E3080, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_01.TSC.bin"

@ ROM 7E3880..7E4080 (tilemap)
	.section .rom.007E3880, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_02.TSC.bin"

@ ROM 7E4080..7E4880 (tilemap)
	.section .rom.007E4080, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_03.TSC.bin"

@ ROM 7E4880..7E5080 (tilemap)
	.section .rom.007E4880, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_10.TSC.bin"

@ ROM 7E5080..7E5880 (tilemap)
	.section .rom.007E5080, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_11.TSC.bin"

@ ROM 7E5880..7E6080 (tilemap)
	.section .rom.007E5880, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_12.TSC.bin"

@ ROM 7E6080..7E6880 (tilemap)
	.section .rom.007E6080, "a"
	.incbin "build/graphics/tilemaps/nfp/GA25_13.TSC.bin"

@ ROM 7E6880..7E76B2 (gfx)
	.section .rom.007E6880, "a"
	.incbin "build/graphics/backgrounds/GA26.TCG.lz"

@ ROM 7E76C0..7E7720 (palette)
	.section .rom.007E76C0, "a"
	.incbin "build/graphics/palettes/GA26.TCL.bin"

@ ROM 7E7720..7E7F20 (tilemap)
	.section .rom.007E7720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA26_00.TSC.bin"

@ ROM 7E7F20..7E8720 (tilemap)
	.section .rom.007E7F20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA26_01.TSC.bin"

@ ROM 7E8720..7E8F20 (tilemap)
	.section .rom.007E8720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA26_10.TSC.bin"

@ ROM 7E8F20..7E9720 (tilemap)
	.section .rom.007E8F20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA26_11.TSC.bin"

@ ROM 7E9720..7EAEB8 (gfx)
	.section .rom.007E9720, "a"
	.incbin "build/graphics/tilesets/GA60.TCG.lz"

@ ROM 7EAEC0..7EAF20 (palette)
	.section .rom.007EAEC0, "a"
	.incbin "build/graphics/palettes/GA60.TCL.bin"

@ ROM 7EAF20..7EB720 (tilemap)
	.section .rom.007EAF20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_00.TSC.bin"

@ ROM 7EB720..7EBF20 (tilemap)
	.section .rom.007EB720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_01.TSC.bin"

@ ROM 7EBF20..7EC720 (tilemap)
	.section .rom.007EBF20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_02.TSC.bin"

@ ROM 7EC720..7ECF20 (tilemap)
	.section .rom.007EC720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_03.TSC.bin"

@ ROM 7ECF20..7ED720 (tilemap)
	.section .rom.007ECF20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_04.TSC.bin"

@ ROM 7ED720..7EDF20 (tilemap)
	.section .rom.007ED720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_05.TSC.bin"

@ ROM 7EDF20..7EE720 (tilemap)
	.section .rom.007EDF20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_06.TSC.bin"

@ ROM 7EE720..7EEF20 (tilemap)
	.section .rom.007EE720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_10.TSC.bin"

@ ROM 7EEF20..7EF720 (tilemap)
	.section .rom.007EEF20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_11.TSC.bin"

@ ROM 7EF720..7EFF20 (tilemap)
	.section .rom.007EF720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_12.TSC.bin"

@ ROM 7EFF20..7F0720 (tilemap)
	.section .rom.007EFF20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_13.TSC.bin"

@ ROM 7F0720..7F0F20 (tilemap)
	.section .rom.007F0720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_14.TSC.bin"

@ ROM 7F0F20..7F1720 (tilemap)
	.section .rom.007F0F20, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_15.TSC.bin"

@ ROM 7F1720..7F1F20 (tilemap)
	.section .rom.007F1720, "a"
	.incbin "build/graphics/tilemaps/nfp/GA60_16.TSC.bin"

@ ROM 7F1F20..7F3B27 (gfx)
	.section .rom.007F1F20, "a"
	.incbin "build/graphics/backgrounds/GA_BG01.KCG.lz"

@ ROM 7F3B30..7F3B50 (palette)
	.section .rom.007F3B30, "a"
	.incbin "build/graphics/palettes/GA_BG01.KCL.bin"

@ ROM 814B30..8161EF (gfx)
	.section .rom.00814B30, "a"
	.incbin "build/graphics/backgrounds/IT_BG01.KCG.lz"

@ ROM 8161F0..816210 (palette)
	.section .rom.008161F0, "a"
	.incbin "build/graphics/palettes/IT_BG01.KCL.bin"

@ ROM 816AD0..817B90 (gfx)
	.section .rom.00816AD0, "a"
	.incbin "build/graphics/backgrounds/IT_BG02.KCG.lz"

@ ROM 817B90..817BB0 (palette)
	.section .rom.00817B90, "a"
	.incbin "build/graphics/palettes/IT_BG02.KCL.bin"

@ ROM 818470..819C20 (gfx)
	.section .rom.00818470, "a"
	.incbin "build/graphics/backgrounds/JA05.TCG.lz"

@ ROM 819C20..819C80 (palette)
	.section .rom.00819C20, "a"
	.incbin "build/graphics/palettes/JA05.TCL.bin"

@ ROM 819C80..81A480 (tilemap)
	.section .rom.00819C80, "a"
	.incbin "build/graphics/tilemaps/nfp/JA05_A.TSC.bin"

@ ROM 81A480..81AC80 (tilemap)
	.section .rom.0081A480, "a"
	.incbin "build/graphics/tilemaps/nfp/JA05_B.TSC.bin"

@ ROM 81AC80..81B480 (tilemap)
	.section .rom.0081AC80, "a"
	.incbin "build/graphics/tilemaps/nfp/JA05_C.TSC.bin"

@ ROM 81B480..81BC80 (tilemap)
	.section .rom.0081B480, "a"
	.incbin "build/graphics/tilemaps/nfp/JA05_D.TSC.bin"

@ ROM 81F7C0..824A1E (gfx)
	.section .rom.0081F7C0, "a"
	.incbin "build/graphics/backgrounds/MAP00_A.KCG.lz"

@ ROM 824A20..824B20 (palette)
	.section .rom.00824A20, "a"
	.incbin "build/graphics/palettes/MAP00_A.KCL.bin"

@ ROM 85AF20..860BE0 (gfx)
	.section .rom.0085AF20, "a"
	.incbin "build/graphics/backgrounds/MAP01_1A.KCG.lz"

@ ROM 860BE0..860D20 (palette)
	.section .rom.00860BE0, "a"
	.incbin "build/graphics/palettes/MAP01_1A.KCL.bin"

@ ROM 866A30..86C1B1 (gfx)
	.section .rom.00866A30, "a"
	.incbin "build/graphics/backgrounds/MAP01_2A.KCG.lz"

@ ROM 86C1C0..86C300 (palette)
	.section .rom.0086C1C0, "a"
	.incbin "build/graphics/palettes/MAP01_2A.KCL.bin"

@ ROM 86F4C0..875AC9 (gfx)
	.section .rom.0086F4C0, "a"
	.incbin "build/graphics/backgrounds/MAP01_3A.KCG.lz"

@ ROM 875AD0..875C10 (palette)
	.section .rom.00875AD0, "a"
	.incbin "build/graphics/palettes/MAP01_3A.KCL.bin"

@ ROM 892240..8989FC (gfx)
	.section .rom.00892240, "a"
	.incbin "build/graphics/backgrounds/MAP01_A.KCG.lz"

@ ROM 898A00..898B20 (palette)
	.section .rom.00898A00, "a"
	.incbin "build/graphics/palettes/MAP01_A.KCL.bin"

@ ROM 89EDE0..8A4ACD (gfx)
	.section .rom.0089EDE0, "a"
	.incbin "build/graphics/backgrounds/MAP03_A.KCG.lz"

@ ROM 8A4AD0..8A4C10 (palette)
	.section .rom.008A4AD0, "a"
	.incbin "build/graphics/palettes/MAP03_A.KCL.bin"

@ ROM 8D56F0..8DBD44 (gfx)
	.section .rom.008D56F0, "a"
	.incbin "build/graphics/backgrounds/MAP04_6A.KCG.lz"

@ ROM 8DBD50..8DBE90 (palette)
	.section .rom.008DBD50, "a"
	.incbin "build/graphics/palettes/MAP04_6A.KCL.bin"

@ ROM 8E2070..8E6275 (gfx)
	.section .rom.008E2070, "a"
	.incbin "build/graphics/backgrounds/MAP04_7A.KCG.lz"

@ ROM 8E6280..8E63C0 (palette)
	.section .rom.008E6280, "a"
	.incbin "build/graphics/palettes/MAP04_7A.KCL.bin"

@ ROM 8EC480..8F24DD (gfx)
	.section .rom.008EC480, "a"
	.incbin "build/graphics/backgrounds/MAP04_A.KCG.lz"

@ ROM 8F24E0..8F2620 (palette)
	.section .rom.008F24E0, "a"
	.incbin "build/graphics/palettes/MAP04_A.KCL.bin"

@ ROM 93ABF0..93F7F9 (gfx)
	.section .rom.0093ABF0, "a"
	.incbin "build/graphics/backgrounds/MAP05_A.KCG.lz"

@ ROM 93F800..93F920 (palette)
	.section .rom.0093F800, "a"
	.incbin "build/graphics/palettes/MAP05_A.KCL.bin"

@ ROM 94BD50..951D8A (gfx)
	.section .rom.0094BD50, "a"
	.incbin "build/graphics/backgrounds/MAP06_1A.KCG.lz"

@ ROM 951D90..951E70 (palette)
	.section .rom.00951D90, "a"
	.incbin "build/graphics/palettes/MAP06_1A.KCL.bin"

@ ROM 95BE20..961BA3 (gfx)
	.section .rom.0095BE20, "a"
	.incbin "build/graphics/backgrounds/MAP06_2A.KCG.lz"

@ ROM 961BB0..961CD0 (palette)
	.section .rom.00961BB0, "a"
	.incbin "build/graphics/palettes/MAP06_2A.KCL.bin"

@ ROM 963D60..969D9A (gfx)
	.section .rom.00963D60, "a"
	.incbin "build/graphics/backgrounds/MAP06_A.KCG.lz"

@ ROM 969DA0..969E80 (palette)
	.section .rom.00969DA0, "a"
	.incbin "build/graphics/palettes/MAP06_A.KCL.bin"

@ ROM 980DC0..9859FF (gfx)
	.section .rom.00980DC0, "a"
	.incbin "build/graphics/backgrounds/MAP07_2A.KCG.lz"

@ ROM 985A00..985AC0 (palette)
	.section .rom.00985A00, "a"
	.incbin "build/graphics/palettes/MAP07_2A.KCL.bin"

@ ROM 988960..98E8F2 (gfx)
	.section .rom.00988960, "a"
	.incbin "build/graphics/backgrounds/MAP07_3A.KCG.lz"

@ ROM 98E900..98EA20 (palette)
	.section .rom.0098E900, "a"
	.incbin "build/graphics/palettes/MAP07_3A.KCL.bin"

@ ROM 992740..997B0A (gfx)
	.section .rom.00992740, "a"
	.incbin "build/graphics/backgrounds/MAP07_A.KCG.lz"

@ ROM 997B10..997B90 (palette)
	.section .rom.00997B10, "a"
	.incbin "build/graphics/palettes/MAP07_A.KCL.bin"

@ ROM A11790..A16AC5 (gfx)
	.section .rom.00A11790, "a"
	.incbin "build/graphics/backgrounds/MAP08_A.KCG.lz"

@ ROM A16AD0..A16BD0 (palette)
	.section .rom.00A16AD0, "a"
	.incbin "build/graphics/palettes/MAP08_A.KCL.bin"

@ ROM A1CE60..A22A31 (gfx)
	.section .rom.00A1CE60, "a"
	.incbin "build/graphics/backgrounds/MAP09_A.KCG.lz"

@ ROM A22A40..A22B80 (palette)
	.section .rom.00A22A40, "a"
	.incbin "build/graphics/palettes/MAP09_A.KCL.bin"

@ ROM A32DD0..A376D2 (gfx)
	.section .rom.00A32DD0, "a"
	.incbin "build/graphics/backgrounds/MAP10_1A.KCG.lz"

@ ROM A376E0..A377E0 (palette)
	.section .rom.00A376E0, "a"
	.incbin "build/graphics/palettes/MAP10_1A.KCL.bin"

@ ROM A3A480..A4031F (gfx)
	.section .rom.00A3A480, "a"
	.incbin "build/graphics/backgrounds/MAP10_A.KCG.lz"

@ ROM A40320..A40460 (palette)
	.section .rom.00A40320, "a"
	.incbin "build/graphics/palettes/MAP10_A.KCL.bin"

@ ROM A473C0..A4CCAC (gfx)
	.section .rom.00A473C0, "a"
	.incbin "build/graphics/backgrounds/MAP11_1A.KCG.lz"

@ ROM A4CCB0..A4CDD0 (palette)
	.section .rom.00A4CCB0, "a"
	.incbin "build/graphics/palettes/MAP11_1A.KCL.bin"

@ ROM A53290..A58D45 (gfx)
	.section .rom.00A53290, "a"
	.incbin "build/graphics/backgrounds/MAP11_2A.KCG.lz"

@ ROM A58D50..A58E10 (palette)
	.section .rom.00A58D50, "a"
	.incbin "build/graphics/palettes/MAP11_2A.KCL.bin"

@ ROM A5D7C0..A63230 (gfx)
	.section .rom.00A5D7C0, "a"
	.incbin "build/graphics/backgrounds/MAP11_A.KCG.lz"

@ ROM A63230..A63370 (palette)
	.section .rom.00A63230, "a"
	.incbin "build/graphics/palettes/MAP11_A.KCL.bin"

@ ROM A6F830..A74372 (gfx)
	.section .rom.00A6F830, "a"
	.incbin "build/graphics/backgrounds/MAP24_1A.KCG.lz"

@ ROM A74380..A74460 (palette)
	.section .rom.00A74380, "a"
	.incbin "build/graphics/palettes/MAP24_1A.KCL.bin"

@ ROM AC3390..AC888F (gfx)
	.section .rom.00AC3390, "a"
	.incbin "build/graphics/backgrounds/MAP24_4A.KCG.lz"

@ ROM AC8890..AC89D0 (palette)
	.section .rom.00AC8890, "a"
	.incbin "build/graphics/palettes/MAP24_4A.KCL.bin"

@ ROM AEA9D0..AF05B8 (gfx)
	.section .rom.00AEA9D0, "a"
	.incbin "build/graphics/backgrounds/MAP24_A.KCG.lz"

@ ROM AF05C0..AF0700 (palette)
	.section .rom.00AF05C0, "a"
	.incbin "build/graphics/palettes/MAP24_A.KCL.bin"

@ ROM AF3A60..AF9C6C (gfx)
	.section .rom.00AF3A60, "a"
	.incbin "build/graphics/backgrounds/MAP25_1A.KCG.lz"

@ ROM AF9C70..AF9DB0 (palette)
	.section .rom.00AF9C70, "a"
	.incbin "build/graphics/palettes/MAP25_1A.KCL.bin"

@ ROM BC7780..BCD519 (gfx)
	.section .rom.00BC7780, "a"
	.incbin "build/graphics/backgrounds/MAP25_5A.KCG.lz"

@ ROM BCD520..BCD660 (palette)
	.section .rom.00BCD520, "a"
	.incbin "build/graphics/palettes/MAP25_5A.KCL.bin"

@ ROM BD9410..BDE717 (gfx)
	.section .rom.00BD9410, "a"
	.incbin "build/graphics/backgrounds/MAP26_1A.KCG.lz"

@ ROM BDE720..BDE7E0 (palette)
	.section .rom.00BDE720, "a"
	.incbin "build/graphics/palettes/MAP26_1A.KCL.bin"

@ ROM C06ED0..C0CDAF (gfx)
	.section .rom.00C06ED0, "a"
	.incbin "build/graphics/backgrounds/MAP26_2A.KCG.lz"

@ ROM C0CDB0..C0CEF0 (palette)
	.section .rom.00C0CDB0, "a"
	.incbin "build/graphics/palettes/MAP26_2A.KCL.bin"

@ ROM CC8CC0..CCB832 (gfx)
	.section .rom.00CC8CC0, "a"
	.incbin "build/graphics/tilesets/MAP27_A.KCG.lz"

@ ROM CCB840..CCB8A0 (palette)
	.section .rom.00CCB840, "a"
	.incbin "build/graphics/palettes/MAP27_A.KCL.bin"

@ ROM D49D50..D49D66 (gfx)
	.section .rom.00D49D50, "a"
	.incbin "build/graphics/backgrounds/MAP99_A.KCG.lz"

@ ROM D49D70..D49D90 (palette)
	.section .rom.00D49D70, "a"
	.incbin "build/graphics/palettes/MAP99_A.KCL.bin"

@ ROM D4B650..D4D74C (gfx)
	.section .rom.00D4B650, "a"
	.incbin "build/graphics/backgrounds/ML_BG01.KCG.lz"

@ ROM D4D750..D4D770 (palette)
	.section .rom.00D4D750, "a"
	.incbin "build/graphics/palettes/ML_BG01.KCL.bin"

@ ROM D4E030..D4E455 (gfx)
	.section .rom.00D4E030, "a"
	.incbin "build/graphics/backgrounds/MWA.KCG.lz"

@ ROM D4E460..D4E480 (palette)
	.section .rom.00D4E460, "a"
	.incbin "build/graphics/palettes/MWA.KCL.bin"

@ ROM D4F540..D510B5 (gfx)
	.section .rom.00D4F540, "a"
	.incbin "build/graphics/backgrounds/NE01.TCG.lz"

@ ROM D510C0..D51120 (palette)
	.section .rom.00D510C0, "a"
	.incbin "build/graphics/palettes/NE01.TCL.bin"

@ ROM D51120..D51220 (tilemap)
	.section .rom.00D51120, "a"
	.incbin "build/graphics/tilemaps/nfp/NE01.TSC.bin"

@ ROM D51220..D51280 (palette)
	.section .rom.00D51220, "a"
	.incbin "build/graphics/palettes/NE05.TCL.bin"

@ ROM D51280..D52B7B (gfx)
	.section .rom.00D51280, "a"
	.incbin "build/graphics/backgrounds/NE13.TCG.lz"

@ ROM D52B80..D52BE0 (palette)
	.section .rom.00D52B80, "a"
	.incbin "build/graphics/palettes/NE13.TCL.bin"

@ ROM D52BE0..D52CE0 (tilemap)
	.section .rom.00D52BE0, "a"
	.incbin "build/graphics/tilemaps/nfp/NE13_A.TSC.bin"

@ ROM D52CE0..D52DE0 (tilemap)
	.section .rom.00D52CE0, "a"
	.incbin "build/graphics/tilemaps/nfp/NE13_B.TSC.bin"

@ ROM D52DE0..D52EE0 (tilemap)
	.section .rom.00D52DE0, "a"
	.incbin "build/graphics/tilemaps/nfp/NE13_C.TSC.bin"

@ ROM D52EE0..D55DA7 (gfx)
	.section .rom.00D52EE0, "a"
	.incbin "build/graphics/tilesets/NE21.TCG.lz"

@ ROM D55DB0..D55E10 (palette)
	.section .rom.00D55DB0, "a"
	.incbin "build/graphics/palettes/NE21.TCL.bin"

@ ROM D55E10..D56610 (tilemap)
	.section .rom.00D55E10, "a"
	.incbin "build/graphics/tilemaps/nfp/NE21_00.TSC.bin"

@ ROM D56610..D56E10 (tilemap)
	.section .rom.00D56610, "a"
	.incbin "build/graphics/tilemaps/nfp/NE21_01.TSC.bin"

@ ROM D56E10..D57610 (tilemap)
	.section .rom.00D56E10, "a"
	.incbin "build/graphics/tilemaps/nfp/NE21_02.TSC.bin"

@ ROM D57610..D57E10 (tilemap)
	.section .rom.00D57610, "a"
	.incbin "build/graphics/tilemaps/nfp/NE21_03.TSC.bin"

@ ROM D57E10..D58610 (tilemap)
	.section .rom.00D57E10, "a"
	.incbin "build/graphics/tilemaps/nfp/NE21_04.TSC.bin"

@ ROM D58610..D58E10 (tilemap)
	.section .rom.00D58610, "a"
	.incbin "build/graphics/tilemaps/nfp/NE21_05.TSC.bin"

@ ROM D58E10..D5AB90 (gfx)
	.section .rom.00D58E10, "a"
	.incbin "build/graphics/tilesets/NE32.TCG.lz"

@ ROM D5AB90..D5ABF0 (palette)
	.section .rom.00D5AB90, "a"
	.incbin "build/graphics/palettes/NE32.TCL.bin"

@ ROM D5ABF0..D5CBF0 (tilemap)
	.section .rom.00D5ABF0, "a"
	.incbin "build/graphics/tilemaps/nfp/NE32.TSC.bin"

@ ROM D5CBF0..D5E49B (gfx)
	.section .rom.00D5CBF0, "a"
	.incbin "build/graphics/backgrounds/NE33.TCG.lz"

@ ROM D5E4A0..D5E500 (palette)
	.section .rom.00D5E4A0, "a"
	.incbin "build/graphics/palettes/NE33.TCL.bin"

@ ROM D5E500..D5E600 (tilemap)
	.section .rom.00D5E500, "a"
	.incbin "build/graphics/tilemaps/nfp/NE33_A.TSC.bin"

@ ROM D5E600..D5E700 (tilemap)
	.section .rom.00D5E600, "a"
	.incbin "build/graphics/tilemaps/nfp/NE33_B.TSC.bin"

@ ROM D5E700..D5E800 (tilemap)
	.section .rom.00D5E700, "a"
	.incbin "build/graphics/tilemaps/nfp/NE33_C.TSC.bin"

@ ROM D6EAB0..D72769 (gfx)
	.section .rom.00D6EAB0, "a"
	.incbin "build/graphics/backgrounds/OP_01_A.KCG.lz"

@ ROM D72770..D727D0 (palette)
	.section .rom.00D72770, "a"
	.incbin "build/graphics/palettes/OP_01_A.KCL.bin"

@ ROM D736A0..D76E63 (gfx)
	.section .rom.00D736A0, "a"
	.incbin "build/graphics/backgrounds/OP_04_A.KCG.lz"

@ ROM D76E70..D76ED0 (palette)
	.section .rom.00D76E70, "a"
	.incbin "build/graphics/palettes/OP_04_A.KCL.bin"

@ ROM D77DA0..D7BD73 (gfx)
	.section .rom.00D77DA0, "a"
	.incbin "build/graphics/backgrounds/OP_05_A.KCG.lz"

@ ROM D7BD80..D7BDE0 (palette)
	.section .rom.00D7BD80, "a"
	.incbin "build/graphics/palettes/OP_05_A.KCL.bin"

@ ROM D7CCB0..D80082 (gfx)
	.section .rom.00D7CCB0, "a"
	.incbin "build/graphics/backgrounds/OP_06_A.KCG.lz"

@ ROM D80090..D80150 (palette)
	.section .rom.00D80090, "a"
	.incbin "build/graphics/palettes/OP_06_A.KCL.bin"

@ ROM D81890..D83CA2 (gfx)
	.section .rom.00D81890, "a"
	.incbin "build/graphics/tilesets/OP_07_A.KCG.lz"

@ ROM D83CB0..D83DF0 (palette)
	.section .rom.00D83CB0, "a"
	.incbin "build/graphics/palettes/OP_07_A.KCL.bin"

@ ROM D856B0..D87F5C (gfx)
	.section .rom.00D856B0, "a"
	.incbin "build/graphics/backgrounds/OP_08_A.KCG.lz"

@ ROM D87F60..D880A0 (palette)
	.section .rom.00D87F60, "a"
	.incbin "build/graphics/palettes/OP_08_A.KCL.bin"

@ ROM D89960..D8D07A (gfx)
	.section .rom.00D89960, "a"
	.incbin "build/graphics/backgrounds/OP_09_A.KCG.lz"

@ ROM D8D080..D8D1C0 (palette)
	.section .rom.00D8D080, "a"
	.incbin "build/graphics/palettes/OP_09_A.KCL.bin"

@ ROM D8EA80..D8FF99 (gfx)
	.section .rom.00D8EA80, "a"
	.incbin "build/graphics/backgrounds/OP_0A_A.KCG.lz"

@ ROM D8FFA0..D900E0 (palette)
	.section .rom.00D8FFA0, "a"
	.incbin "build/graphics/palettes/OP_0A_A.KCL.bin"

@ ROM D91C80..D9529D (gfx)
	.section .rom.00D91C80, "a"
	.incbin "build/graphics/backgrounds/PS_BG01.KCG.lz"

@ ROM D952A0..D952C0 (palette)
	.section .rom.00D952A0, "a"
	.incbin "build/graphics/palettes/PS_BG01.KCL.bin"

@ ROM D95B80..D979B0 (gfx)
	.section .rom.00D95B80, "a"
	.incbin "build/graphics/backgrounds/PV_BG01.KCG.lz"

@ ROM D979B0..D979D0 (palette)
	.section .rom.00D979B0, "a"
	.incbin "build/graphics/palettes/PV_BG01.KCL.bin"

@ ROM D98290..D986CA (gfx)
	.section .rom.00D98290, "a"
	.incbin "build/graphics/backgrounds/PV_BG11.KCG.lz"

@ ROM D986D0..D986F0 (palette)
	.section .rom.00D986D0, "a"
	.incbin "build/graphics/palettes/PV_BG11.KCL.bin"

@ ROM D98FB0..D9A5C4 (gfx)
	.section .rom.00D98FB0, "a"
	.incbin "build/graphics/tilesets/PW_BG01.KCG.lz"

@ ROM D9A5D0..D9A5F0 (palette)
	.section .rom.00D9A5D0, "a"
	.incbin "build/graphics/palettes/PW_BG01.KCL.bin"

@ ROM D9AEB0..D9C217 (gfx)
	.section .rom.00D9AEB0, "a"
	.incbin "build/graphics/tilesets/PW_BOX.KCG.lz"

@ ROM D9C220..D9C240 (palette)
	.section .rom.00D9C220, "a"
	.incbin "build/graphics/palettes/PW_BOX.KCL.bin"

@ ROM D9CB00..D9F944 (gfx)
	.section .rom.00D9CB00, "a"
	.incbin "build/graphics/backgrounds/SBA06.TCG.lz"

@ ROM D9F950..D9F9B0 (palette)
	.section .rom.00D9F950, "a"
	.incbin "build/graphics/palettes/SBA06.TCL.bin"

@ ROM D9F9B0..DA01B0 (tilemap)
	.section .rom.00D9F9B0, "a"
	.incbin "build/graphics/tilemaps/nfp/SBA06_00.TSC.bin"

@ ROM DA01B0..DA09B0 (tilemap)
	.section .rom.00DA01B0, "a"
	.incbin "build/graphics/tilemaps/nfp/SBA06_01.TSC.bin"

@ ROM DA2370..DA3577 (gfx)
	.section .rom.00DA2370, "a"
	.incbin "build/graphics/backgrounds/SK02.TCG.lz"

@ ROM DA3580..DA35E0 (palette)
	.section .rom.00DA3580, "a"
	.incbin "build/graphics/palettes/SK02.TCL.bin"

@ ROM DA35E0..DA36E0 (tilemap)
	.section .rom.00DA35E0, "a"
	.incbin "build/graphics/tilemaps/nfp/SK02_00.TSC.bin"

@ ROM DA36E0..DA37E0 (tilemap)
	.section .rom.00DA36E0, "a"
	.incbin "build/graphics/tilemaps/nfp/SK02_01.TSC.bin"

@ ROM DA37E0..DA38E0 (tilemap)
	.section .rom.00DA37E0, "a"
	.incbin "build/graphics/tilemaps/nfp/SK02_02.TSC.bin"

@ ROM DA38E0..DA39E0 (tilemap)
	.section .rom.00DA38E0, "a"
	.incbin "build/graphics/tilemaps/nfp/SK02_03.TSC.bin"

@ ROM DA39E0..DA4BE7 (gfx)
	.section .rom.00DA39E0, "a"
	.incbin "build/graphics/backgrounds/SK03.TCG.lz"

@ ROM DA4BF0..DA4C50 (palette)
	.section .rom.00DA4BF0, "a"
	.incbin "build/graphics/palettes/SK03.TCL.bin"

@ ROM DA4C50..DA5050 (tilemap)
	.section .rom.00DA4C50, "a"
	.incbin "build/graphics/tilemaps/nfp/SK03_00.TSC.bin"

@ ROM DA5050..DA5450 (tilemap)
	.section .rom.00DA5050, "a"
	.incbin "build/graphics/tilemaps/nfp/SK03_01.TSC.bin"

@ ROM DA5450..DA5850 (tilemap)
	.section .rom.00DA5450, "a"
	.incbin "build/graphics/tilemaps/nfp/SK03_02.TSC.bin"

@ ROM DA5850..DA5C50 (tilemap)
	.section .rom.00DA5850, "a"
	.incbin "build/graphics/tilemaps/nfp/SK03_03.TSC.bin"

@ ROM DA5C50..DA80AC (gfx)
	.section .rom.00DA5C50, "a"
	.incbin "build/graphics/backgrounds/SM_BG01.KCG.lz"

@ ROM DA80B0..DA80D0 (palette)
	.section .rom.00DA80B0, "a"
	.incbin "build/graphics/palettes/SM_BG01.KCL.bin"

@ ROM DA9BD0..DA9BF0 (palette)
	.section .rom.00DA9BD0, "a"
	.incbin "build/graphics/palettes/SM_BG12.KCL.bin"

@ ROM DAA4B0..DAB3D4 (gfx)
	.section .rom.00DAA4B0, "a"
	.incbin "build/graphics/backgrounds/SN06.TCG.lz"

@ ROM DAB3E0..DAB440 (palette)
	.section .rom.00DAB3E0, "a"
	.incbin "build/graphics/palettes/SN06.TCL.bin"

@ ROM DAB440..DABC40 (tilemap)
	.section .rom.00DAB440, "a"
	.incbin "build/graphics/tilemaps/nfp/SN06.TSC.bin"

@ ROM DABC40..DAE9E3 (gfx)
	.section .rom.00DABC40, "a"
	.incbin "build/graphics/tilesets/SN07.TCG.lz"

@ ROM DAE9F0..DAEA50 (palette)
	.section .rom.00DAE9F0, "a"
	.incbin "build/graphics/palettes/SN07.TCL.bin"

@ ROM DAEA50..DB0A50 (tilemap)
	.section .rom.00DAEA50, "a"
	.incbin "build/graphics/tilemaps/nfp/SN07_A.TSC.bin"

@ ROM DB0A50..DB2A50 (tilemap)
	.section .rom.00DB0A50, "a"
	.incbin "build/graphics/tilemaps/nfp/SN07_B.TSC.bin"

@ ROM DB33A0..DB5778 (gfx)
	.section .rom.00DB33A0, "a"
	.incbin "build/graphics/backgrounds/SP_BG01.KCG.lz"

@ ROM DB5780..DB57A0 (palette)
	.section .rom.00DB5780, "a"
	.incbin "build/graphics/palettes/SP_BG01.KCL.bin"

@ ROM DB6060..DB89C9 (gfx)
	.section .rom.00DB6060, "a"
	.incbin "build/graphics/backgrounds/SP_BG11.KCG.lz"

@ ROM DB89D0..DB89F0 (palette)
	.section .rom.00DB89D0, "a"
	.incbin "build/graphics/palettes/SP_BG11.KCL.bin"

@ ROM DB92B0..DB9D37 (gfx)
	.section .rom.00DB92B0, "a"
	.incbin "build/graphics/backgrounds/SP_BG12.KCG.lz"

@ ROM DB9D40..DB9D60 (palette)
	.section .rom.00DB9D40, "a"
	.incbin "build/graphics/palettes/SP_BG12.KCL.bin"

@ ROM DBA620..DBC95D (gfx)
	.section .rom.00DBA620, "a"
	.incbin "build/graphics/backgrounds/SP_BG21.KCG.lz"

@ ROM DBC960..DBC980 (palette)
	.section .rom.00DBC960, "a"
	.incbin "build/graphics/palettes/SP_BG21.KCL.bin"

@ ROM DBD240..DBFA01 (gfx)
	.section .rom.00DBD240, "a"
	.incbin "build/graphics/backgrounds/SP_BG22.KCG.lz"

@ ROM DBFA10..DBFA30 (palette)
	.section .rom.00DBFA10, "a"
	.incbin "build/graphics/palettes/SP_BG22.KCL.bin"

@ ROM DC8210..DCAFB3 (gfx)
	.section .rom.00DC8210, "a"
	.incbin "build/graphics/tilesets/SSN07.TCG.lz"

@ ROM DCAFC0..DCB020 (palette)
	.section .rom.00DCAFC0, "a"
	.incbin "build/graphics/palettes/SSN07.TCL.bin"

@ ROM DCB020..DCD020 (tilemap)
	.section .rom.00DCB020, "a"
	.incbin "build/graphics/tilemaps/nfp/SSN07_A.TSC.bin"

@ ROM DCD020..DCF020 (tilemap)
	.section .rom.00DCD020, "a"
	.incbin "build/graphics/tilemaps/nfp/SSN07_B.TSC.bin"

@ ROM DCF020..DD0394 (gfx)
	.section .rom.00DCF020, "a"
	.incbin "build/graphics/backgrounds/ST_BG01.KCG.lz"

@ ROM DD03A0..DD03C0 (palette)
	.section .rom.00DD03A0, "a"
	.incbin "build/graphics/palettes/ST_BG01.KCL.bin"

@ ROM DD0C80..DD1D10 (gfx)
	.section .rom.00DD0C80, "a"
	.incbin "build/graphics/backgrounds/ST_BG02.KCG.lz"

@ ROM DD1D10..DD1D30 (palette)
	.section .rom.00DD1D10, "a"
	.incbin "build/graphics/palettes/ST_BG02.KCL.bin"

@ ROM DD25F0..DD3624 (gfx)
	.section .rom.00DD25F0, "a"
	.incbin "build/graphics/backgrounds/ST_BG03.KCG.lz"

@ ROM DD3630..DD3650 (palette)
	.section .rom.00DD3630, "a"
	.incbin "build/graphics/palettes/ST_BG03.KCL.bin"

@ ROM DD3F10..DD60F6 (gfx)
	.section .rom.00DD3F10, "a"
	.incbin "build/graphics/backgrounds/ST_BG11.KCG.lz"

@ ROM DD6100..DD6120 (palette)
	.section .rom.00DD6100, "a"
	.incbin "build/graphics/palettes/ST_BG11.KCL.bin"

@ ROM F1A300..F1A320 (palette)
	.section .rom.00F1A300, "a"
	.incbin "build/graphics/palettes/T_C01.KCL.bin"

@ ROM F1ABE0..F1B027 (gfx)
	.section .rom.00F1ABE0, "a"
	.incbin "build/graphics/backgrounds/T_C02.KCG.lz"

@ ROM F1B030..F1B050 (palette)
	.section .rom.00F1B030, "a"
	.incbin "build/graphics/palettes/T_C02.KCL.bin"

@ ROM F1B910..F1E649 (gfx)
	.section .rom.00F1B910, "a"
	.incbin "build/graphics/backgrounds/T_ML_BG.KCG.lz"

@ ROM F1E650..F1E690 (palette)
	.section .rom.00F1E650, "a"
	.incbin "build/graphics/palettes/T_ML_BG.KCL.bin"

@ ROM F213A0..F21420 (palette)
	.section .rom.00F213A0, "a"
	.incbin "build/graphics/palettes/T_TTL06.KCL.bin"

@ ROM F23E20..F25C70 (gfx)
	.section .rom.00F23E20, "a"
	.incbin "build/graphics/backgrounds/WM_BG01.KCG.lz"

@ ROM F25C70..F25C90 (palette)
	.section .rom.00F25C70, "a"
	.incbin "build/graphics/palettes/WM_BG01.KCL.bin"

@ ROM F26550..F27607 (gfx)
	.section .rom.00F26550, "a"
	.incbin "build/graphics/backgrounds/WM_BG02.KCG.lz"

@ ROM F27610..F27630 (palette)
	.section .rom.00F27610, "a"
	.incbin "build/graphics/palettes/WM_BG02.KCL.bin"
