@ Japanese assets replaced together by the English build.
@ Generated by tools/split.py; section names preserve ROM order.

@ ROM 5AEAF0..791060 (sprites)
	.section .rom.005AEAF0, "a"
	.incbin "build/graphics/ncd/EFFECT.ncd"

@ ROM DA8990..DA9BC4 (gfx)
	.section .rom.00DA8990, "a"
	.incbin "build/graphics/backgrounds/SM_BG12.KCG.lz"

@ ROM DA9BF0..DAA4B0 (map)
	.section .rom.00DA9BF0, "a"
	.incbin "build/maps/nfp/SM_BG12.KMP.bin"

@ ROM DD69E0..F12390 (sprites)
	.section .rom.00DD69E0, "a"
	.incbin "build/graphics/ncd/SYSTEM.ncd"

@ ROM F19AA0..F1A2FB (gfx)
	.section .rom.00F19AA0, "a"
	.incbin "build/graphics/backgrounds/T_C01.KCG.lz"

@ ROM F1A320..F1ABE0 (map)
	.section .rom.00F1A320, "a"
	.incbin "build/maps/nfp/T_C01.KMP.bin"

@ ROM F1EF50..F21395 (gfx)
	.section .rom.00F1EF50, "a"
	.incbin "build/graphics/backgrounds/T_TTL06.KCG.lz"

@ ROM F21420..F21CE0 (map)
	.section .rom.00F21420, "a"
	.incbin "build/maps/nfp/T_TTL06.KMP.bin"
