@ map assets ROM sections.
@ Generated by tools/split.py; section names preserve ROM order.

@ ROM 1C3D40..1C9E00 (map)
	.section .rom.001C3D40, "a"
	.incbin "build/maps/nfp/AD0_B_A.KMP.bin"

@ ROM 1CF8F0..1D17B0 (map)
	.section .rom.001CF8F0, "a"
	.incbin "build/maps/nfp/AD0_P_0A.KMP.bin"

@ ROM 1D17B0..1D3670 (map)
	.section .rom.001D17B0, "a"
	.incbin "build/maps/nfp/AD0_P_1A.KMP.bin"

@ ROM 1D3670..1D5530 (map)
	.section .rom.001D3670, "a"
	.incbin "build/maps/nfp/AD0_P_2A.KMP.bin"

@ ROM 1D5530..1D73F0 (map)
	.section .rom.001D5530, "a"
	.incbin "build/maps/nfp/AD0_P_3A.KMP.bin"

@ ROM 1D73F0..1DA1B0 (map)
	.section .rom.001D73F0, "a"
	.incbin "build/maps/nfp/AD0_P_4A.KMP.bin"

@ ROM 1DA1B0..1DCF70 (map)
	.section .rom.001DA1B0, "a"
	.incbin "build/maps/nfp/AD0_P_5A.KMP.bin"

@ ROM 1DCF70..1DFD30 (map)
	.section .rom.001DCF70, "a"
	.incbin "build/maps/nfp/AD0_P_6A.KMP.bin"

@ ROM 1DFD30..1E2AF0 (map)
	.section .rom.001DFD30, "a"
	.incbin "build/maps/nfp/AD0_P_7A.KMP.bin"

@ ROM 1E2AF0..1E8BB0 (map)
	.section .rom.001E2AF0, "a"
	.incbin "build/maps/nfp/AD0_R_0A.KMP.bin"

@ ROM 1E8BB0..1EEC70 (map)
	.section .rom.001E8BB0, "a"
	.incbin "build/maps/nfp/AD0_R_1A.KMP.bin"

@ ROM 1EEC70..1F4D30 (map)
	.section .rom.001EEC70, "a"
	.incbin "build/maps/nfp/AD0_R_2A.KMP.bin"

@ ROM 1F4D30..1FADF0 (map)
	.section .rom.001F4D30, "a"
	.incbin "build/maps/nfp/AD0_R_3A.KMP.bin"

@ ROM 1FADF0..200EB0 (map)
	.section .rom.001FADF0, "a"
	.incbin "build/maps/nfp/AD0_R_4A.KMP.bin"

@ ROM 200EB0..206F70 (map)
	.section .rom.00200EB0, "a"
	.incbin "build/maps/nfp/AD0_R_5A.KMP.bin"

@ ROM 206F70..20D030 (map)
	.section .rom.00206F70, "a"
	.incbin "build/maps/nfp/AD0_R_6A.KMP.bin"

@ ROM 20D030..2130F0 (map)
	.section .rom.0020D030, "a"
	.incbin "build/maps/nfp/AD0_R_7A.KMP.bin"

@ ROM 2130F0..2191B0 (map)
	.section .rom.002130F0, "a"
	.incbin "build/maps/nfp/AD0_R_8A.KMP.bin"

@ ROM 2191B0..21F270 (map)
	.section .rom.002191B0, "a"
	.incbin "build/maps/nfp/AD0_R_9A.KMP.bin"

@ ROM 21F270..225330 (map)
	.section .rom.0021F270, "a"
	.incbin "build/maps/nfp/AD0_R_AA.KMP.bin"

@ ROM 225330..22B3F0 (map)
	.section .rom.00225330, "a"
	.incbin "build/maps/nfp/AD0_R_BA.KMP.bin"

@ ROM 22B3F0..2314B0 (map)
	.section .rom.0022B3F0, "a"
	.incbin "build/maps/nfp/AD0_R_CA.KMP.bin"

@ ROM 2314B0..237570 (map)
	.section .rom.002314B0, "a"
	.incbin "build/maps/nfp/AD1_B_A.KMP.bin"

@ ROM 23C000..23DEC0 (map)
	.section .rom.0023C000, "a"
	.incbin "build/maps/nfp/AD1_P_0A.KMP.bin"

@ ROM 23DEC0..23FD80 (map)
	.section .rom.0023DEC0, "a"
	.incbin "build/maps/nfp/AD1_P_1A.KMP.bin"

@ ROM 23FD80..241C40 (map)
	.section .rom.0023FD80, "a"
	.incbin "build/maps/nfp/AD1_P_2A.KMP.bin"

@ ROM 241C40..243B00 (map)
	.section .rom.00241C40, "a"
	.incbin "build/maps/nfp/AD1_P_3A.KMP.bin"

@ ROM 243B00..2468C0 (map)
	.section .rom.00243B00, "a"
	.incbin "build/maps/nfp/AD1_P_4A.KMP.bin"

@ ROM 2468C0..249680 (map)
	.section .rom.002468C0, "a"
	.incbin "build/maps/nfp/AD1_P_5A.KMP.bin"

@ ROM 249680..24C440 (map)
	.section .rom.00249680, "a"
	.incbin "build/maps/nfp/AD1_P_6A.KMP.bin"

@ ROM 24C440..24F200 (map)
	.section .rom.0024C440, "a"
	.incbin "build/maps/nfp/AD1_P_7A.KMP.bin"

@ ROM 24F200..2552C0 (map)
	.section .rom.0024F200, "a"
	.incbin "build/maps/nfp/AD1_R_0A.KMP.bin"

@ ROM 2552C0..25B380 (map)
	.section .rom.002552C0, "a"
	.incbin "build/maps/nfp/AD1_R_1A.KMP.bin"

@ ROM 25B380..261440 (map)
	.section .rom.0025B380, "a"
	.incbin "build/maps/nfp/AD1_R_2A.KMP.bin"

@ ROM 261440..267500 (map)
	.section .rom.00261440, "a"
	.incbin "build/maps/nfp/AD1_R_3A.KMP.bin"

@ ROM 267500..26D5C0 (map)
	.section .rom.00267500, "a"
	.incbin "build/maps/nfp/AD1_R_4A.KMP.bin"

@ ROM 26D5C0..273680 (map)
	.section .rom.0026D5C0, "a"
	.incbin "build/maps/nfp/AD1_R_5A.KMP.bin"

@ ROM 273680..279740 (map)
	.section .rom.00273680, "a"
	.incbin "build/maps/nfp/AD1_R_6A.KMP.bin"

@ ROM 279740..27F800 (map)
	.section .rom.00279740, "a"
	.incbin "build/maps/nfp/AD1_R_7A.KMP.bin"

@ ROM 27F800..2858C0 (map)
	.section .rom.0027F800, "a"
	.incbin "build/maps/nfp/AD1_R_8A.KMP.bin"

@ ROM 2858C0..28B980 (map)
	.section .rom.002858C0, "a"
	.incbin "build/maps/nfp/AD1_R_9A.KMP.bin"

@ ROM 28B980..291A40 (map)
	.section .rom.0028B980, "a"
	.incbin "build/maps/nfp/AD1_R_AA.KMP.bin"

@ ROM 291A40..297B00 (map)
	.section .rom.00291A40, "a"
	.incbin "build/maps/nfp/AD1_R_BA.KMP.bin"

@ ROM 297B00..29DBC0 (map)
	.section .rom.00297B00, "a"
	.incbin "build/maps/nfp/AD1_R_CA.KMP.bin"

@ ROM 29DBC0..2A3C80 (map)
	.section .rom.0029DBC0, "a"
	.incbin "build/maps/nfp/AD3_B_A.KMP.bin"

@ ROM 2A89D0..2AA890 (map)
	.section .rom.002A89D0, "a"
	.incbin "build/maps/nfp/AD3_P_0A.KMP.bin"

@ ROM 2AA890..2AC750 (map)
	.section .rom.002AA890, "a"
	.incbin "build/maps/nfp/AD3_P_1A.KMP.bin"

@ ROM 2AC750..2AE610 (map)
	.section .rom.002AC750, "a"
	.incbin "build/maps/nfp/AD3_P_2A.KMP.bin"

@ ROM 2AE610..2B04D0 (map)
	.section .rom.002AE610, "a"
	.incbin "build/maps/nfp/AD3_P_3A.KMP.bin"

@ ROM 2B04D0..2B3290 (map)
	.section .rom.002B04D0, "a"
	.incbin "build/maps/nfp/AD3_P_4A.KMP.bin"

@ ROM 2B3290..2B6050 (map)
	.section .rom.002B3290, "a"
	.incbin "build/maps/nfp/AD3_P_5A.KMP.bin"

@ ROM 2B6050..2B8E10 (map)
	.section .rom.002B6050, "a"
	.incbin "build/maps/nfp/AD3_P_6A.KMP.bin"

@ ROM 2B8E10..2BBBD0 (map)
	.section .rom.002B8E10, "a"
	.incbin "build/maps/nfp/AD3_P_7A.KMP.bin"

@ ROM 2BBBD0..2C1C90 (map)
	.section .rom.002BBBD0, "a"
	.incbin "build/maps/nfp/AD3_R_0A.KMP.bin"

@ ROM 2C1C90..2C7D50 (map)
	.section .rom.002C1C90, "a"
	.incbin "build/maps/nfp/AD3_R_1A.KMP.bin"

@ ROM 2C7D50..2CDE10 (map)
	.section .rom.002C7D50, "a"
	.incbin "build/maps/nfp/AD3_R_2A.KMP.bin"

@ ROM 2CDE10..2D3ED0 (map)
	.section .rom.002CDE10, "a"
	.incbin "build/maps/nfp/AD3_R_3A.KMP.bin"

@ ROM 2D3ED0..2D9F90 (map)
	.section .rom.002D3ED0, "a"
	.incbin "build/maps/nfp/AD3_R_4A.KMP.bin"

@ ROM 2D9F90..2E0050 (map)
	.section .rom.002D9F90, "a"
	.incbin "build/maps/nfp/AD3_R_5A.KMP.bin"

@ ROM 2E0050..2E6110 (map)
	.section .rom.002E0050, "a"
	.incbin "build/maps/nfp/AD3_R_6A.KMP.bin"

@ ROM 2E6110..2EC1D0 (map)
	.section .rom.002E6110, "a"
	.incbin "build/maps/nfp/AD3_R_7A.KMP.bin"

@ ROM 2EC1D0..2F2290 (map)
	.section .rom.002EC1D0, "a"
	.incbin "build/maps/nfp/AD3_R_8A.KMP.bin"

@ ROM 2F2290..2F8350 (map)
	.section .rom.002F2290, "a"
	.incbin "build/maps/nfp/AD3_R_9A.KMP.bin"

@ ROM 2F8350..2FE410 (map)
	.section .rom.002F8350, "a"
	.incbin "build/maps/nfp/AD3_R_AA.KMP.bin"

@ ROM 2FE410..3044D0 (map)
	.section .rom.002FE410, "a"
	.incbin "build/maps/nfp/AD3_R_BA.KMP.bin"

@ ROM 3044D0..30A590 (map)
	.section .rom.003044D0, "a"
	.incbin "build/maps/nfp/AD3_R_CA.KMP.bin"

@ ROM 30A590..310650 (map)
	.section .rom.0030A590, "a"
	.incbin "build/maps/nfp/AD4_B_A.KMP.bin"

@ ROM 313DF0..315CB0 (map)
	.section .rom.00313DF0, "a"
	.incbin "build/maps/nfp/AD4_P_0A.KMP.bin"

@ ROM 315CB0..317B70 (map)
	.section .rom.00315CB0, "a"
	.incbin "build/maps/nfp/AD4_P_1A.KMP.bin"

@ ROM 317B70..319A30 (map)
	.section .rom.00317B70, "a"
	.incbin "build/maps/nfp/AD4_P_2A.KMP.bin"

@ ROM 319A30..31B8F0 (map)
	.section .rom.00319A30, "a"
	.incbin "build/maps/nfp/AD4_P_3A.KMP.bin"

@ ROM 31B8F0..31E6B0 (map)
	.section .rom.0031B8F0, "a"
	.incbin "build/maps/nfp/AD4_P_4A.KMP.bin"

@ ROM 31E6B0..321470 (map)
	.section .rom.0031E6B0, "a"
	.incbin "build/maps/nfp/AD4_P_5A.KMP.bin"

@ ROM 321470..324230 (map)
	.section .rom.00321470, "a"
	.incbin "build/maps/nfp/AD4_P_6A.KMP.bin"

@ ROM 324230..326FF0 (map)
	.section .rom.00324230, "a"
	.incbin "build/maps/nfp/AD4_P_7A.KMP.bin"

@ ROM 326FF0..32D0B0 (map)
	.section .rom.00326FF0, "a"
	.incbin "build/maps/nfp/AD4_R_0A.KMP.bin"

@ ROM 32D0B0..333170 (map)
	.section .rom.0032D0B0, "a"
	.incbin "build/maps/nfp/AD4_R_1A.KMP.bin"

@ ROM 333170..339230 (map)
	.section .rom.00333170, "a"
	.incbin "build/maps/nfp/AD4_R_2A.KMP.bin"

@ ROM 339230..33F2F0 (map)
	.section .rom.00339230, "a"
	.incbin "build/maps/nfp/AD4_R_3A.KMP.bin"

@ ROM 33F2F0..3453B0 (map)
	.section .rom.0033F2F0, "a"
	.incbin "build/maps/nfp/AD4_R_4A.KMP.bin"

@ ROM 3453B0..34B470 (map)
	.section .rom.003453B0, "a"
	.incbin "build/maps/nfp/AD4_R_5A.KMP.bin"

@ ROM 34B470..351530 (map)
	.section .rom.0034B470, "a"
	.incbin "build/maps/nfp/AD4_R_6A.KMP.bin"

@ ROM 351530..3575F0 (map)
	.section .rom.00351530, "a"
	.incbin "build/maps/nfp/AD4_R_7A.KMP.bin"

@ ROM 3575F0..35D6B0 (map)
	.section .rom.003575F0, "a"
	.incbin "build/maps/nfp/AD4_R_8A.KMP.bin"

@ ROM 35D6B0..363770 (map)
	.section .rom.0035D6B0, "a"
	.incbin "build/maps/nfp/AD4_R_9A.KMP.bin"

@ ROM 363770..369830 (map)
	.section .rom.00363770, "a"
	.incbin "build/maps/nfp/AD4_R_AA.KMP.bin"

@ ROM 369830..36F8F0 (map)
	.section .rom.00369830, "a"
	.incbin "build/maps/nfp/AD4_R_BA.KMP.bin"

@ ROM 36F8F0..3759B0 (map)
	.section .rom.0036F8F0, "a"
	.incbin "build/maps/nfp/AD4_R_CA.KMP.bin"

@ ROM 377750..378010 (map)
	.section .rom.00377750, "a"
	.incbin "build/maps/nfp/AD_BG01.KMP.bin"

@ ROM 378980..379240 (map)
	.section .rom.00378980, "a"
	.incbin "build/maps/nfp/AD_BG02.KMP.bin"

@ ROM 37B350..37BC10 (map)
	.section .rom.0037B350, "a"
	.incbin "build/maps/nfp/AL_BG01.KMP.bin"

@ ROM 37C6C0..37CF80 (map)
	.section .rom.0037C6C0, "a"
	.incbin "build/maps/nfp/AL_BG02.KMP.bin"

@ ROM 37F2E0..37FBA0 (map)
	.section .rom.0037F2E0, "a"
	.incbin "build/maps/nfp/AS_BG01.KMP.bin"

@ ROM 380FE0..3818A0 (map)
	.section .rom.00380FE0, "a"
	.incbin "build/maps/nfp/AS_BG02.KMP.bin"

@ ROM 3835F0..383EB0 (map)
	.section .rom.003835F0, "a"
	.incbin "build/maps/nfp/AT_BG01.KMP.bin"

@ ROM 56E5B0..56EE70 (map)
	.section .rom.0056E5B0, "a"
	.incbin "build/maps/nfp/CLPASS.KMP.bin"

@ ROM 570790..571050 (map)
	.section .rom.00570790, "a"
	.incbin "build/maps/nfp/CM_BG01.KMP.bin"

@ ROM 572190..572A50 (map)
	.section .rom.00572190, "a"
	.incbin "build/maps/nfp/CM_BG02.KMP.bin"

@ ROM 5AA2B0..5AAB70 (map)
	.section .rom.005AA2B0, "a"
	.incbin "build/maps/nfp/DS_BG01.KMP.bin"

@ ROM 5ABAD0..5AC390 (map)
	.section .rom.005ABAD0, "a"
	.incbin "build/maps/nfp/DS_BG02.KMP.bin"

@ ROM 5AE230..5AEAF0 (map)
	.section .rom.005AE230, "a"
	.incbin "build/maps/nfp/EFCSTART.KMP.bin"

@ ROM 7F3B50..7F4410 (map)
	.section .rom.007F3B50, "a"
	.incbin "build/maps/nfp/GA_BG01.KMP.bin"

@ ROM 816210..816AD0 (map)
	.section .rom.00816210, "a"
	.incbin "build/maps/nfp/IT_BG01.KMP.bin"

@ ROM 817BB0..818470 (map)
	.section .rom.00817BB0, "a"
	.incbin "build/maps/nfp/IT_BG02.KMP.bin"

@ ROM 824B20..85ABE0 (map)
	.section .rom.00824B20, "a"
	.incbin "build/maps/nfp/MAP00_A.KMP.bin"

@ ROM 860D20..8667E0 (map)
	.section .rom.00860D20, "a"
	.incbin "build/maps/nfp/MAP01_1A.KMP.bin"

@ ROM 86C300..86F3C0 (map)
	.section .rom.0086C300, "a"
	.incbin "build/maps/nfp/MAP01_2A.KMP.bin"

@ ROM 875C10..8804D0 (map)
	.section .rom.00875C10, "a"
	.incbin "build/maps/nfp/MAP01_3A.KMP.bin"

@ ROM 8807C0..886880 (map)
	.section .rom.008807C0, "a"
	.incbin "build/maps/nfp/MAP01_4A.KMP.bin"

@ ROM 886A30..88CAF0 (map)
	.section .rom.00886A30, "a"
	.incbin "build/maps/nfp/MAP01_5A.KMP.bin"

@ ROM 88CD20..892240 (map)
	.section .rom.0088CD20, "a"
	.incbin "build/maps/nfp/MAP01_6A.KMP.bin"

@ ROM 898B20..89EBE0 (map)
	.section .rom.00898B20, "a"
	.incbin "build/maps/nfp/MAP01_A.KMP.bin"

@ ROM 8A4C10..8AACD0 (map)
	.section .rom.008A4C10, "a"
	.incbin "build/maps/nfp/MAP03_A.KMP.bin"

@ ROM 8AAE30..8CD330 (map)
	.section .rom.008AAE30, "a"
	.incbin "build/maps/nfp/MAP04_4A.KMP.bin"

@ ROM 8CD520..8D54A0 (map)
	.section .rom.008CD520, "a"
	.incbin "build/maps/nfp/MAP04_5A.KMP.bin"

@ ROM 8DBE90..8E1F50 (map)
	.section .rom.008DBE90, "a"
	.incbin "build/maps/nfp/MAP04_6A.KMP.bin"

@ ROM 8E63C0..8EC480 (map)
	.section .rom.008E63C0, "a"
	.incbin "build/maps/nfp/MAP04_7A.KMP.bin"

@ ROM 8F2620..93A6E0 (map)
	.section .rom.008F2620, "a"
	.incbin "build/maps/nfp/MAP04_A.KMP.bin"

@ ROM 93F920..94B9E0 (map)
	.section .rom.0093F920, "a"
	.incbin "build/maps/nfp/MAP05_A.KMP.bin"

@ ROM 951E70..95BB30 (map)
	.section .rom.00951E70, "a"
	.incbin "build/maps/nfp/MAP06_1A.KMP.bin"

@ ROM 961CD0..963B90 (map)
	.section .rom.00961CD0, "a"
	.incbin "build/maps/nfp/MAP06_2A.KMP.bin"

@ ROM 969E80..96CF40 (map)
	.section .rom.00969E80, "a"
	.incbin "build/maps/nfp/MAP06_A.KMP.bin"

@ ROM 96D060..980D20 (map)
	.section .rom.0096D060, "a"
	.incbin "build/maps/nfp/MAP07_1A.KMP.bin"

@ ROM 985AC0..988880 (map)
	.section .rom.00985AC0, "a"
	.incbin "build/maps/nfp/MAP07_2A.KMP.bin"

@ ROM 98EA20..9926A0 (map)
	.section .rom.0098EA20, "a"
	.incbin "build/maps/nfp/MAP07_3A.KMP.bin"

@ ROM 997B90..A11130 (map)
	.section .rom.00997B90, "a"
	.incbin "build/maps/nfp/MAP07_A.KMP.bin"

@ ROM A16BD0..A1CC90 (map)
	.section .rom.00A16BD0, "a"
	.incbin "build/maps/nfp/MAP08_A.KMP.bin"

@ ROM A22B80..A329C0 (map)
	.section .rom.00A22B80, "a"
	.incbin "build/maps/nfp/MAP09_A.KMP.bin"

@ ROM A377E0..A3A2A0 (map)
	.section .rom.00A377E0, "a"
	.incbin "build/maps/nfp/MAP10_1A.KMP.bin"

@ ROM A40460..A47120 (map)
	.section .rom.00A40460, "a"
	.incbin "build/maps/nfp/MAP10_A.KMP.bin"

@ ROM A4CDD0..A52E90 (map)
	.section .rom.00A4CDD0, "a"
	.incbin "build/maps/nfp/MAP11_1A.KMP.bin"

@ ROM A58E10..A5D6D0 (map)
	.section .rom.00A58E10, "a"
	.incbin "build/maps/nfp/MAP11_2A.KMP.bin"

@ ROM A63370..A6F430 (map)
	.section .rom.00A63370, "a"
	.incbin "build/maps/nfp/MAP11_A.KMP.bin"

@ ROM A74460..A97320 (map)
	.section .rom.00A74460, "a"
	.incbin "build/maps/nfp/MAP24_1A.KMP.bin"

@ ROM A97750..AC3010 (map)
	.section .rom.00A97750, "a"
	.incbin "build/maps/nfp/MAP24_2A.KMP.bin"

@ ROM AC89D0..AEA690 (map)
	.section .rom.00AC89D0, "a"
	.incbin "build/maps/nfp/MAP24_4A.KMP.bin"

@ ROM AF0700..AF37C0 (map)
	.section .rom.00AF0700, "a"
	.incbin "build/maps/nfp/MAP24_A.KMP.bin"

@ ROM AF9DB0..B1EA70 (map)
	.section .rom.00AF9DB0, "a"
	.incbin "build/maps/nfp/MAP25_1A.KMP.bin"

@ ROM B1EC50..B4ED10 (map)
	.section .rom.00B1EC50, "a"
	.incbin "build/maps/nfp/MAP25_2A.KMP.bin"

@ ROM B4F220..BC72E0 (map)
	.section .rom.00B4F220, "a"
	.incbin "build/maps/nfp/MAP25_4A.KMP.bin"

@ ROM BCD660..BD9120 (map)
	.section .rom.00BCD660, "a"
	.incbin "build/maps/nfp/MAP25_5A.KMP.bin"

@ ROM BDE7E0..C06B90 (map)
	.section .rom.00BDE7E0, "a"
	.incbin "build/maps/nfp/MAP26_1A.KMP.bin"

@ ROM C0CEF0..C183B0 (map)
	.section .rom.00C0CEF0, "a"
	.incbin "build/maps/nfp/MAP26_2A.KMP.bin"

@ ROM C185B0..C5AC70 (map)
	.section .rom.00C185B0, "a"
	.incbin "build/maps/nfp/MAP26_3A.KMP.bin"

@ ROM C5B020..CB8D10 (map)
	.section .rom.00C5B020, "a"
	.incbin "build/maps/nfp/MAP26_5A.KMP.bin"

@ ROM CB9310..CC8B50 (map)
	.section .rom.00CB9310, "a"
	.incbin "build/maps/nfp/MAP26_6A.KMP.bin"

@ ROM CCB8A0..CCD160 (map)
	.section .rom.00CCB8A0, "a"
	.incbin "build/maps/nfp/MAP27_A.KMP.bin"

@ ROM CCD160..D04D20 (map)
	.section .rom.00CCD160, "a"
	.incbin "build/maps/nfp/MAP40_A.KMP.bin"

@ ROM D05060..D11120 (map)
	.section .rom.00D05060, "a"
	.incbin "build/maps/nfp/MAP41_A.KMP.bin"

@ ROM D112B0..D49A70 (map)
	.section .rom.00D112B0, "a"
	.incbin "build/maps/nfp/MAP42_A.KMP.bin"

@ ROM D49D90..D4B650 (map)
	.section .rom.00D49D90, "a"
	.incbin "build/maps/nfp/MAP99_A.KMP.bin"

@ ROM D4D770..D4E030 (map)
	.section .rom.00D4D770, "a"
	.incbin "build/maps/nfp/ML_BG01.KMP.bin"

@ ROM D4E480..D4F540 (map)
	.section .rom.00D4E480, "a"
	.incbin "build/maps/nfp/MWA.KMP.bin"

@ ROM D5E800..D600C0 (map)
	.section .rom.00D5E800, "a"
	.incbin "build/maps/nfp/NET_00_A.KMP.bin"

@ ROM D600C0..D61980 (map)
	.section .rom.00D600C0, "a"
	.incbin "build/maps/nfp/NET_03_A.KMP.bin"

@ ROM D61980..D63240 (map)
	.section .rom.00D61980, "a"
	.incbin "build/maps/nfp/NET_04_A.KMP.bin"

@ ROM D63240..D64B00 (map)
	.section .rom.00D63240, "a"
	.incbin "build/maps/nfp/NET_05_A.KMP.bin"

@ ROM D64B00..D663C0 (map)
	.section .rom.00D64B00, "a"
	.incbin "build/maps/nfp/NET_07_A.KMP.bin"

@ ROM D663C0..D67C80 (map)
	.section .rom.00D663C0, "a"
	.incbin "build/maps/nfp/NET_24_A.KMP.bin"

@ ROM D67C80..D69540 (map)
	.section .rom.00D67C80, "a"
	.incbin "build/maps/nfp/NET_25_A.KMP.bin"

@ ROM D69540..D6AE00 (map)
	.section .rom.00D69540, "a"
	.incbin "build/maps/nfp/NET_26_A.KMP.bin"

@ ROM D6AE00..D6C6C0 (map)
	.section .rom.00D6AE00, "a"
	.incbin "build/maps/nfp/NET_AD_A.KMP.bin"

@ ROM D727D0..D736A0 (map)
	.section .rom.00D727D0, "a"
	.incbin "build/maps/nfp/OP_01_A.KMP.bin"

@ ROM D76ED0..D77DA0 (map)
	.section .rom.00D76ED0, "a"
	.incbin "build/maps/nfp/OP_04_A.KMP.bin"

@ ROM D7BDE0..D7CCB0 (map)
	.section .rom.00D7BDE0, "a"
	.incbin "build/maps/nfp/OP_05_A.KMP.bin"

@ ROM D80150..D81890 (map)
	.section .rom.00D80150, "a"
	.incbin "build/maps/nfp/OP_06_A.KMP.bin"

@ ROM D83DF0..D856B0 (map)
	.section .rom.00D83DF0, "a"
	.incbin "build/maps/nfp/OP_07_A.KMP.bin"

@ ROM D880A0..D89960 (map)
	.section .rom.00D880A0, "a"
	.incbin "build/maps/nfp/OP_08_A.KMP.bin"

@ ROM D8D1C0..D8EA80 (map)
	.section .rom.00D8D1C0, "a"
	.incbin "build/maps/nfp/OP_09_A.KMP.bin"

@ ROM D900E0..D919A0 (map)
	.section .rom.00D900E0, "a"
	.incbin "build/maps/nfp/OP_0A_A.KMP.bin"

@ ROM D952C0..D95B80 (map)
	.section .rom.00D952C0, "a"
	.incbin "build/maps/nfp/PS_BG01.KMP.bin"

@ ROM D979D0..D98290 (map)
	.section .rom.00D979D0, "a"
	.incbin "build/maps/nfp/PV_BG01.KMP.bin"

@ ROM D986F0..D98FB0 (map)
	.section .rom.00D986F0, "a"
	.incbin "build/maps/nfp/PV_BG11.KMP.bin"

@ ROM D9A5F0..D9AEB0 (map)
	.section .rom.00D9A5F0, "a"
	.incbin "build/maps/nfp/PW_BG01.KMP.bin"

@ ROM D9C240..D9CB00 (map)
	.section .rom.00D9C240, "a"
	.incbin "build/maps/nfp/PW_BOX.KMP.bin"

@ ROM DA80D0..DA8990 (map)
	.section .rom.00DA80D0, "a"
	.incbin "build/maps/nfp/SM_BG01.KMP.bin"

@ ROM DB57A0..DB6060 (map)
	.section .rom.00DB57A0, "a"
	.incbin "build/maps/nfp/SP_BG01.KMP.bin"

@ ROM DB89F0..DB92B0 (map)
	.section .rom.00DB89F0, "a"
	.incbin "build/maps/nfp/SP_BG11.KMP.bin"

@ ROM DB9D60..DBA620 (map)
	.section .rom.00DB9D60, "a"
	.incbin "build/maps/nfp/SP_BG12.KMP.bin"

@ ROM DBC980..DBD240 (map)
	.section .rom.00DBC980, "a"
	.incbin "build/maps/nfp/SP_BG21.KMP.bin"

@ ROM DBFA30..DC02F0 (map)
	.section .rom.00DBFA30, "a"
	.incbin "build/maps/nfp/SP_BG22.KMP.bin"

@ ROM DD03C0..DD0C80 (map)
	.section .rom.00DD03C0, "a"
	.incbin "build/maps/nfp/ST_BG01.KMP.bin"

@ ROM DD1D30..DD25F0 (map)
	.section .rom.00DD1D30, "a"
	.incbin "build/maps/nfp/ST_BG02.KMP.bin"

@ ROM DD3650..DD3F10 (map)
	.section .rom.00DD3650, "a"
	.incbin "build/maps/nfp/ST_BG03.KMP.bin"

@ ROM DD6120..DD69E0 (map)
	.section .rom.00DD6120, "a"
	.incbin "build/maps/nfp/ST_BG11.KMP.bin"

@ ROM F1B050..F1B910 (map)
	.section .rom.00F1B050, "a"
	.incbin "build/maps/nfp/T_C02.KMP.bin"

@ ROM F1E690..F1EF50 (map)
	.section .rom.00F1E690, "a"
	.incbin "build/maps/nfp/T_ML_BG.KMP.bin"

@ ROM F21CE0..F23E20 (map)
	.section .rom.00F21CE0, "a"
	.incbin "build/maps/nfp/VSMAP01.KMP.bin"

@ ROM F25C90..F26550 (map)
	.section .rom.00F25C90, "a"
	.incbin "build/maps/nfp/WM_BG01.KMP.bin"

@ ROM F27630..F27EF0 (map)
	.section .rom.00F27630, "a"
	.incbin "build/maps/nfp/WM_BG02.KMP.bin"
