@ Uniform alignment and erased-ROM regions.
@ Generated by tools/split.py; these bytes contain no assets.

	.section .rom.001CF7A1, "a"
	.fill 15, 1, 0x00

	.section .rom.0023BF12, "a"
	.fill 14, 1, 0x00

	.section .rom.002A8908, "a"
	.fill 8, 1, 0x00

	.section .rom.00313D8A, "a"
	.fill 6, 1, 0x00

	.section .rom.0037772F, "a"
	.fill 1, 1, 0x00

	.section .rom.00378951, "a"
	.fill 15, 1, 0x00

	.section .rom.0037B323, "a"
	.fill 13, 1, 0x00

	.section .rom.0037C692, "a"
	.fill 14, 1, 0x00

	.section .rom.0037F2B7, "a"
	.fill 9, 1, 0x00

	.section .rom.00380FB8, "a"
	.fill 8, 1, 0x00

	.section .rom.003835C5, "a"
	.fill 11, 1, 0x00

	.section .rom.00386CF4, "a"
	.fill 12, 1, 0x00

	.section .rom.0038AC5A, "a"
	.fill 6, 1, 0x00

	.section .rom.0038CEF4, "a"
	.fill 12, 1, 0x00

	.section .rom.0056E58E, "a"
	.fill 2, 1, 0x00

	.section .rom.00570763, "a"
	.fill 13, 1, 0x00

	.section .rom.00572165, "a"
	.fill 11, 1, 0x00

	.section .rom.005AA28A, "a"
	.fill 6, 1, 0x00

	.section .rom.005ABAA3, "a"
	.fill 13, 1, 0x00

	.section .rom.007CCDBA, "a"
	.fill 6, 1, 0x00

	.section .rom.007D611A, "a"
	.fill 6, 1, 0x00

	.section .rom.007DC77B, "a"
	.fill 5, 1, 0x00

	.section .rom.007E2814, "a"
	.fill 12, 1, 0x00

	.section .rom.007E76B2, "a"
	.fill 14, 1, 0x00

	.section .rom.007EAEB8, "a"
	.fill 8, 1, 0x00

	.section .rom.007F3B27, "a"
	.fill 9, 1, 0x00

	.section .rom.008161EF, "a"
	.fill 1, 1, 0x00

	.section .rom.00824A1E, "a"
	.fill 2, 1, 0x00

	.section .rom.0086C1B1, "a"
	.fill 15, 1, 0x00

	.section .rom.00875AC9, "a"
	.fill 7, 1, 0x00

	.section .rom.008989FC, "a"
	.fill 4, 1, 0x00

	.section .rom.008A4ACD, "a"
	.fill 3, 1, 0x00

	.section .rom.008DBD44, "a"
	.fill 12, 1, 0x00

	.section .rom.008E6275, "a"
	.fill 11, 1, 0x00

	.section .rom.008F24DD, "a"
	.fill 3, 1, 0x00

	.section .rom.0093F7F9, "a"
	.fill 7, 1, 0x00

	.section .rom.00951D8A, "a"
	.fill 6, 1, 0x00

	.section .rom.00961BA3, "a"
	.fill 13, 1, 0x00

	.section .rom.00969D9A, "a"
	.fill 6, 1, 0x00

	.section .rom.009859FF, "a"
	.fill 1, 1, 0x00

	.section .rom.0098E8F2, "a"
	.fill 14, 1, 0x00

	.section .rom.00997B0A, "a"
	.fill 6, 1, 0x00

	.section .rom.00A16AC5, "a"
	.fill 11, 1, 0x00

	.section .rom.00A22A31, "a"
	.fill 15, 1, 0x00

	.section .rom.00A376D2, "a"
	.fill 14, 1, 0x00

	.section .rom.00A4031F, "a"
	.fill 1, 1, 0x00

	.section .rom.00A4CCAC, "a"
	.fill 4, 1, 0x00

	.section .rom.00A58D45, "a"
	.fill 11, 1, 0x00

	.section .rom.00A74372, "a"
	.fill 14, 1, 0x00

	.section .rom.00AC888F, "a"
	.fill 1, 1, 0x00

	.section .rom.00AF05B8, "a"
	.fill 8, 1, 0x00

	.section .rom.00AF9C6C, "a"
	.fill 4, 1, 0x00

	.section .rom.00BCD519, "a"
	.fill 7, 1, 0x00

	.section .rom.00BDE717, "a"
	.fill 9, 1, 0x00

	.section .rom.00C0CDAF, "a"
	.fill 1, 1, 0x00

	.section .rom.00CCB832, "a"
	.fill 14, 1, 0x00

	.section .rom.00D49D66, "a"
	.fill 10, 1, 0x00

	.section .rom.00D4D74C, "a"
	.fill 4, 1, 0x00

	.section .rom.00D4E455, "a"
	.fill 11, 1, 0x00

	.section .rom.00D510B5, "a"
	.fill 11, 1, 0x00

	.section .rom.00D52B7B, "a"
	.fill 5, 1, 0x00

	.section .rom.00D55DA7, "a"
	.fill 9, 1, 0x00

	.section .rom.00D5E49B, "a"
	.fill 5, 1, 0x00

	.section .rom.00D72769, "a"
	.fill 7, 1, 0x00

	.section .rom.00D76E63, "a"
	.fill 13, 1, 0x00

	.section .rom.00D7BD73, "a"
	.fill 13, 1, 0x00

	.section .rom.00D80082, "a"
	.fill 14, 1, 0x00

	.section .rom.00D83CA2, "a"
	.fill 14, 1, 0x00

	.section .rom.00D87F5C, "a"
	.fill 4, 1, 0x00

	.section .rom.00D8D07A, "a"
	.fill 6, 1, 0x00

	.section .rom.00D8FF99, "a"
	.fill 7, 1, 0x00

	.section .rom.00D9529D, "a"
	.fill 3, 1, 0x00

	.section .rom.00D986CA, "a"
	.fill 6, 1, 0x00

	.section .rom.00D9A5C4, "a"
	.fill 12, 1, 0x00

	.section .rom.00D9C217, "a"
	.fill 9, 1, 0x00

	.section .rom.00D9F944, "a"
	.fill 12, 1, 0x00

	.section .rom.00DA3577, "a"
	.fill 9, 1, 0x00

	.section .rom.00DA4BE7, "a"
	.fill 9, 1, 0x00

	.section .rom.00DA80AC, "a"
	.fill 4, 1, 0x00

	.section .rom.00DA9BC4, "a"
	.fill 12, 1, 0x00

	.section .rom.00DAB3D4, "a"
	.fill 12, 1, 0x00

	.section .rom.00DAE9E3, "a"
	.fill 13, 1, 0x00

	.section .rom.00DB5778, "a"
	.fill 8, 1, 0x00

	.section .rom.00DB89C9, "a"
	.fill 7, 1, 0x00

	.section .rom.00DB9D37, "a"
	.fill 9, 1, 0x00

	.section .rom.00DBC95D, "a"
	.fill 3, 1, 0x00

	.section .rom.00DBFA01, "a"
	.fill 15, 1, 0x00

	.section .rom.00DCAFB3, "a"
	.fill 13, 1, 0x00

	.section .rom.00DD0394, "a"
	.fill 12, 1, 0x00

	.section .rom.00DD3624, "a"
	.fill 12, 1, 0x00

	.section .rom.00DD60F6, "a"
	.fill 10, 1, 0x00

	.section .rom.00F1A2FB, "a"
	.fill 5, 1, 0x00

	.section .rom.00F1B027, "a"
	.fill 9, 1, 0x00

	.section .rom.00F1E649, "a"
	.fill 7, 1, 0x00

	.section .rom.00F21395, "a"
	.fill 11, 1, 0x00

	.section .rom.00F27607, "a"
	.fill 9, 1, 0x00

	.section .rom.00F2B448, "a"
	.fill 262144, 1, 0xFF

	.section .rom.00F6B448, "a"
	.fill 262144, 1, 0xFF

	.section .rom.00FAB448, "a"
	.fill 215992, 1, 0xFF

	.section .rom.00FE4000, "a"
	.fill 29768, 1, 0xFF

	.section .rom.00FEB448, "a"
	.fill 80824, 1, 0xFF

	.section .rom.00FFFF00, "a"
	.fill 256, 1, 0xFF
