@ raw data ROM sections.
@ Generated by tools/split.py; section names preserve ROM order.

@ ROM 1B02A4..1B096C (raw)
@ Source: data/data_1B02A4.bin, with text/ applied by tools/build_text.py
	.section .rom.001B02A4, "a"
	.incbin "build/data/data_1B02A4.bin"

@ ROM 1BEC3C..1BF408 (raw)
@ Source: data/data_1BEC3C.bin, with text/ applied by tools/build_text.py
	.section .rom.001BEC3C, "a"
	.incbin "build/data/data_1BEC3C.bin"

@ ROM FE0000..FE4000 (raw)
@ Source: data/data_FE0000.bin, with text/ applied by tools/build_text.py
	.section .rom.00FE0000, "a"
	.incbin "build/data/data_FE0000.bin"

@ ROM FFF000..FFFF00 (raw)
@ Source: data/data_FFF000.bin, with text/ applied by tools/build_text.py
	.section .rom.00FFF000, "a"
	.incbin "build/data/data_FFF000.bin"
