@ script assets ROM sections.
@ Generated by tools/split.py; section names preserve ROM order.

@ ROM 38D760..38E8D0 (script)
	.section .rom.0038D760, "a"
	.incbin "build/scripts/nfp/BGM_SET.SPC.bin"

@ ROM 38E8D0..38ECB0 (script)
	.section .rom.0038E8D0, "a"
	.incbin "build/scripts/nfp/BTIM00.SPC.bin"

@ ROM 38ECB0..38F050 (script)
	.section .rom.0038ECB0, "a"
	.incbin "build/scripts/nfp/BTIM01_3.SPC.bin"

@ ROM 38F050..38F0E0 (script)
	.section .rom.0038F050, "a"
	.incbin "build/scripts/nfp/BTIM03.SPC.bin"

@ ROM 38F0E0..38FFA0 (script)
	.section .rom.0038F0E0, "a"
	.incbin "build/scripts/nfp/BTIM04.SPC.bin"

@ ROM 38FFA0..390630 (script)
	.section .rom.0038FFA0, "a"
	.incbin "build/scripts/nfp/BTIM04_4.SPC.bin"

@ ROM 390630..390930 (script)
	.section .rom.00390630, "a"
	.incbin "build/scripts/nfp/BTIM05.SPC.bin"

@ ROM 390930..391C50 (script)
	.section .rom.00390930, "a"
	.incbin "build/scripts/nfp/BTIM07.SPC.bin"

@ ROM 391C50..3926A0 (script)
	.section .rom.00391C50, "a"
	.incbin "build/scripts/nfp/BTIM24_1.SPC.bin"

@ ROM 3926A0..392F90 (script)
	.section .rom.003926A0, "a"
	.incbin "build/scripts/nfp/BTIM24_2.SPC.bin"

@ ROM 392F90..393820 (script)
	.section .rom.00392F90, "a"
	.incbin "build/scripts/nfp/BTIM24_4.SPC.bin"

@ ROM 393820..3946F0 (script)
	.section .rom.00393820, "a"
	.incbin "build/scripts/nfp/BTIM25_1.SPC.bin"

@ ROM 3946F0..395070 (script)
	.section .rom.003946F0, "a"
	.incbin "build/scripts/nfp/BTIM25_2.SPC.bin"

@ ROM 395070..396870 (script)
	.section .rom.00395070, "a"
	.incbin "build/scripts/nfp/BTIM25_4.SPC.bin"

@ ROM 396870..3972D0 (script)
	.section .rom.00396870, "a"
	.incbin "build/scripts/nfp/BTIM26_1.SPC.bin"

@ ROM 3972D0..398110 (script)
	.section .rom.003972D0, "a"
	.incbin "build/scripts/nfp/BTIM26_3.SPC.bin"

@ ROM 398110..399F10 (script)
	.section .rom.00398110, "a"
	.incbin "build/scripts/nfp/BTIM26_5.SPC.bin"

@ ROM 399F10..39A2F0 (script)
	.section .rom.00399F10, "a"
	.incbin "build/scripts/nfp/BTIM40.SPC.bin"

@ ROM 39A2F0..39A6B0 (script)
	.section .rom.0039A2F0, "a"
	.incbin "build/scripts/nfp/BTIM41.SPC.bin"

@ ROM 39A6B0..39AF50 (script)
	.section .rom.0039A6B0, "a"
	.incbin "build/scripts/nfp/BTIM42.SPC.bin"

@ ROM 39AF50..39B390 (script)
	.section .rom.0039AF50, "a"
	.incbin "build/scripts/nfp/BTI_DUNG.SPC.bin"

@ ROM 39B390..39C170 (script)
	.section .rom.0039B390, "a"
	.incbin "build/scripts/nfp/BTI_N.SPC.bin"

@ ROM 39C170..39C7A0 (script)
	.section .rom.0039C170, "a"
	.incbin "build/scripts/nfp/BTI_PSET.SPC.bin"

@ ROM 39C7A0..39CD30 (script)
	.section .rom.0039C7A0, "a"
	.incbin "build/scripts/nfp/BTL_ESCP.SPC.bin"

@ ROM 39CD30..39CD90 (script)
	.section .rom.0039CD30, "a"
	.incbin "build/scripts/nfp/BTOM00.SPC.bin"

@ ROM 39CD90..39CF30 (script)
	.section .rom.0039CD90, "a"
	.incbin "build/scripts/nfp/BTOM01_3.SPC.bin"

@ ROM 39CF30..39D060 (script)
	.section .rom.0039CF30, "a"
	.incbin "build/scripts/nfp/BTOM03.SPC.bin"

@ ROM 39D060..39D0C0 (script)
	.section .rom.0039D060, "a"
	.incbin "build/scripts/nfp/BTOM04.SPC.bin"

@ ROM 39D0C0..39D120 (script)
	.section .rom.0039D0C0, "a"
	.incbin "build/scripts/nfp/BTOM04_4.SPC.bin"

@ ROM 39D120..39D250 (script)
	.section .rom.0039D120, "a"
	.incbin "build/scripts/nfp/BTOM04_6.SPC.bin"

@ ROM 39D250..39D420 (script)
	.section .rom.0039D250, "a"
	.incbin "build/scripts/nfp/BTOM05.SPC.bin"

@ ROM 39D420..39D600 (script)
	.section .rom.0039D420, "a"
	.incbin "build/scripts/nfp/BTOM07.SPC.bin"

@ ROM 39D600..39D6A0 (script)
	.section .rom.0039D600, "a"
	.incbin "build/scripts/nfp/BTOM07_3.SPC.bin"

@ ROM 39D6A0..39D700 (script)
	.section .rom.0039D6A0, "a"
	.incbin "build/scripts/nfp/BTOM24_1.SPC.bin"

@ ROM 39D700..39D760 (script)
	.section .rom.0039D700, "a"
	.incbin "build/scripts/nfp/BTOM24_2.SPC.bin"

@ ROM 39D760..39D890 (script)
	.section .rom.0039D760, "a"
	.incbin "build/scripts/nfp/BTOM24_4.SPC.bin"

@ ROM 39D890..39D8F0 (script)
	.section .rom.0039D890, "a"
	.incbin "build/scripts/nfp/BTOM25_1.SPC.bin"

@ ROM 39D8F0..39D950 (script)
	.section .rom.0039D8F0, "a"
	.incbin "build/scripts/nfp/BTOM25_2.SPC.bin"

@ ROM 39D950..39D9B0 (script)
	.section .rom.0039D950, "a"
	.incbin "build/scripts/nfp/BTOM25_4.SPC.bin"

@ ROM 39D9B0..39DA50 (script)
	.section .rom.0039D9B0, "a"
	.incbin "build/scripts/nfp/BTOM25_5.SPC.bin"

@ ROM 39DA50..39DAB0 (script)
	.section .rom.0039DA50, "a"
	.incbin "build/scripts/nfp/BTOM26_1.SPC.bin"

@ ROM 39DAB0..39DB50 (script)
	.section .rom.0039DAB0, "a"
	.incbin "build/scripts/nfp/BTOM26_2.SPC.bin"

@ ROM 39DB50..39DBB0 (script)
	.section .rom.0039DB50, "a"
	.incbin "build/scripts/nfp/BTOM26_3.SPC.bin"

@ ROM 39DBB0..39DC10 (script)
	.section .rom.0039DBB0, "a"
	.incbin "build/scripts/nfp/BTOM26_5.SPC.bin"

@ ROM 39DC10..39DC70 (script)
	.section .rom.0039DC10, "a"
	.incbin "build/scripts/nfp/BTOM26_6.SPC.bin"

@ ROM 39DC70..39DD70 (script)
	.section .rom.0039DC70, "a"
	.incbin "build/scripts/nfp/BTOM40.SPC.bin"

@ ROM 39DD70..39DDD0 (script)
	.section .rom.0039DD70, "a"
	.incbin "build/scripts/nfp/BTOM41.SPC.bin"

@ ROM 39DDD0..39DED0 (script)
	.section .rom.0039DDD0, "a"
	.incbin "build/scripts/nfp/BTOM42.SPC.bin"

@ ROM 39DED0..39E690 (script)
	.section .rom.0039DED0, "a"
	.incbin "build/scripts/nfp/BTO_DEF.SPC.bin"

@ ROM 39E690..39EAF0 (script)
	.section .rom.0039E690, "a"
	.incbin "build/scripts/nfp/BTO_DEF2.SPC.bin"

@ ROM 39EAF0..39F3B0 (script)
	.section .rom.0039EAF0, "a"
	.incbin "build/scripts/nfp/BTO_DUNG.SPC.bin"

@ ROM 39F3B0..39FFD0 (script)
	.section .rom.0039F3B0, "a"
	.incbin "build/scripts/nfp/BTO_N.SPC.bin"

@ ROM 5683C0..569C00 (script)
	.section .rom.005683C0, "a"
	.incbin "build/scripts/nfp/CH_ESC.SPC.bin"

@ ROM 569C00..569F30 (script)
	.section .rom.00569C00, "a"
	.incbin "build/scripts/nfp/CH_M00A.SPC.bin"

@ ROM 569F30..56A220 (script)
	.section .rom.00569F30, "a"
	.incbin "build/scripts/nfp/CH_M01_3.SPC.bin"

@ ROM 56A220..56A280 (script)
	.section .rom.0056A220, "a"
	.incbin "build/scripts/nfp/CH_M03A.SPC.bin"

@ ROM 56A280..56A600 (script)
	.section .rom.0056A280, "a"
	.incbin "build/scripts/nfp/CH_M05A.SPC.bin"

@ ROM 56A600..56A8B0 (script)
	.section .rom.0056A600, "a"
	.incbin "build/scripts/nfp/CH_M08A.SPC.bin"

@ ROM 56A8B0..56B610 (script)
	.section .rom.0056A8B0, "a"
	.incbin "build/scripts/nfp/CH_M09A.SPC.bin"

@ ROM 56B610..56B6D0 (script)
	.section .rom.0056B610, "a"
	.incbin "build/scripts/nfp/CH_M10.SPC.bin"

@ ROM 56B6D0..56BED0 (script)
	.section .rom.0056B6D0, "a"
	.incbin "build/scripts/nfp/CH_M11.SPC.bin"

@ ROM 56BED0..56BFA0 (script)
	.section .rom.0056BED0, "a"
	.incbin "build/scripts/nfp/CH_M24_3.SPC.bin"

@ ROM 56BFA0..56C3F0 (script)
	.section .rom.0056BFA0, "a"
	.incbin "build/scripts/nfp/CH_M24_A.SPC.bin"

@ ROM 56C3F0..56DB30 (script)
	.section .rom.0056C3F0, "a"
	.incbin "build/scripts/nfp/CH_M26_6.SPC.bin"

@ ROM 572A50..573300 (script)
	.section .rom.00572A50, "a"
	.incbin "build/scripts/nfp/D0_BOSS.SPC.bin"

@ ROM 573300..5744D0 (script)
	.section .rom.00573300, "a"
	.incbin "build/scripts/nfp/D0_ENEMY.SPC.bin"

@ ROM 5744D0..575070 (script)
	.section .rom.005744D0, "a"
	.incbin "build/scripts/nfp/D0_ITEM.SPC.bin"

@ ROM 575070..5756C0 (script)
	.section .rom.00575070, "a"
	.incbin "build/scripts/nfp/D0_MAKE.SPC.bin"

@ ROM 5756C0..575950 (script)
	.section .rom.005756C0, "a"
	.incbin "build/scripts/nfp/D0_NORM.SPC.bin"

@ ROM 575950..5761B0 (script)
	.section .rom.00575950, "a"
	.incbin "build/scripts/nfp/D1_BOSS.SPC.bin"

@ ROM 5761B0..5783A0 (script)
	.section .rom.005761B0, "a"
	.incbin "build/scripts/nfp/D1_ENEMY.SPC.bin"

@ ROM 5783A0..579FF0 (script)
	.section .rom.005783A0, "a"
	.incbin "build/scripts/nfp/D1_ITEM.SPC.bin"

@ ROM 579FF0..57AA40 (script)
	.section .rom.00579FF0, "a"
	.incbin "build/scripts/nfp/D1_MAKE.SPC.bin"

@ ROM 57AA40..57B2A0 (script)
	.section .rom.0057AA40, "a"
	.incbin "build/scripts/nfp/D2_BOSS.SPC.bin"

@ ROM 57B2A0..57E690 (script)
	.section .rom.0057B2A0, "a"
	.incbin "build/scripts/nfp/D2_ENEMY.SPC.bin"

@ ROM 57E690..582B20 (script)
	.section .rom.0057E690, "a"
	.incbin "build/scripts/nfp/D2_ITEM.SPC.bin"

@ ROM 582B20..583970 (script)
	.section .rom.00582B20, "a"
	.incbin "build/scripts/nfp/D2_MAKE.SPC.bin"

@ ROM 583970..5841D0 (script)
	.section .rom.00583970, "a"
	.incbin "build/scripts/nfp/D3_BOSS.SPC.bin"

@ ROM 5841D0..588620 (script)
	.section .rom.005841D0, "a"
	.incbin "build/scripts/nfp/D3_ENEMY.SPC.bin"

@ ROM 588620..58DAE0 (script)
	.section .rom.00588620, "a"
	.incbin "build/scripts/nfp/D3_ITEM.SPC.bin"

@ ROM 58DAE0..58ED30 (script)
	.section .rom.0058DAE0, "a"
	.incbin "build/scripts/nfp/D3_MAKE.SPC.bin"

@ ROM 58ED30..58F590 (script)
	.section .rom.0058ED30, "a"
	.incbin "build/scripts/nfp/D4_BOSS.SPC.bin"

@ ROM 58F590..594A70 (script)
	.section .rom.0058F590, "a"
	.incbin "build/scripts/nfp/D4_ENEMY.SPC.bin"

@ ROM 594A70..59A3B0 (script)
	.section .rom.00594A70, "a"
	.incbin "build/scripts/nfp/D4_ITEM.SPC.bin"

@ ROM 59A3B0..59BAF0 (script)
	.section .rom.0059A3B0, "a"
	.incbin "build/scripts/nfp/D4_MAKE.SPC.bin"

@ ROM 59BAF0..59BE70 (script)
	.section .rom.0059BAF0, "a"
	.incbin "build/scripts/nfp/DBG_BTL.SPC.bin"

@ ROM 59BE70..59D2D0 (script)
	.section .rom.0059BE70, "a"
	.incbin "build/scripts/nfp/DBG_BTLQ.SPC.bin"

@ ROM 59D2D0..59E020 (script)
	.section .rom.0059D2D0, "a"
	.incbin "build/scripts/nfp/DBG_ESC.SPC.bin"

@ ROM 59E020..5A62B0 (script)
	.section .rom.0059E020, "a"
	.incbin "build/scripts/nfp/DBG_FACE.SPC.bin"

@ ROM 5A62B0..5A6FA0 (script)
	.section .rom.005A62B0, "a"
	.incbin "build/scripts/nfp/DITEMCOM.SPC.bin"

@ ROM 5AC390..5AC9A0 (script)
	.section .rom.005AC390, "a"
	.incbin "build/scripts/nfp/DUNG_DEF.SPC.bin"

@ ROM 5AC9A0..5AD530 (script)
	.section .rom.005AC9A0, "a"
	.incbin "build/scripts/nfp/DUNG_END.SPC.bin"

@ ROM 5AD530..5AE230 (script)
	.section .rom.005AD530, "a"
	.incbin "build/scripts/nfp/D_VS_R.SPC.bin"

@ ROM 791060..793140 (script)
	.section .rom.00791060, "a"
	.incbin "build/scripts/nfp/END2.SPC.bin"

@ ROM 793140..7952D0 (script)
	.section .rom.00793140, "a"
	.incbin "build/scripts/nfp/ENE_SET.SPC.bin"

@ ROM 7952D0..796110 (script)
	.section .rom.007952D0, "a"
	.incbin "build/scripts/nfp/EV_AL01.SPC.bin"

@ ROM 796110..796E90 (script)
	.section .rom.00796110, "a"
	.incbin "build/scripts/nfp/EV_AL02.SPC.bin"

@ ROM 796E90..7983F0 (script)
	.section .rom.00796E90, "a"
	.incbin "build/scripts/nfp/EV_AL02B.SPC.bin"

@ ROM 7983F0..7992B0 (script)
	.section .rom.007983F0, "a"
	.incbin "build/scripts/nfp/EV_AL03.SPC.bin"

@ ROM 7992B0..799570 (script)
	.section .rom.007992B0, "a"
	.incbin "build/scripts/nfp/EV_AL04.SPC.bin"

@ ROM 799570..79A490 (script)
	.section .rom.00799570, "a"
	.incbin "build/scripts/nfp/EV_BA01.SPC.bin"

@ ROM 79A490..79ACF0 (script)
	.section .rom.0079A490, "a"
	.incbin "build/scripts/nfp/EV_BA02.SPC.bin"

@ ROM 79ACF0..79B340 (script)
	.section .rom.0079ACF0, "a"
	.incbin "build/scripts/nfp/EV_BA03.SPC.bin"

@ ROM 79B340..79BB10 (script)
	.section .rom.0079B340, "a"
	.incbin "build/scripts/nfp/EV_BA04.SPC.bin"

@ ROM 79BB10..79BF50 (script)
	.section .rom.0079BB10, "a"
	.incbin "build/scripts/nfp/EV_BIN01.SPC.bin"

@ ROM 79BF50..79C3B0 (script)
	.section .rom.0079BF50, "a"
	.incbin "build/scripts/nfp/EV_BIN02.SPC.bin"

@ ROM 79C3B0..79C870 (script)
	.section .rom.0079C3B0, "a"
	.incbin "build/scripts/nfp/EV_BIN03.SPC.bin"

@ ROM 79C870..79D720 (script)
	.section .rom.0079C870, "a"
	.incbin "build/scripts/nfp/EV_EDO01.SPC.bin"

@ ROM 79D720..79E2E0 (script)
	.section .rom.0079D720, "a"
	.incbin "build/scripts/nfp/EV_GO01.SPC.bin"

@ ROM 79E2E0..79EB60 (script)
	.section .rom.0079E2E0, "a"
	.incbin "build/scripts/nfp/EV_GO02.SPC.bin"

@ ROM 79EB60..79EFA0 (script)
	.section .rom.0079EB60, "a"
	.incbin "build/scripts/nfp/EV_GO03.SPC.bin"

@ ROM 79EFA0..79FA20 (script)
	.section .rom.0079EFA0, "a"
	.incbin "build/scripts/nfp/EV_GO04.SPC.bin"

@ ROM 79FA20..7A01E0 (script)
	.section .rom.0079FA20, "a"
	.incbin "build/scripts/nfp/EV_GO05.SPC.bin"

@ ROM 7A01E0..7A0780 (script)
	.section .rom.007A01E0, "a"
	.incbin "build/scripts/nfp/EV_GO06.SPC.bin"

@ ROM 7A0780..7A0DB0 (script)
	.section .rom.007A0780, "a"
	.incbin "build/scripts/nfp/EV_GO07.SPC.bin"

@ ROM 7A0DB0..7A1170 (script)
	.section .rom.007A0DB0, "a"
	.incbin "build/scripts/nfp/EV_GO08.SPC.bin"

@ ROM 7A1170..7A1BF0 (script)
	.section .rom.007A1170, "a"
	.incbin "build/scripts/nfp/EV_GO09.SPC.bin"

@ ROM 7A1BF0..7A2280 (script)
	.section .rom.007A1BF0, "a"
	.incbin "build/scripts/nfp/EV_GO10.SPC.bin"

@ ROM 7A2280..7A32E0 (script)
	.section .rom.007A2280, "a"
	.incbin "build/scripts/nfp/EV_GO11.SPC.bin"

@ ROM 7A32E0..7A3AE0 (script)
	.section .rom.007A32E0, "a"
	.incbin "build/scripts/nfp/EV_GO12.SPC.bin"

@ ROM 7A3AE0..7A43F0 (script)
	.section .rom.007A3AE0, "a"
	.incbin "build/scripts/nfp/EV_GTOB.SPC.bin"

@ ROM 7A43F0..7A4880 (script)
	.section .rom.007A43F0, "a"
	.incbin "build/scripts/nfp/EV_GTOB2.SPC.bin"

@ ROM 7A4880..7A5270 (script)
	.section .rom.007A4880, "a"
	.incbin "build/scripts/nfp/EV_ICE01.SPC.bin"

@ ROM 7A5270..7A6020 (script)
	.section .rom.007A5270, "a"
	.incbin "build/scripts/nfp/EV_ICE02.SPC.bin"

@ ROM 7A6020..7A6550 (script)
	.section .rom.007A6020, "a"
	.incbin "build/scripts/nfp/EV_ICE03.SPC.bin"

@ ROM 7A6550..7A6870 (script)
	.section .rom.007A6550, "a"
	.incbin "build/scripts/nfp/EV_ICE04.SPC.bin"

@ ROM 7A6870..7A6AE0 (script)
	.section .rom.007A6870, "a"
	.incbin "build/scripts/nfp/EV_ICE05.SPC.bin"

@ ROM 7A6AE0..7A6D10 (script)
	.section .rom.007A6AE0, "a"
	.incbin "build/scripts/nfp/EV_ICE06.SPC.bin"

@ ROM 7A6D10..7A7520 (script)
	.section .rom.007A6D10, "a"
	.incbin "build/scripts/nfp/EV_ICE07.SPC.bin"

@ ROM 7A7520..7A77B0 (script)
	.section .rom.007A7520, "a"
	.incbin "build/scripts/nfp/EV_ICE08.SPC.bin"

@ ROM 7A77B0..7A8C20 (script)
	.section .rom.007A77B0, "a"
	.incbin "build/scripts/nfp/EV_ICE09.SPC.bin"

@ ROM 7A8C20..7A9B40 (script)
	.section .rom.007A8C20, "a"
	.incbin "build/scripts/nfp/EV_ICE10.SPC.bin"

@ ROM 7A9B40..7AA9B0 (script)
	.section .rom.007A9B40, "a"
	.incbin "build/scripts/nfp/EV_ICE11.SPC.bin"

@ ROM 7AA9B0..7AC390 (script)
	.section .rom.007AA9B0, "a"
	.incbin "build/scripts/nfp/EV_ICE12.SPC.bin"

@ ROM 7AC390..7AC750 (script)
	.section .rom.007AC390, "a"
	.incbin "build/scripts/nfp/EV_IWA.SPC.bin"

@ ROM 7AC750..7ADD20 (script)
	.section .rom.007AC750, "a"
	.incbin "build/scripts/nfp/EV_JA01.SPC.bin"

@ ROM 7ADD20..7AE570 (script)
	.section .rom.007ADD20, "a"
	.incbin "build/scripts/nfp/EV_JA02.SPC.bin"

@ ROM 7AE570..7AF030 (script)
	.section .rom.007AE570, "a"
	.incbin "build/scripts/nfp/EV_JA03.SPC.bin"

@ ROM 7AF030..7AFA20 (script)
	.section .rom.007AF030, "a"
	.incbin "build/scripts/nfp/EV_JA04.SPC.bin"

@ ROM 7AFA20..7B05E0 (script)
	.section .rom.007AFA20, "a"
	.incbin "build/scripts/nfp/EV_JA04B.SPC.bin"

@ ROM 7B05E0..7B0990 (script)
	.section .rom.007B05E0, "a"
	.incbin "build/scripts/nfp/EV_JA04C.SPC.bin"

@ ROM 7B0990..7B1000 (script)
	.section .rom.007B0990, "a"
	.incbin "build/scripts/nfp/EV_MON01.SPC.bin"

@ ROM 7B1000..7B16B0 (script)
	.section .rom.007B1000, "a"
	.incbin "build/scripts/nfp/EV_MON02.SPC.bin"

@ ROM 7B16B0..7B19E0 (script)
	.section .rom.007B16B0, "a"
	.incbin "build/scripts/nfp/EV_MON03.SPC.bin"

@ ROM 7B19E0..7B1E60 (script)
	.section .rom.007B19E0, "a"
	.incbin "build/scripts/nfp/EV_MON04.SPC.bin"

@ ROM 7B1E60..7B20C0 (script)
	.section .rom.007B1E60, "a"
	.incbin "build/scripts/nfp/EV_MON05.SPC.bin"

@ ROM 7B20C0..7B2370 (script)
	.section .rom.007B20C0, "a"
	.incbin "build/scripts/nfp/EV_MON06.SPC.bin"

@ ROM 7B2370..7B2970 (script)
	.section .rom.007B2370, "a"
	.incbin "build/scripts/nfp/EV_PA01.SPC.bin"

@ ROM 7B2970..7B2E20 (script)
	.section .rom.007B2970, "a"
	.incbin "build/scripts/nfp/EV_RT01.SPC.bin"

@ ROM 7B2E20..7B36D0 (script)
	.section .rom.007B2E20, "a"
	.incbin "build/scripts/nfp/EV_RT02.SPC.bin"

@ ROM 7B36D0..7B43A0 (script)
	.section .rom.007B36D0, "a"
	.incbin "build/scripts/nfp/EV_RT03.SPC.bin"

@ ROM 7B43A0..7B4A40 (script)
	.section .rom.007B43A0, "a"
	.incbin "build/scripts/nfp/EV_START.SPC.bin"

@ ROM 7B4A40..7B52B0 (script)
	.section .rom.007B4A40, "a"
	.incbin "build/scripts/nfp/EV_T1KIL.SPC.bin"

@ ROM 7B52B0..7B5D50 (script)
	.section .rom.007B52B0, "a"
	.incbin "build/scripts/nfp/EV_T2KIL.SPC.bin"

@ ROM 7B5D50..7B7680 (script)
	.section .rom.007B5D50, "a"
	.incbin "build/scripts/nfp/EV_T3KIL.SPC.bin"

@ ROM 7B7680..7B8820 (script)
	.section .rom.007B7680, "a"
	.incbin "build/scripts/nfp/EV_T4KIL.SPC.bin"

@ ROM 7B8820..7B96A0 (script)
	.section .rom.007B8820, "a"
	.incbin "build/scripts/nfp/EV_UTA01.SPC.bin"

@ ROM 7B96A0..7B9C80 (script)
	.section .rom.007B96A0, "a"
	.incbin "build/scripts/nfp/EV_VE01.SPC.bin"

@ ROM 7B9C80..7BA990 (script)
	.section .rom.007B9C80, "a"
	.incbin "build/scripts/nfp/EV_VE02.SPC.bin"

@ ROM 7CA370..7CA760 (script)
	.section .rom.007CA370, "a"
	.incbin "build/scripts/nfp/FULL_ITM.SPC.bin"

@ ROM 7F4410..7F4500 (script)
	.section .rom.007F4410, "a"
	.incbin "build/scripts/nfp/GMAP27_A.SPC.bin"

@ ROM 7F4500..7F4A20 (script)
	.section .rom.007F4500, "a"
	.incbin "build/scripts/nfp/G_EV001.SPC.bin"

@ ROM 7F4A20..7F4E00 (script)
	.section .rom.007F4A20, "a"
	.incbin "build/scripts/nfp/G_EV002.SPC.bin"

@ ROM 7F4E00..7F5F20 (script)
	.section .rom.007F4E00, "a"
	.incbin "build/scripts/nfp/G_EV003.SPC.bin"

@ ROM 7F5F20..7F60D0 (script)
	.section .rom.007F5F20, "a"
	.incbin "build/scripts/nfp/G_EV004.SPC.bin"

@ ROM 7F60D0..7F6E20 (script)
	.section .rom.007F60D0, "a"
	.incbin "build/scripts/nfp/G_EV005.SPC.bin"

@ ROM 7F6E20..7F79A0 (script)
	.section .rom.007F6E20, "a"
	.incbin "build/scripts/nfp/G_EV006.SPC.bin"

@ ROM 7F79A0..7F8230 (script)
	.section .rom.007F79A0, "a"
	.incbin "build/scripts/nfp/G_EV007.SPC.bin"

@ ROM 7F8230..7F85E0 (script)
	.section .rom.007F8230, "a"
	.incbin "build/scripts/nfp/G_EV010.SPC.bin"

@ ROM 7F85E0..7F9730 (script)
	.section .rom.007F85E0, "a"
	.incbin "build/scripts/nfp/G_EV011.SPC.bin"

@ ROM 7F9730..7F9E60 (script)
	.section .rom.007F9730, "a"
	.incbin "build/scripts/nfp/G_EV011B.SPC.bin"

@ ROM 7F9E60..7FA990 (script)
	.section .rom.007F9E60, "a"
	.incbin "build/scripts/nfp/G_EV011C.SPC.bin"

@ ROM 7FA990..7FB040 (script)
	.section .rom.007FA990, "a"
	.incbin "build/scripts/nfp/G_EV012.SPC.bin"

@ ROM 7FB040..7FB650 (script)
	.section .rom.007FB040, "a"
	.incbin "build/scripts/nfp/G_EV013.SPC.bin"

@ ROM 7FB650..7FC900 (script)
	.section .rom.007FB650, "a"
	.incbin "build/scripts/nfp/G_EV020.SPC.bin"

@ ROM 7FC900..7FDB00 (script)
	.section .rom.007FC900, "a"
	.incbin "build/scripts/nfp/G_EV020B.SPC.bin"

@ ROM 7FDB00..7FE4B0 (script)
	.section .rom.007FDB00, "a"
	.incbin "build/scripts/nfp/G_EV020C.SPC.bin"

@ ROM 7FE4B0..7FF440 (script)
	.section .rom.007FE4B0, "a"
	.incbin "build/scripts/nfp/G_EV021.SPC.bin"

@ ROM 7FF440..7FF470 (script)
	.section .rom.007FF440, "a"
	.incbin "build/scripts/nfp/G_EV022.SPC.bin"

@ ROM 7FF470..800690 (script)
	.section .rom.007FF470, "a"
	.incbin "build/scripts/nfp/G_EV023.SPC.bin"

@ ROM 800690..800870 (script)
	.section .rom.00800690, "a"
	.incbin "build/scripts/nfp/G_EV023B.SPC.bin"

@ ROM 800870..8011A0 (script)
	.section .rom.00800870, "a"
	.incbin "build/scripts/nfp/G_EV023C.SPC.bin"

@ ROM 8011A0..802080 (script)
	.section .rom.008011A0, "a"
	.incbin "build/scripts/nfp/G_EV024.SPC.bin"

@ ROM 802080..802AF0 (script)
	.section .rom.00802080, "a"
	.incbin "build/scripts/nfp/G_EV025.SPC.bin"

@ ROM 802AF0..803E00 (script)
	.section .rom.00802AF0, "a"
	.incbin "build/scripts/nfp/G_EV025B.SPC.bin"

@ ROM 803E00..804A40 (script)
	.section .rom.00803E00, "a"
	.incbin "build/scripts/nfp/G_EV030.SPC.bin"

@ ROM 804A40..8051C0 (script)
	.section .rom.00804A40, "a"
	.incbin "build/scripts/nfp/G_EV031.SPC.bin"

@ ROM 8051C0..8051F0 (script)
	.section .rom.008051C0, "a"
	.incbin "build/scripts/nfp/G_EV032.SPC.bin"

@ ROM 8051F0..805970 (script)
	.section .rom.008051F0, "a"
	.incbin "build/scripts/nfp/G_EV040.SPC.bin"

@ ROM 805970..8060F0 (script)
	.section .rom.00805970, "a"
	.incbin "build/scripts/nfp/G_EV041.SPC.bin"

@ ROM 8060F0..8069A0 (script)
	.section .rom.008060F0, "a"
	.incbin "build/scripts/nfp/G_EV042.SPC.bin"

@ ROM 8069A0..807130 (script)
	.section .rom.008069A0, "a"
	.incbin "build/scripts/nfp/G_EV043.SPC.bin"

@ ROM 807130..807780 (script)
	.section .rom.00807130, "a"
	.incbin "build/scripts/nfp/G_EV044.SPC.bin"

@ ROM 807780..8088C0 (script)
	.section .rom.00807780, "a"
	.incbin "build/scripts/nfp/G_EV050.SPC.bin"

@ ROM 8088C0..8095E0 (script)
	.section .rom.008088C0, "a"
	.incbin "build/scripts/nfp/G_EV051.SPC.bin"

@ ROM 8095E0..809980 (script)
	.section .rom.008095E0, "a"
	.incbin "build/scripts/nfp/G_EV052.SPC.bin"

@ ROM 809980..80A2F0 (script)
	.section .rom.00809980, "a"
	.incbin "build/scripts/nfp/G_EV060.SPC.bin"

@ ROM 80A2F0..80B2D0 (script)
	.section .rom.0080A2F0, "a"
	.incbin "build/scripts/nfp/G_EV061.SPC.bin"

@ ROM 80B2D0..80D170 (script)
	.section .rom.0080B2D0, "a"
	.incbin "build/scripts/nfp/G_EV062.SPC.bin"

@ ROM 80D170..80D650 (script)
	.section .rom.0080D170, "a"
	.incbin "build/scripts/nfp/G_EV063.SPC.bin"

@ ROM 80D650..80D8F0 (script)
	.section .rom.0080D650, "a"
	.incbin "build/scripts/nfp/G_VS_R.SPC.bin"

@ ROM 80D8F0..80DBB0 (script)
	.section .rom.0080D8F0, "a"
	.incbin "build/scripts/nfp/HI_DUNG.SPC.bin"

@ ROM 80DBB0..80E1D0 (script)
	.section .rom.0080DBB0, "a"
	.incbin "build/scripts/nfp/HI_M00.SPC.bin"

@ ROM 80E1D0..80E430 (script)
	.section .rom.0080E1D0, "a"
	.incbin "build/scripts/nfp/HI_M01_1.SPC.bin"

@ ROM 80E430..80E740 (script)
	.section .rom.0080E430, "a"
	.incbin "build/scripts/nfp/HI_M01_2.SPC.bin"

@ ROM 80E740..80E970 (script)
	.section .rom.0080E740, "a"
	.incbin "build/scripts/nfp/HI_M04.SPC.bin"

@ ROM 80E970..80F210 (script)
	.section .rom.0080E970, "a"
	.incbin "build/scripts/nfp/HI_M07.SPC.bin"

@ ROM 80F210..80F2A0 (script)
	.section .rom.0080F210, "a"
	.incbin "build/scripts/nfp/HI_M07_2.SPC.bin"

@ ROM 80F2A0..80F4F0 (script)
	.section .rom.0080F2A0, "a"
	.incbin "build/scripts/nfp/HI_M09.SPC.bin"

@ ROM 80F4F0..80FAB0 (script)
	.section .rom.0080F4F0, "a"
	.incbin "build/scripts/nfp/HI_M11.SPC.bin"

@ ROM 80FAB0..810F40 (script)
	.section .rom.0080FAB0, "a"
	.incbin "build/scripts/nfp/HI_M24.SPC.bin"

@ ROM 810F40..811890 (script)
	.section .rom.00810F40, "a"
	.incbin "build/scripts/nfp/HI_M24_1.SPC.bin"

@ ROM 811890..812890 (script)
	.section .rom.00811890, "a"
	.incbin "build/scripts/nfp/HI_M24_2.SPC.bin"

@ ROM 812890..813A70 (script)
	.section .rom.00812890, "a"
	.incbin "build/scripts/nfp/HI_M24_4.SPC.bin"

@ ROM 813A70..813E60 (script)
	.section .rom.00813A70, "a"
	.incbin "build/scripts/nfp/HI_M25_1.SPC.bin"

@ ROM 813E60..814430 (script)
	.section .rom.00813E60, "a"
	.incbin "build/scripts/nfp/HI_M25_2.SPC.bin"

@ ROM 814430..814720 (script)
	.section .rom.00814430, "a"
	.incbin "build/scripts/nfp/HI_M26_2.SPC.bin"

@ ROM 814720..8147C0 (script)
	.section .rom.00814720, "a"
	.incbin "build/scripts/nfp/HI_M42.SPC.bin"

@ ROM 8147C0..814B30 (script)
	.section .rom.008147C0, "a"
	.incbin "build/scripts/nfp/HI_NORM.SPC.bin"

@ ROM 81BC80..81C2D0 (script)
	.section .rom.0081BC80, "a"
	.incbin "build/scripts/nfp/J_HOLE.SPC.bin"

@ ROM 81C2D0..81C5D0 (script)
	.section .rom.0081C2D0, "a"
	.incbin "build/scripts/nfp/J_VS_M.SPC.bin"

@ ROM 81C5D0..81D0F0 (script)
	.section .rom.0081C5D0, "a"
	.incbin "build/scripts/nfp/L11_0_0.SPC.bin"

@ ROM 81D0F0..81DB60 (script)
	.section .rom.0081D0F0, "a"
	.incbin "build/scripts/nfp/L11_0_2.SPC.bin"

@ ROM 81DB60..81DFF0 (script)
	.section .rom.0081DB60, "a"
	.incbin "build/scripts/nfp/L11_0_3.SPC.bin"

@ ROM 81DFF0..81EE80 (script)
	.section .rom.0081DFF0, "a"
	.incbin "build/scripts/nfp/L24_0_0.SPC.bin"

@ ROM 81EE80..81F020 (script)
	.section .rom.0081EE80, "a"
	.incbin "build/scripts/nfp/L24_1_0.SPC.bin"

@ ROM 81F020..81F7C0 (script)
	.section .rom.0081F020, "a"
	.incbin "build/scripts/nfp/L25_4_0.SPC.bin"

@ ROM 85ABE0..85AF20 (script)
	.section .rom.0085ABE0, "a"
	.incbin "build/scripts/nfp/MAP00_A.SPC.bin"

@ ROM 8667E0..866A30 (script)
	.section .rom.008667E0, "a"
	.incbin "build/scripts/nfp/MAP01_1A.SPC.bin"

@ ROM 86F3C0..86F4C0 (script)
	.section .rom.0086F3C0, "a"
	.incbin "build/scripts/nfp/MAP01_2A.SPC.bin"

@ ROM 8804D0..8807C0 (script)
	.section .rom.008804D0, "a"
	.incbin "build/scripts/nfp/MAP01_3A.SPC.bin"

@ ROM 886880..886A30 (script)
	.section .rom.00886880, "a"
	.incbin "build/scripts/nfp/MAP01_4A.SPC.bin"

@ ROM 88CAF0..88CD20 (script)
	.section .rom.0088CAF0, "a"
	.incbin "build/scripts/nfp/MAP01_5A.SPC.bin"

@ ROM 89EBE0..89EDE0 (script)
	.section .rom.0089EBE0, "a"
	.incbin "build/scripts/nfp/MAP01_A.SPC.bin"

@ ROM 8AACD0..8AAE30 (script)
	.section .rom.008AACD0, "a"
	.incbin "build/scripts/nfp/MAP03_A.SPC.bin"

@ ROM 8CD330..8CD520 (script)
	.section .rom.008CD330, "a"
	.incbin "build/scripts/nfp/MAP04_4A.SPC.bin"

@ ROM 8D54A0..8D56F0 (script)
	.section .rom.008D54A0, "a"
	.incbin "build/scripts/nfp/MAP04_5A.SPC.bin"

@ ROM 8E1F50..8E2070 (script)
	.section .rom.008E1F50, "a"
	.incbin "build/scripts/nfp/MAP04_6A.SPC.bin"

@ ROM 93A6E0..93ABF0 (script)
	.section .rom.0093A6E0, "a"
	.incbin "build/scripts/nfp/MAP04_A.SPC.bin"

@ ROM 94B9E0..94BD50 (script)
	.section .rom.0094B9E0, "a"
	.incbin "build/scripts/nfp/MAP05_A.SPC.bin"

@ ROM 95BB30..95BE20 (script)
	.section .rom.0095BB30, "a"
	.incbin "build/scripts/nfp/MAP06_1A.SPC.bin"

@ ROM 963B90..963D60 (script)
	.section .rom.00963B90, "a"
	.incbin "build/scripts/nfp/MAP06_2A.SPC.bin"

@ ROM 96CF40..96D060 (script)
	.section .rom.0096CF40, "a"
	.incbin "build/scripts/nfp/MAP06_A.SPC.bin"

@ ROM 980D20..980DC0 (script)
	.section .rom.00980D20, "a"
	.incbin "build/scripts/nfp/MAP07_1A.SPC.bin"

@ ROM 988880..988960 (script)
	.section .rom.00988880, "a"
	.incbin "build/scripts/nfp/MAP07_2A.SPC.bin"

@ ROM 9926A0..992740 (script)
	.section .rom.009926A0, "a"
	.incbin "build/scripts/nfp/MAP07_3A.SPC.bin"

@ ROM A11130..A11790 (script)
	.section .rom.00A11130, "a"
	.incbin "build/scripts/nfp/MAP07_A.SPC.bin"

@ ROM A1CC90..A1CE60 (script)
	.section .rom.00A1CC90, "a"
	.incbin "build/scripts/nfp/MAP08_A.SPC.bin"

@ ROM A329C0..A32DD0 (script)
	.section .rom.00A329C0, "a"
	.incbin "build/scripts/nfp/MAP09_A.SPC.bin"

@ ROM A3A2A0..A3A480 (script)
	.section .rom.00A3A2A0, "a"
	.incbin "build/scripts/nfp/MAP10_1A.SPC.bin"

@ ROM A47120..A473C0 (script)
	.section .rom.00A47120, "a"
	.incbin "build/scripts/nfp/MAP10_A.SPC.bin"

@ ROM A52E90..A531A0 (script)
	.section .rom.00A52E90, "a"
	.incbin "build/scripts/nfp/MAP11_1A.SPC.bin"

@ ROM A531A0..A53290 (script)
	.section .rom.00A531A0, "a"
	.incbin "build/scripts/nfp/MAP11_2.SPC.bin"

@ ROM A5D6D0..A5D7C0 (script)
	.section .rom.00A5D6D0, "a"
	.incbin "build/scripts/nfp/MAP11_2G.SPC.bin"

@ ROM A6F430..A6F830 (script)
	.section .rom.00A6F430, "a"
	.incbin "build/scripts/nfp/MAP11_A.SPC.bin"

@ ROM A97320..A97750 (script)
	.section .rom.00A97320, "a"
	.incbin "build/scripts/nfp/MAP24_1A.SPC.bin"

@ ROM AC3010..AC3390 (script)
	.section .rom.00AC3010, "a"
	.incbin "build/scripts/nfp/MAP24_2A.SPC.bin"

@ ROM AEA690..AEA9D0 (script)
	.section .rom.00AEA690, "a"
	.incbin "build/scripts/nfp/MAP24_4A.SPC.bin"

@ ROM AF37C0..AF3A60 (script)
	.section .rom.00AF37C0, "a"
	.incbin "build/scripts/nfp/MAP24_A.SPC.bin"

@ ROM B1EA70..B1EC50 (script)
	.section .rom.00B1EA70, "a"
	.incbin "build/scripts/nfp/MAP25_1A.SPC.bin"

@ ROM B4ED10..B4F220 (script)
	.section .rom.00B4ED10, "a"
	.incbin "build/scripts/nfp/MAP25_2A.SPC.bin"

@ ROM BC72E0..BC7780 (script)
	.section .rom.00BC72E0, "a"
	.incbin "build/scripts/nfp/MAP25_4A.SPC.bin"

@ ROM BD9120..BD9410 (script)
	.section .rom.00BD9120, "a"
	.incbin "build/scripts/nfp/MAP25_5A.SPC.bin"

@ ROM C06B90..C06ED0 (script)
	.section .rom.00C06B90, "a"
	.incbin "build/scripts/nfp/MAP26_1A.SPC.bin"

@ ROM C183B0..C185B0 (script)
	.section .rom.00C183B0, "a"
	.incbin "build/scripts/nfp/MAP26_2A.SPC.bin"

@ ROM C5AC70..C5B020 (script)
	.section .rom.00C5AC70, "a"
	.incbin "build/scripts/nfp/MAP26_3A.SPC.bin"

@ ROM CB8D10..CB9310 (script)
	.section .rom.00CB8D10, "a"
	.incbin "build/scripts/nfp/MAP26_5A.SPC.bin"

@ ROM CC8B50..CC8CC0 (script)
	.section .rom.00CC8B50, "a"
	.incbin "build/scripts/nfp/MAP26_6A.SPC.bin"

@ ROM D04D20..D05060 (script)
	.section .rom.00D04D20, "a"
	.incbin "build/scripts/nfp/MAP40_A.SPC.bin"

@ ROM D11120..D112B0 (script)
	.section .rom.00D11120, "a"
	.incbin "build/scripts/nfp/MAP41_A.SPC.bin"

@ ROM D49A70..D49D50 (script)
	.section .rom.00D49A70, "a"
	.incbin "build/scripts/nfp/MAP42_A.SPC.bin"

@ ROM D6C6C0..D6C9C0 (script)
	.section .rom.00D6C6C0, "a"
	.incbin "build/scripts/nfp/OBJ_D.SPC.bin"

@ ROM D6C9C0..D6CCE0 (script)
	.section .rom.00D6C9C0, "a"
	.incbin "build/scripts/nfp/OBJ_G.SPC.bin"

@ ROM D6CCE0..D6D0C0 (script)
	.section .rom.00D6CCE0, "a"
	.incbin "build/scripts/nfp/OBJ_J.SPC.bin"

@ ROM D6D0C0..D6D350 (script)
	.section .rom.00D6D0C0, "a"
	.incbin "build/scripts/nfp/OBJ_S.SPC.bin"

@ ROM D6D350..D6D6E0 (script)
	.section .rom.00D6D350, "a"
	.incbin "build/scripts/nfp/OBJ_V.SPC.bin"

@ ROM D6D6E0..D6EAB0 (script)
	.section .rom.00D6D6E0, "a"
	.incbin "build/scripts/nfp/OPEN.SPC.bin"

@ ROM D919A0..D91C80 (script)
	.section .rom.00D919A0, "a"
	.incbin "build/scripts/nfp/PHANTOM.SPC.bin"

@ ROM DA09B0..DA0D30 (script)
	.section .rom.00DA09B0, "a"
	.incbin "build/scripts/nfp/SHOPPA01.SPC.bin"

@ ROM DA0D30..DA10C0 (script)
	.section .rom.00DA0D30, "a"
	.incbin "build/scripts/nfp/SHOPPA02.SPC.bin"

@ ROM DA10C0..DA13F0 (script)
	.section .rom.00DA10C0, "a"
	.incbin "build/scripts/nfp/SHOPPA03.SPC.bin"

@ ROM DA13F0..DA1730 (script)
	.section .rom.00DA13F0, "a"
	.incbin "build/scripts/nfp/SHOPPA04.SPC.bin"

@ ROM DA1730..DA1CB0 (script)
	.section .rom.00DA1730, "a"
	.incbin "build/scripts/nfp/SHOPPA05.SPC.bin"

@ ROM DA1CB0..DA1FF0 (script)
	.section .rom.00DA1CB0, "a"
	.incbin "build/scripts/nfp/SHOPPE01.SPC.bin"

@ ROM DA1FF0..DA2370 (script)
	.section .rom.00DA1FF0, "a"
	.incbin "build/scripts/nfp/SHOPPE02.SPC.bin"

@ ROM DB2A50..DB2E10 (script)
	.section .rom.00DB2A50, "a"
	.incbin "build/scripts/nfp/SPR_DUNG.SPC.bin"

@ ROM DB2E10..DB33A0 (script)
	.section .rom.00DB2E10, "a"
	.incbin "build/scripts/nfp/SPR_NORM.SPC.bin"

@ ROM DC02F0..DC0800 (script)
	.section .rom.00DC02F0, "a"
	.incbin "build/scripts/nfp/SP_M00.SPC.bin"

@ ROM DC0800..DC0E10 (script)
	.section .rom.00DC0800, "a"
	.incbin "build/scripts/nfp/SP_M01.SPC.bin"

@ ROM DC0E10..DC0ED0 (script)
	.section .rom.00DC0E10, "a"
	.incbin "build/scripts/nfp/SP_M01_1.SPC.bin"

@ ROM DC0ED0..DC1400 (script)
	.section .rom.00DC0ED0, "a"
	.incbin "build/scripts/nfp/SP_M01_3.SPC.bin"

@ ROM DC1400..DC14C0 (script)
	.section .rom.00DC1400, "a"
	.incbin "build/scripts/nfp/SP_M01_4.SPC.bin"

@ ROM DC14C0..DC15B0 (script)
	.section .rom.00DC14C0, "a"
	.incbin "build/scripts/nfp/SP_M01_5.SPC.bin"

@ ROM DC15B0..DC1750 (script)
	.section .rom.00DC15B0, "a"
	.incbin "build/scripts/nfp/SP_M01_6.SPC.bin"

@ ROM DC1750..DC1AB0 (script)
	.section .rom.00DC1750, "a"
	.incbin "build/scripts/nfp/SP_M04.SPC.bin"

@ ROM DC1AB0..DC1B70 (script)
	.section .rom.00DC1AB0, "a"
	.incbin "build/scripts/nfp/SP_M04_4.SPC.bin"

@ ROM DC1B70..DC1C50 (script)
	.section .rom.00DC1B70, "a"
	.incbin "build/scripts/nfp/SP_M04_5.SPC.bin"

@ ROM DC1C50..DC1D60 (script)
	.section .rom.00DC1C50, "a"
	.incbin "build/scripts/nfp/SP_M05.SPC.bin"

@ ROM DC1D60..DC2040 (script)
	.section .rom.00DC1D60, "a"
	.incbin "build/scripts/nfp/SP_M06_1.SPC.bin"

@ ROM DC2040..DC2100 (script)
	.section .rom.00DC2040, "a"
	.incbin "build/scripts/nfp/SP_M06_2.SPC.bin"

@ ROM DC2100..DC22F0 (script)
	.section .rom.00DC2100, "a"
	.incbin "build/scripts/nfp/SP_M07.SPC.bin"

@ ROM DC22F0..DC28B0 (script)
	.section .rom.00DC22F0, "a"
	.incbin "build/scripts/nfp/SP_M07_1.SPC.bin"

@ ROM DC28B0..DC2C80 (script)
	.section .rom.00DC28B0, "a"
	.incbin "build/scripts/nfp/SP_M08.SPC.bin"

@ ROM DC2C80..DC2D70 (script)
	.section .rom.00DC2C80, "a"
	.incbin "build/scripts/nfp/SP_M09.SPC.bin"

@ ROM DC2D70..DC2E50 (script)
	.section .rom.00DC2D70, "a"
	.incbin "build/scripts/nfp/SP_M10.SPC.bin"

@ ROM DC2E50..DC3060 (script)
	.section .rom.00DC2E50, "a"
	.incbin "build/scripts/nfp/SP_M10_1.SPC.bin"

@ ROM DC3060..DC3180 (script)
	.section .rom.00DC3060, "a"
	.incbin "build/scripts/nfp/SP_M24.SPC.bin"

@ ROM DC3180..DC3320 (script)
	.section .rom.00DC3180, "a"
	.incbin "build/scripts/nfp/SP_M24_1.SPC.bin"

@ ROM DC3320..DC34A0 (script)
	.section .rom.00DC3320, "a"
	.incbin "build/scripts/nfp/SP_M24_2.SPC.bin"

@ ROM DC34A0..DC35E0 (script)
	.section .rom.00DC34A0, "a"
	.incbin "build/scripts/nfp/SP_M24_3.SPC.bin"

@ ROM DC35E0..DC45B0 (script)
	.section .rom.00DC35E0, "a"
	.incbin "build/scripts/nfp/SP_M24_4.SPC.bin"

@ ROM DC45B0..DC46B0 (script)
	.section .rom.00DC45B0, "a"
	.incbin "build/scripts/nfp/SP_M25_1.SPC.bin"

@ ROM DC46B0..DC4870 (script)
	.section .rom.00DC46B0, "a"
	.incbin "build/scripts/nfp/SP_M25_2.SPC.bin"

@ ROM DC4870..DC4E80 (script)
	.section .rom.00DC4870, "a"
	.incbin "build/scripts/nfp/SP_M25_4.SPC.bin"

@ ROM DC4E80..DC6130 (script)
	.section .rom.00DC4E80, "a"
	.incbin "build/scripts/nfp/SP_M25_5.SPC.bin"

@ ROM DC6130..DC62A0 (script)
	.section .rom.00DC6130, "a"
	.incbin "build/scripts/nfp/SP_M26_1.SPC.bin"

@ ROM DC62A0..DC6C70 (script)
	.section .rom.00DC62A0, "a"
	.incbin "build/scripts/nfp/SP_M26_2.SPC.bin"

@ ROM DC6C70..DC6E00 (script)
	.section .rom.00DC6C70, "a"
	.incbin "build/scripts/nfp/SP_M26_3.SPC.bin"

@ ROM DC6E00..DC7A00 (script)
	.section .rom.00DC6E00, "a"
	.incbin "build/scripts/nfp/SP_M26_5.SPC.bin"

@ ROM DC7A00..DC7CA0 (script)
	.section .rom.00DC7A00, "a"
	.incbin "build/scripts/nfp/SP_M40.SPC.bin"

@ ROM DC7CA0..DC7D60 (script)
	.section .rom.00DC7CA0, "a"
	.incbin "build/scripts/nfp/SP_M41.SPC.bin"

@ ROM DC7D60..DC8080 (script)
	.section .rom.00DC7D60, "a"
	.incbin "build/scripts/nfp/SP_M42.SPC.bin"

@ ROM DC8080..DC8210 (script)
	.section .rom.00DC8080, "a"
	.incbin "build/scripts/nfp/SROLL.SPC.bin"

@ ROM F12390..F12490 (script)
	.section .rom.00F12390, "a"
	.incbin "build/scripts/nfp/S_BTLIRQ.SPC.bin"

@ ROM F12490..F12590 (script)
	.section .rom.00F12490, "a"
	.incbin "build/scripts/nfp/S_BTLOUT.SPC.bin"

@ ROM F12590..F12C30 (script)
	.section .rom.00F12590, "a"
	.incbin "build/scripts/nfp/S_CHRIRQ.SPC.bin"

@ ROM F12C30..F13460 (script)
	.section .rom.00F12C30, "a"
	.incbin "build/scripts/nfp/S_DUNG.SPC.bin"

@ ROM F13460..F13560 (script)
	.section .rom.00F13460, "a"
	.incbin "build/scripts/nfp/S_HITIRQ.SPC.bin"

@ ROM F13560..F135F0 (script)
	.section .rom.00F13560, "a"
	.incbin "build/scripts/nfp/S_MAIN.SPC.bin"

@ ROM F135F0..F13DD0 (script)
	.section .rom.00F135F0, "a"
	.incbin "build/scripts/nfp/S_MAP11.SPC.bin"

@ ROM F13DD0..F195C0 (script)
	.section .rom.00F13DD0, "a"
	.incbin "build/scripts/nfp/S_MAPIRQ.SPC.bin"

@ ROM F195C0..F19970 (script)
	.section .rom.00F195C0, "a"
	.incbin "build/scripts/nfp/S_SIOBTL.SPC.bin"

@ ROM F19970..F19AA0 (script)
	.section .rom.00F19970, "a"
	.incbin "build/scripts/nfp/S_SPRIRQ.SPC.bin"

@ ROM F27EF0..F28410 (script)
	.section .rom.00F27EF0, "a"
	.incbin "build/scripts/nfp/W_MAP.SPC.bin"
