# Per-asset graphics rules. GENERATED by tools/gen_rules.py -- edit
# assets.json and re-run `make rules`, or override a single asset below.
#
# Each rule turns the editable PNG into raw GBA character data:
#     graphics/<kind>/<name>.png  --(bpp, width)-->  build/.../<name>.4bpp
#
# The default build stages compressed assets through tools/build_assets.py:
# unchanged decoded pixels retain their source stream; edits are recompressed.
# These raw conversion targets also let you inspect any asset on demand:
#
#     make build/graphics/backgrounds/OP_05_A.KCG.4bpp
#
# and so the bit depth and width of every asset are written down somewhere you
# can correct.

GBAGFX := $(PYTHON) tools/gbagfx.py

# AD0_P_0A.KCG: 978 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/AD0_P_0A.KCG.4bpp: graphics/backgrounds/AD0_P_0A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AD0_P_0A.KCG --output $@

# AD1_P_0A.KCG: 1016 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/AD1_P_0A.KCG.4bpp: graphics/backgrounds/AD1_P_0A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AD1_P_0A.KCG --output $@

# AD3_P_0A.KCG: 1004 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/AD3_P_0A.KCG.4bpp: graphics/backgrounds/AD3_P_0A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AD3_P_0A.KCG --output $@

# AD4_P_0A.KCG: 627 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/AD4_P_0A.KCG.4bpp: graphics/backgrounds/AD4_P_0A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AD4_P_0A.KCG --output $@

# AD_BG01.KCG: 301 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/AD_BG01.KCG.4bpp: graphics/backgrounds/AD_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AD_BG01.KCG --output $@

# AD_BG02.KCG: 181 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/AD_BG02.KCG.4bpp: graphics/backgrounds/AD_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AD_BG02.KCG --output $@

# AL_BG01.KCG: 369 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/AL_BG01.KCG.4bpp: graphics/backgrounds/AL_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AL_BG01.KCG --output $@

# AL_BG02.KCG: 97 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/AL_BG02.KCG.4bpp: graphics/backgrounds/AL_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AL_BG02.KCG --output $@

# AS_BG01.KCG: 349 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/AS_BG01.KCG.4bpp: graphics/backgrounds/AS_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AS_BG01.KCG --output $@

# AS_BG02.KCG: 181 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/AS_BG02.KCG.4bpp: graphics/backgrounds/AS_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AS_BG02.KCG --output $@

# AT_BG01.KCG: 349 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/AT_BG01.KCG.4bpp: graphics/backgrounds/AT_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset AT_BG01.KCG --output $@

# BA06.TCG: 576 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/BA06.TCG.4bpp: graphics/backgrounds/BA06.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset BA06.TCG --output $@

# BA06_BG.TCG: 544 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/BA06_BG.TCG.4bpp: graphics/tilesets/BA06_BG.TCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 17408

# BA07.TCG: 160 tiles, 4 bpp, 16 tiles wide
$(BUILD)/graphics/backgrounds/BA07.TCG.4bpp: graphics/backgrounds/BA07.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset BA07.TCG --output $@

# CLPASS.KCG: 163 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/CLPASS.KCG.4bpp: graphics/backgrounds/CLPASS.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset CLPASS.KCG --output $@

# CM_BG01.KCG: 217 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/CM_BG01.KCG.4bpp: graphics/backgrounds/CM_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset CM_BG01.KCG --output $@

# CM_BG02.KCG: 148 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/CM_BG02.KCG.4bpp: graphics/backgrounds/CM_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset CM_BG02.KCG --output $@

# DS_BG01.KCG: 541 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/DS_BG01.KCG.4bpp: graphics/backgrounds/DS_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset DS_BG01.KCG --output $@

# DS_BG02.KCG: 432 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/DS_BG02.KCG.4bpp: graphics/backgrounds/DS_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset DS_BG02.KCG --output $@

# GA08.TCG: 448 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/GA08.TCG.4bpp: graphics/tilesets/GA08.TCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 14336

# GA13.TCG: 480 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/GA13.TCG.4bpp: graphics/backgrounds/GA13.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset GA13.TCG --output $@

# GA24.TCG: 320 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/GA24.TCG.4bpp: graphics/backgrounds/GA24.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset GA24.TCG --output $@

# GA25.TCG: 352 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/GA25.TCG.4bpp: graphics/backgrounds/GA25.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset GA25.TCG --output $@

# GA26.TCG: 192 tiles, 4 bpp, 16 tiles wide
$(BUILD)/graphics/backgrounds/GA26.TCG.4bpp: graphics/backgrounds/GA26.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset GA26.TCG --output $@

# GA60.TCG: 352 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/GA60.TCG.4bpp: graphics/tilesets/GA60.TCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 11264

# GA_BG01.KCG: 349 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/GA_BG01.KCG.4bpp: graphics/backgrounds/GA_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset GA_BG01.KCG --output $@

# IT_BG01.KCG: 205 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/IT_BG01.KCG.4bpp: graphics/backgrounds/IT_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset IT_BG01.KCG --output $@

# IT_BG02.KCG: 148 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/IT_BG02.KCG.4bpp: graphics/backgrounds/IT_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset IT_BG02.KCG --output $@

# JA05.TCG: 352 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/JA05.TCG.4bpp: graphics/backgrounds/JA05.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset JA05.TCG --output $@

# MAP00_A.KCG: 719 tiles, 4 bpp, 192 tiles wide
$(BUILD)/graphics/backgrounds/MAP00_A.KCG.4bpp: graphics/backgrounds/MAP00_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP00_A.KCG --output $@

# MAP01_1A.KCG: 1024 tiles, 4 bpp, 60 tiles wide
$(BUILD)/graphics/backgrounds/MAP01_1A.KCG.4bpp: graphics/backgrounds/MAP01_1A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP01_1A.KCG --output $@

# MAP01_2A.KCG: 1019 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP01_2A.KCG.4bpp: graphics/backgrounds/MAP01_2A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP01_2A.KCG --output $@

# MAP01_3A.KCG: 1024 tiles, 4 bpp, 112 tiles wide
$(BUILD)/graphics/backgrounds/MAP01_3A.KCG.4bpp: graphics/backgrounds/MAP01_3A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP01_3A.KCG --output $@

# MAP01_A.KCG: 1024 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP01_A.KCG.4bpp: graphics/backgrounds/MAP01_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP01_A.KCG --output $@

# MAP03_A.KCG: 853 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP03_A.KCG.4bpp: graphics/backgrounds/MAP03_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP03_A.KCG --output $@

# MAP04_6A.KCG: 1007 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP04_6A.KCG.4bpp: graphics/backgrounds/MAP04_6A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP04_6A.KCG --output $@

# MAP04_7A.KCG: 873 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP04_7A.KCG.4bpp: graphics/backgrounds/MAP04_7A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP04_7A.KCG --output $@

# MAP04_A.KCG: 931 tiles, 4 bpp, 192 tiles wide
$(BUILD)/graphics/backgrounds/MAP04_A.KCG.4bpp: graphics/backgrounds/MAP04_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP04_A.KCG --output $@

# MAP05_A.KCG: 723 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP05_A.KCG.4bpp: graphics/backgrounds/MAP05_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP05_A.KCG --output $@

# MAP06_1A.KCG: 1017 tiles, 4 bpp, 104 tiles wide
$(BUILD)/graphics/backgrounds/MAP06_1A.KCG.4bpp: graphics/backgrounds/MAP06_1A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP06_1A.KCG --output $@

# MAP06_2A.KCG: 1014 tiles, 4 bpp, 40 tiles wide
$(BUILD)/graphics/backgrounds/MAP06_2A.KCG.4bpp: graphics/backgrounds/MAP06_2A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP06_2A.KCG --output $@

# MAP06_A.KCG: 1017 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP06_A.KCG.4bpp: graphics/backgrounds/MAP06_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP06_A.KCG --output $@

# MAP07_2A.KCG: 919 tiles, 4 bpp, 30 tiles wide
$(BUILD)/graphics/backgrounds/MAP07_2A.KCG.4bpp: graphics/backgrounds/MAP07_2A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP07_2A.KCG --output $@

# MAP07_3A.KCG: 1000 tiles, 4 bpp, 52 tiles wide
$(BUILD)/graphics/backgrounds/MAP07_3A.KCG.4bpp: graphics/backgrounds/MAP07_3A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP07_3A.KCG --output $@

# MAP07_A.KCG: 1024 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/MAP07_A.KCG.4bpp: graphics/tilesets/MAP07_A.KCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 32768

# MAP08_A.KCG: 907 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP08_A.KCG.4bpp: graphics/backgrounds/MAP08_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP08_A.KCG --output $@

# MAP09_A.KCG: 1024 tiles, 4 bpp, 104 tiles wide
$(BUILD)/graphics/backgrounds/MAP09_A.KCG.4bpp: graphics/backgrounds/MAP09_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP09_A.KCG --output $@

# MAP10_1A.KCG: 954 tiles, 4 bpp, 56 tiles wide
$(BUILD)/graphics/backgrounds/MAP10_1A.KCG.4bpp: graphics/backgrounds/MAP10_1A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP10_1A.KCG --output $@

# MAP10_A.KCG: 1024 tiles, 4 bpp, 72 tiles wide
$(BUILD)/graphics/backgrounds/MAP10_A.KCG.4bpp: graphics/backgrounds/MAP10_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP10_A.KCG --output $@

# MAP11_1A.KCG: 1015 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP11_1A.KCG.4bpp: graphics/backgrounds/MAP11_1A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP11_1A.KCG --output $@

# MAP11_2A.KCG: 1012 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP11_2A.KCG.4bpp: graphics/backgrounds/MAP11_2A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP11_2A.KCG --output $@

# MAP11_A.KCG: 1012 tiles, 4 bpp, 128 tiles wide
$(BUILD)/graphics/backgrounds/MAP11_A.KCG.4bpp: graphics/backgrounds/MAP11_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP11_A.KCG --output $@

# MAP24_1A.KCG: 1016 tiles, 4 bpp, 124 tiles wide
$(BUILD)/graphics/backgrounds/MAP24_1A.KCG.4bpp: graphics/backgrounds/MAP24_1A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP24_1A.KCG --output $@

# MAP24_4A.KCG: 1024 tiles, 4 bpp, 128 tiles wide
$(BUILD)/graphics/backgrounds/MAP24_4A.KCG.4bpp: graphics/backgrounds/MAP24_4A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP24_4A.KCG --output $@

# MAP24_A.KCG: 1019 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP24_A.KCG.4bpp: graphics/backgrounds/MAP24_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP24_A.KCG --output $@

# MAP25_1A.KCG: 978 tiles, 4 bpp, 128 tiles wide
$(BUILD)/graphics/backgrounds/MAP25_1A.KCG.4bpp: graphics/backgrounds/MAP25_1A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP25_1A.KCG --output $@

# MAP25_5A.KCG: 975 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP25_5A.KCG.4bpp: graphics/backgrounds/MAP25_5A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP25_5A.KCG --output $@

# MAP26_1A.KCG: 1004 tiles, 4 bpp, 254 tiles wide
$(BUILD)/graphics/backgrounds/MAP26_1A.KCG.4bpp: graphics/backgrounds/MAP26_1A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP26_1A.KCG --output $@

# MAP26_2A.KCG: 1024 tiles, 4 bpp, 64 tiles wide
$(BUILD)/graphics/backgrounds/MAP26_2A.KCG.4bpp: graphics/backgrounds/MAP26_2A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP26_2A.KCG --output $@

# MAP27_A.KCG: 484 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/MAP27_A.KCG.4bpp: graphics/tilesets/MAP27_A.KCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 15488

# MAP99_A.KCG: 3 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/MAP99_A.KCG.4bpp: graphics/backgrounds/MAP99_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset MAP99_A.KCG --output $@

# ML_BG01.KCG: 369 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/ML_BG01.KCG.4bpp: graphics/backgrounds/ML_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset ML_BG01.KCG --output $@

# MWA.KCG: 125 tiles, 4 bpp, 16 tiles wide
$(BUILD)/graphics/tilesets/MWA.KCG.4bpp: graphics/tilesets/MWA.KCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 4000

# NE01.TCG: 256 tiles, 8 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/NE01.TCG.8bpp: graphics/backgrounds/NE01.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset NE01.TCG --output $@

# NE13.TCG: 256 tiles, 8 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/NE13.TCG.8bpp: graphics/backgrounds/NE13.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset NE13.TCG --output $@

# NE21.TCG: 512 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/NE21.TCG.4bpp: graphics/tilesets/NE21.TCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 16384

# NE32.TCG: 512 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/NE32.TCG.4bpp: graphics/tilesets/NE32.TCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 16384

# NE33.TCG: 256 tiles, 8 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/NE33.TCG.8bpp: graphics/backgrounds/NE33.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset NE33.TCG --output $@

# OP_01_A.KCG: 551 tiles, 4 bpp, 30 tiles wide
$(BUILD)/graphics/backgrounds/OP_01_A.KCG.4bpp: graphics/backgrounds/OP_01_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset OP_01_A.KCG --output $@

# OP_04_A.KCG: 596 tiles, 4 bpp, 30 tiles wide
$(BUILD)/graphics/backgrounds/OP_04_A.KCG.4bpp: graphics/backgrounds/OP_04_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset OP_04_A.KCG --output $@

# OP_05_A.KCG: 595 tiles, 4 bpp, 30 tiles wide
$(BUILD)/graphics/backgrounds/OP_05_A.KCG.4bpp: graphics/backgrounds/OP_05_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset OP_05_A.KCG --output $@

# OP_06_A.KCG: 891 tiles, 4 bpp, 30 tiles wide
$(BUILD)/graphics/backgrounds/OP_06_A.KCG.4bpp: graphics/backgrounds/OP_06_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset OP_06_A.KCG --output $@

# OP_07_A.KCG: 336 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/OP_07_A.KCG.4bpp: graphics/tilesets/OP_07_A.KCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 10752

# OP_08_A.KCG: 417 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/OP_08_A.KCG.4bpp: graphics/backgrounds/OP_08_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset OP_08_A.KCG --output $@

# OP_09_A.KCG: 547 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/OP_09_A.KCG.4bpp: graphics/backgrounds/OP_09_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset OP_09_A.KCG --output $@

# OP_0A_A.KCG: 178 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/OP_0A_A.KCG.4bpp: graphics/backgrounds/OP_0A_A.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset OP_0A_A.KCG --output $@

# PS_BG01.KCG: 499 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/PS_BG01.KCG.4bpp: graphics/backgrounds/PS_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset PS_BG01.KCG --output $@

# PV_BG01.KCG: 349 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/PV_BG01.KCG.4bpp: graphics/backgrounds/PV_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset PV_BG01.KCG --output $@

# PV_BG11.KCG: 31 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/PV_BG11.KCG.4bpp: graphics/backgrounds/PV_BG11.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset PV_BG11.KCG --output $@

# PW_BG01.KCG: 235 tiles, 4 bpp, 16 tiles wide
$(BUILD)/graphics/tilesets/PW_BG01.KCG.4bpp: graphics/tilesets/PW_BG01.KCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 7520

# PW_BOX.KCG: 426 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/PW_BOX.KCG.4bpp: graphics/tilesets/PW_BOX.KCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 13632

# SBA06.TCG: 576 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SBA06.TCG.4bpp: graphics/backgrounds/SBA06.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SBA06.TCG --output $@

# SK02.TCG: 224 tiles, 8 bpp, 16 tiles wide
$(BUILD)/graphics/backgrounds/SK02.TCG.8bpp: graphics/backgrounds/SK02.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SK02.TCG --output $@

# SK03.TCG: 224 tiles, 8 bpp, 16 tiles wide
$(BUILD)/graphics/backgrounds/SK03.TCG.8bpp: graphics/backgrounds/SK03.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SK03.TCG --output $@

# SM_BG01.KCG: 369 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SM_BG01.KCG.4bpp: graphics/backgrounds/SM_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SM_BG01.KCG --output $@

# SM_BG12.KCG: 181 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SM_BG12.KCG.4bpp: graphics/backgrounds/SM_BG12.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SM_BG12.KCG --output $@

# SN06.TCG: 544 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SN06.TCG.4bpp: graphics/backgrounds/SN06.TCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SN06.TCG --output $@

# SN07.TCG: 544 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/SN07.TCG.4bpp: graphics/tilesets/SN07.TCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 17408

# SP_BG01.KCG: 349 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SP_BG01.KCG.4bpp: graphics/backgrounds/SP_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SP_BG01.KCG --output $@

# SP_BG11.KCG: 369 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SP_BG11.KCG.4bpp: graphics/backgrounds/SP_BG11.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SP_BG11.KCG --output $@

# SP_BG12.KCG: 97 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SP_BG12.KCG.4bpp: graphics/backgrounds/SP_BG12.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SP_BG12.KCG --output $@

# SP_BG21.KCG: 349 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SP_BG21.KCG.4bpp: graphics/backgrounds/SP_BG21.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SP_BG21.KCG --output $@

# SP_BG22.KCG: 349 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/SP_BG22.KCG.4bpp: graphics/backgrounds/SP_BG22.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset SP_BG22.KCG --output $@

# SSN07.TCG: 544 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/tilesets/SSN07.TCG.4bpp: graphics/tilesets/SSN07.TCG.png
	@mkdir -p $(dir $@)
	$(GBAGFX) png2tiles $< $@ --bpp 4 --size 17408

# ST_BG01.KCG: 181 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/ST_BG01.KCG.4bpp: graphics/backgrounds/ST_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset ST_BG01.KCG --output $@

# ST_BG02.KCG: 133 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/ST_BG02.KCG.4bpp: graphics/backgrounds/ST_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset ST_BG02.KCG --output $@

# ST_BG03.KCG: 145 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/ST_BG03.KCG.4bpp: graphics/backgrounds/ST_BG03.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset ST_BG03.KCG --output $@

# ST_BG11.KCG: 601 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/ST_BG11.KCG.4bpp: graphics/backgrounds/ST_BG11.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset ST_BG11.KCG --output $@

# T_C01.KCG: 94 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/T_C01.KCG.4bpp: graphics/backgrounds/T_C01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset T_C01.KCG --output $@

# T_C02.KCG: 63 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/T_C02.KCG.4bpp: graphics/backgrounds/T_C02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset T_C02.KCG --output $@

# T_ML_BG.KCG: 394 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/T_ML_BG.KCG.4bpp: graphics/backgrounds/T_ML_BG.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset T_ML_BG.KCG --output $@

# T_TTL06.KCG: 342 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/T_TTL06.KCG.4bpp: graphics/backgrounds/T_TTL06.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset T_TTL06.KCG --output $@

# WM_BG01.KCG: 301 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/WM_BG01.KCG.4bpp: graphics/backgrounds/WM_BG01.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset WM_BG01.KCG --output $@

# WM_BG02.KCG: 205 tiles, 4 bpp, 32 tiles wide
$(BUILD)/graphics/backgrounds/WM_BG02.KCG.4bpp: graphics/backgrounds/WM_BG02.KCG.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py
	@mkdir -p $(dir $@)
	$(PYTHON) tools/mapped_images.py raw --asset WM_BG02.KCG --output $@

# Uncompressed art is part of the ROM image itself, so the
# main build depends on these being converted.
RAW_GFX := \


.PHONY: graphics-convert
graphics-convert: \
	$(BUILD)/graphics/backgrounds/AD0_P_0A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AD1_P_0A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AD3_P_0A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AD4_P_0A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AD_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AD_BG02.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AL_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AL_BG02.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AS_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AS_BG02.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/AT_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/BA06.TCG.4bpp \
	$(BUILD)/graphics/tilesets/BA06_BG.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/BA07.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/CLPASS.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/CM_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/CM_BG02.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/DS_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/DS_BG02.KCG.4bpp \
	$(BUILD)/graphics/tilesets/GA08.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/GA13.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/GA24.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/GA25.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/GA26.TCG.4bpp \
	$(BUILD)/graphics/tilesets/GA60.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/GA_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/IT_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/IT_BG02.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/JA05.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP00_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP01_1A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP01_2A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP01_3A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP01_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP03_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP04_6A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP04_7A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP04_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP05_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP06_1A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP06_2A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP06_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP07_2A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP07_3A.KCG.4bpp \
	$(BUILD)/graphics/tilesets/MAP07_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP08_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP09_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP10_1A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP10_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP11_1A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP11_2A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP11_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP24_1A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP24_4A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP24_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP25_1A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP25_5A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP26_1A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP26_2A.KCG.4bpp \
	$(BUILD)/graphics/tilesets/MAP27_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/MAP99_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/ML_BG01.KCG.4bpp \
	$(BUILD)/graphics/tilesets/MWA.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/NE01.TCG.8bpp \
	$(BUILD)/graphics/backgrounds/NE13.TCG.8bpp \
	$(BUILD)/graphics/tilesets/NE21.TCG.4bpp \
	$(BUILD)/graphics/tilesets/NE32.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/NE33.TCG.8bpp \
	$(BUILD)/graphics/backgrounds/OP_01_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/OP_04_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/OP_05_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/OP_06_A.KCG.4bpp \
	$(BUILD)/graphics/tilesets/OP_07_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/OP_08_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/OP_09_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/OP_0A_A.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/PS_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/PV_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/PV_BG11.KCG.4bpp \
	$(BUILD)/graphics/tilesets/PW_BG01.KCG.4bpp \
	$(BUILD)/graphics/tilesets/PW_BOX.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/SBA06.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/SK02.TCG.8bpp \
	$(BUILD)/graphics/backgrounds/SK03.TCG.8bpp \
	$(BUILD)/graphics/backgrounds/SM_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/SM_BG12.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/SN06.TCG.4bpp \
	$(BUILD)/graphics/tilesets/SN07.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/SP_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/SP_BG11.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/SP_BG12.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/SP_BG21.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/SP_BG22.KCG.4bpp \
	$(BUILD)/graphics/tilesets/SSN07.TCG.4bpp \
	$(BUILD)/graphics/backgrounds/ST_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/ST_BG02.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/ST_BG03.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/ST_BG11.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/T_C01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/T_C02.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/T_ML_BG.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/T_TTL06.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/WM_BG01.KCG.4bpp \
	$(BUILD)/graphics/backgrounds/WM_BG02.KCG.4bpp
