@ PCM sample spans interleaved with the executable region.
@ Generated by tools/split.py from sound/samples/manifest.json.

	.section .rom.0008B89C, "a"
	.incbin "build/sound/samples/08B89C.bin", 0, 12532

	.section .rom.0008E990, "a"
	.incbin "build/sound/samples/08E990.bin", 0, 4124

	.section .rom.0008F9AC, "a"
	.incbin "build/sound/samples/08F9AC.bin", 0, 1812

	.section .rom.000900C0, "a"
	.incbin "build/sound/samples/08F9AC.bin", 1812, 7872

	.section .rom.00091F80, "a"
	.incbin "build/sound/samples/091F80.bin", 0, 11428

	.section .rom.00094C24, "a"
	.incbin "build/sound/samples/094C24.bin", 0, 13468

	.section .rom.000980C0, "a"
	.incbin "build/sound/samples/094C24.bin", 13468, 856

	.section .rom.00098418, "a"
	.incbin "build/sound/samples/098418.bin", 0, 9372

	.section .rom.0009A8B4, "a"
	.incbin "build/sound/samples/09A8B4.bin", 0, 11012

	.section .rom.0009D3B8, "a"
	.incbin "build/sound/samples/09D3B8.bin", 0, 10500

	.section .rom.0009FCBC, "a"
	.incbin "build/sound/samples/09FCBC.bin", 0, 1028

	.section .rom.000A00C0, "a"
	.incbin "build/sound/samples/09FCBC.bin", 1028, 12796

	.section .rom.000A32BC, "a"
	.incbin "build/sound/samples/0A32BC.bin", 0, 9876

	.section .rom.000A5950, "a"
	.incbin "build/sound/samples/0A5950.bin", 0, 9212

	.section .rom.000A7D4C, "a"
	.incbin "build/sound/samples/0A7D4C.bin", 0, 884

	.section .rom.000A80C0, "a"
	.incbin "build/sound/samples/0A7D4C.bin", 884, 6248

	.section .rom.000A9928, "a"
	.incbin "build/sound/samples/0A9928.bin", 0, 5436

	.section .rom.000AAE64, "a"
	.incbin "build/sound/samples/0AAE64.bin", 0, 8708

	.section .rom.000AD068, "a"
	.incbin "build/sound/samples/0AD068.bin", 0, 4420

	.section .rom.000AE1AC, "a"
	.incbin "build/sound/samples/0AE1AC.bin", 0, 4916

	.section .rom.000AF4E0, "a"
	.incbin "build/sound/samples/0AF4E0.bin", 0, 3040

	.section .rom.000B00C0, "a"
	.incbin "build/sound/samples/0AF4E0.bin", 3040, 11004

	.section .rom.000B2BBC, "a"
	.incbin "build/sound/samples/0B2BBC.bin", 0, 5172

	.section .rom.000B3FF0, "a"
	.incbin "build/sound/samples/0B3FF0.bin", 0, 4436

	.section .rom.000B5144, "a"
	.incbin "build/sound/samples/0B5144.bin", 0, 664

	.section .rom.000B53DC, "a"
	.incbin "build/sound/samples/0B53DC.bin", 0, 2176

	.section .rom.000B5C5C, "a"
	.incbin "build/sound/samples/0B5C5C.bin", 0, 4868

	.section .rom.000B6F60, "a"
	.incbin "build/sound/samples/0B6F60.bin", 0, 4448

	.section .rom.000B80C0, "a"
	.incbin "build/sound/samples/0B6F60.bin", 4448, 820

	.section .rom.000B83F4, "a"
	.incbin "build/sound/samples/0B83F4.bin", 0, 14104

	.section .rom.000BBB0C, "a"
	.incbin "build/sound/samples/0BBB0C.bin", 0, 8836

	.section .rom.000BDD90, "a"
	.incbin "build/sound/samples/0BDD90.bin", 0, 9008

	.section .rom.000C00C0, "a"
	.incbin "build/sound/samples/0BDD90.bin", 9008, 8676

	.section .rom.000C22A4, "a"
	.incbin "build/sound/samples/0C22A4.bin", 0, 6600

	.section .rom.000C3C6C, "a"
	.incbin "build/sound/samples/0C3C6C.bin", 0, 17492

	.section .rom.000C80C0, "a"
	.incbin "build/sound/samples/0C3C6C.bin", 17492, 1344

	.section .rom.000C8600, "a"
	.incbin "build/sound/samples/0C8600.bin", 0, 11860

	.section .rom.000CB454, "a"
	.incbin "build/sound/samples/0CB454.bin", 0, 10680

	.section .rom.000CDE0C, "a"
	.incbin "build/sound/samples/0CDE0C.bin", 0, 7772

	.section .rom.000CFC68, "a"
	.incbin "build/sound/samples/0CFC68.bin", 0, 1112

	.section .rom.000D00C0, "a"
	.incbin "build/sound/samples/0CFC68.bin", 1112, 26940

	.section .rom.000D69FC, "a"
	.incbin "build/sound/samples/0D69FC.bin", 0, 5828

	.section .rom.000D80C0, "a"
	.incbin "build/sound/samples/0D69FC.bin", 5828, 2320

	.section .rom.000D89D0, "a"
	.incbin "build/sound/samples/0D89D0.bin", 0, 28052

	.section .rom.000DF764, "a"
	.incbin "build/sound/samples/0DF764.bin", 0, 2396

	.section .rom.000E00C0, "a"
	.incbin "build/sound/samples/0DF764.bin", 2396, 5036

	.section .rom.000E146C, "a"
	.incbin "build/sound/samples/0E146C.bin", 0, 204

	.section .rom.000E1538, "a"
	.incbin "build/sound/samples/0E1538.bin", 0, 11096

	.section .rom.000E4090, "a"
	.incbin "build/sound/samples/0E4090.bin", 0, 4228

	.section .rom.000E5114, "a"
	.incbin "build/sound/samples/0E5114.bin", 0, 5388

	.section .rom.000E6620, "a"
	.incbin "build/sound/samples/0E6620.bin", 0, 3544

	.section .rom.000E73F8, "a"
	.incbin "build/sound/samples/0E73F8.bin", 0, 2836

	.section .rom.000E7F0C, "a"
	.incbin "build/sound/samples/0E7F0C.bin", 0, 436

	.section .rom.000E80C0, "a"
	.incbin "build/sound/samples/0E7F0C.bin", 436, 840

	.section .rom.000E8408, "a"
	.incbin "build/sound/samples/0E8408.bin", 0, 5268

	.section .rom.000E989C, "a"
	.incbin "build/sound/samples/0E989C.bin", 0, 6300

	.section .rom.000EB138, "a"
	.incbin "build/sound/samples/0EB138.bin", 0, 17556

	.section .rom.000EF5CC, "a"
	.incbin "build/sound/samples/0EF5CC.bin", 0, 988

	.section .rom.000EF9A8, "a"
	.incbin "build/sound/samples/0EF9A8.bin", 0, 1816

	.section .rom.000F00C0, "a"
	.incbin "build/sound/samples/0EF9A8.bin", 1816, 5552

	.section .rom.000F1670, "a"
	.incbin "build/sound/samples/0F1670.bin", 0, 6716

	.section .rom.000F30AC, "a"
	.incbin "build/sound/samples/0F30AC.bin", 0, 1316

	.section .rom.000F35D0, "a"
	.incbin "build/sound/samples/0F35D0.bin", 0, 2228

	.section .rom.000F3E84, "a"
	.incbin "build/sound/samples/0F3E84.bin", 0, 13396

	.section .rom.000F72D8, "a"
	.incbin "build/sound/samples/0F72D8.bin", 0, 3560

	.section .rom.000F80C0, "a"
	.incbin "build/sound/samples/0F72D8.bin", 3560, 13356

	.section .rom.000FB4EC, "a"
	.incbin "build/sound/samples/0FB4EC.bin", 0, 2088

	.section .rom.000FBD14, "a"
	.incbin "build/sound/samples/0FBD14.bin", 0, 14772

	.section .rom.000FF6C8, "a"
	.incbin "build/sound/samples/0FF6C8.bin", 0, 2552

	.section .rom.001000C0, "a"
	.incbin "build/sound/samples/0FF6C8.bin", 2552, 12316

	.section .rom.001030DC, "a"
	.incbin "build/sound/samples/1030DC.bin", 0, 10352

	.section .rom.0010594C, "a"
	.incbin "build/sound/samples/10594C.bin", 0, 2776

	.section .rom.00106424, "a"
	.incbin "build/sound/samples/106424.bin", 0, 4080

	.section .rom.00107414, "a"
	.incbin "build/sound/samples/107414.bin", 0, 3244

	.section .rom.001080C0, "a"
	.incbin "build/sound/samples/107414.bin", 3244, 9380

	.section .rom.0010A564, "a"
	.incbin "build/sound/samples/10A564.bin", 0, 3272

	.section .rom.0010B22C, "a"
	.incbin "build/sound/samples/10B22C.bin", 0, 5244

	.section .rom.0010C6A8, "a"
	.incbin "build/sound/samples/10C6A8.bin", 0, 7188

	.section .rom.0010E2BC, "a"
	.incbin "build/sound/samples/10E2BC.bin", 0, 7684

	.section .rom.001100C0, "a"
	.incbin "build/sound/samples/10E2BC.bin", 7684, 3580

	.section .rom.00110EBC, "a"
	.incbin "build/sound/samples/110EBC.bin", 0, 7444

	.section .rom.00112BD0, "a"
	.incbin "build/sound/samples/112BD0.bin", 0, 11860

	.section .rom.00115A24, "a"
	.incbin "build/sound/samples/115A24.bin", 0, 2992

	.section .rom.001165D4, "a"
	.incbin "build/sound/samples/1165D4.bin", 0, 2504

	.section .rom.00116F9C, "a"
	.incbin "build/sound/samples/116F9C.bin", 0, 4388

	.section .rom.001180C0, "a"
	.incbin "build/sound/samples/116F9C.bin", 4388, 21348

	.section .rom.0011D424, "a"
	.incbin "build/sound/samples/11D424.bin", 0, 11420

	.section .rom.001200C0, "a"
	.incbin "build/sound/samples/11D424.bin", 11420, 8760

	.section .rom.001222F8, "a"
	.incbin "build/sound/samples/1222F8.bin", 0, 22164

	.section .rom.0012798C, "a"
	.incbin "build/sound/samples/12798C.bin", 0, 1844

	.section .rom.001280C0, "a"
	.incbin "build/sound/samples/12798C.bin", 1844, 496

	.section .rom.001282B0, "a"
	.incbin "build/sound/samples/1282B0.bin", 0, 10420

	.section .rom.0012AB64, "a"
	.incbin "build/sound/samples/12AB64.bin", 0, 16756

	.section .rom.0012ECD8, "a"
	.incbin "build/sound/samples/12ECD8.bin", 0, 4148

	.section .rom.0012FD0C, "a"
	.incbin "build/sound/samples/12FD0C.bin", 0, 948

	.section .rom.001300C0, "a"
	.incbin "build/sound/samples/12FD0C.bin", 948, 8784

	.section .rom.00132310, "a"
	.incbin "build/sound/samples/132310.bin", 0, 20872

	.section .rom.00137498, "a"
	.incbin "build/sound/samples/137498.bin", 0, 3112

	.section .rom.001380C0, "a"
	.incbin "build/sound/samples/137498.bin", 3112, 384

	.section .rom.00138240, "a"
	.incbin "build/sound/samples/138240.bin", 0, 1264

	.section .rom.00138730, "a"
	.incbin "build/sound/samples/138730.bin", 0, 15148

	.section .rom.0013C25C, "a"
	.incbin "build/sound/samples/13C25C.bin", 0, 4212

	.section .rom.0013D2D0, "a"
	.incbin "build/sound/samples/13D2D0.bin", 0, 3644

	.section .rom.0013E10C, "a"
	.incbin "build/sound/samples/13E10C.bin", 0, 5204

	.section .rom.0013F560, "a"
	.incbin "build/sound/samples/13F560.bin", 0, 2912

	.section .rom.001400C0, "a"
	.incbin "build/sound/samples/13F560.bin", 2912, 6328

	.section .rom.00141978, "a"
	.incbin "build/sound/samples/141978.bin", 0, 22548

	.section .rom.0014718C, "a"
	.incbin "build/sound/samples/14718C.bin", 0, 3892

	.section .rom.001480C0, "a"
	.incbin "build/sound/samples/14718C.bin", 3892, 432

	.section .rom.00148270, "a"
	.incbin "build/sound/samples/148270.bin", 0, 23744

	.section .rom.0014DF30, "a"
	.incbin "build/sound/samples/14DF30.bin", 0, 8592

	.section .rom.001500C0, "a"
	.incbin "build/sound/samples/14DF30.bin", 8592, 7908

	.section .rom.00151FA4, "a"
	.incbin "build/sound/samples/151FA4.bin", 0, 8028

	.section .rom.00153F00, "a"
	.incbin "build/sound/samples/153F00.bin", 0, 16832

	.section .rom.001580C0, "a"
	.incbin "build/sound/samples/153F00.bin", 16832, 3412

	.section .rom.00158E14, "a"
	.incbin "build/sound/samples/158E14.bin", 0, 9492

	.section .rom.0015B328, "a"
	.incbin "build/sound/samples/15B328.bin", 0, 7444

	.section .rom.0015D03C, "a"
	.incbin "build/sound/samples/15D03C.bin", 0, 12420

	.section .rom.001600C0, "a"
	.incbin "build/sound/samples/15D03C.bin", 12420, 4624

	.section .rom.001612D0, "a"
	.incbin "build/sound/samples/1612D0.bin", 0, 8852

	.section .rom.00163564, "a"
	.incbin "build/sound/samples/163564.bin", 0, 19292

	.section .rom.001680C0, "a"
	.incbin "build/sound/samples/163564.bin", 19292, 22540

	.section .rom.0016D8CC, "a"
	.incbin "build/sound/samples/16D8CC.bin", 0, 10228

	.section .rom.001700C0, "a"
	.incbin "build/sound/samples/16D8CC.bin", 10228, 192

	.section .rom.00170180, "a"
	.incbin "build/sound/samples/170180.bin", 0, 10604

	.section .rom.00172AEC, "a"
	.incbin "build/sound/samples/172AEC.bin", 0, 21972

	.section .rom.001780C0, "a"
	.incbin "build/sound/samples/172AEC.bin", 21972, 21892

	.section .rom.0017D644, "a"
	.incbin "build/sound/samples/17D644.bin", 0, 10876

	.section .rom.001800C0, "a"
	.incbin "build/sound/samples/17D644.bin", 10876, 13048

	.section .rom.001833B8, "a"
	.incbin "build/sound/samples/1833B8.bin", 0, 10964

	.section .rom.00185E8C, "a"
	.incbin "build/sound/samples/185E8C.bin", 0, 8756

	.section .rom.001880C0, "a"
	.incbin "build/sound/samples/185E8C.bin", 8756, 1352

	.section .rom.00188608, "a"
	.incbin "build/sound/samples/188608.bin", 0, 7668

	.section .rom.0018A3FC, "a"
	.incbin "build/sound/samples/18A3FC.bin", 0, 8964

	.section .rom.0018C700, "a"
	.incbin "build/sound/samples/18C700.bin", 0, 3684

	.section .rom.0018D564, "a"
	.incbin "build/sound/samples/18D564.bin", 0, 836

	.section .rom.0018D8A8, "a"
	.incbin "build/sound/samples/18D8A8.bin", 0, 4452

	.section .rom.0018EA0C, "a"
	.incbin "build/sound/samples/18EA0C.bin", 0, 5812

	.section .rom.001900C0, "a"
	.incbin "build/sound/samples/18EA0C.bin", 5812, 12272

	.section .rom.001930B0, "a"
	.incbin "build/sound/samples/1930B0.bin", 0, 6932

	.section .rom.00194BC4, "a"
	.incbin "build/sound/samples/194BC4.bin", 0, 6004

	.section .rom.00196338, "a"
	.incbin "build/sound/samples/196338.bin", 0, 7560

	.section .rom.001980C0, "a"
	.incbin "build/sound/samples/196338.bin", 7560, 3756

	.section .rom.00198F6C, "a"
	.incbin "build/sound/samples/198F6C.bin", 0, 8884

	.section .rom.0019B220, "a"
	.incbin "build/sound/samples/19B220.bin", 0, 772

	.section .rom.0019B524, "a"
	.incbin "build/sound/samples/19B524.bin", 0, 3460

	.section .rom.0019C2A8, "a"
	.incbin "build/sound/samples/19C2A8.bin", 0, 8380

	.section .rom.0019E364, "a"
	.incbin "build/sound/samples/19E364.bin", 0, 2924

	.section .rom.0019EED0, "a"
	.incbin "build/sound/samples/19EED0.bin", 0, 4592

	.section .rom.001A00C0, "a"
	.incbin "build/sound/samples/19EED0.bin", 4592, 9380
