// Requires Node.js and playwright-core with an installed Chromium browser.
const {chromium}=require(process.env.MAR_PLAYWRIGHT_MODULE||'playwright-core');
const fs=require('fs');const assert=require('assert');
(async()=>{
 if(!process.argv[2])throw Error('Pass the session JSON written by map_editor_browser_server.py');
 const session=JSON.parse(fs.readFileSync(process.argv[2]));
 assert.equal(session.isolated_fixture,true,'Only run mutations against the isolated browser fixture');
 const output=require('path').resolve(__dirname,'../reports/maps');
 const launch={headless:true};if(process.env.MAR_BROWSER_EXECUTABLE)launch.executablePath=process.env.MAR_BROWSER_EXECUTABLE;
 const browser=await chromium.launch(launch);
 try{
  const page=await browser.newPage({viewport:{width:1500,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(session.url);await page.waitForFunction(()=>document.querySelector('#script-info').textContent.includes('literal calls editable'));
  await page.locator('#map-scroll').evaluate(el=>{el.scrollLeft=80;el.scrollTop=70;});
  const viewport=await page.locator('#map-scroll').boundingBox();
  const mouse={x:viewport.x+151,y:viewport.y+121};
  await page.mouse.move(mouse.x,mouse.y);
  const anchor=()=>page.evaluate(({x,y})=>{const el=document.querySelector('#map-scroll'),r=el.getBoundingClientRect(),z=Number(document.querySelector('#zoom').value);return [(el.scrollLeft+x-r.left-el.clientLeft)/z,(el.scrollTop+y-r.top-el.clientTop)/z];},mouse);
  const beforeZoom=await anchor();
  await page.mouse.wheel(0,-120);await page.waitForFunction(()=>document.querySelector('#zoom').value==='3');
  const afterZoom=await anchor();afterZoom.forEach((v,i)=>assert(Math.abs(v-beforeZoom[i])<1));
  await page.mouse.wheel(0,120);await page.waitForFunction(()=>document.querySelector('#zoom').value==='2');
  for(let i=0;i<4;i++){await page.mouse.wheel(0,-120);await page.waitForTimeout(100);}
  assert.equal(await page.locator('#zoom').inputValue(),'4');
  for(let i=0;i<20;i++){await page.mouse.wheel(0,120);await page.waitForTimeout(50);}
  assert.equal(await page.locator('#zoom').inputValue(),'0.03125');
  assert.equal(await page.evaluate(()=>dirty),false);
  const tilesBox=await page.locator('#tiles-scroll').boundingBox();await page.mouse.move(tilesBox.x+10,tilesBox.y+10);
  await page.mouse.wheel(0,120);await page.waitForTimeout(100);
  assert.equal(await page.locator('#zoom').inputValue(),'0.03125');
  await page.locator('#fit-map').click();
  const fitted=await page.evaluate(()=>{const viewport=document.querySelector('#map-scroll'),canvas=document.querySelector('#map');return {fits:canvas.width<=viewport.clientWidth&&canvas.height<=viewport.clientHeight,zoom:document.querySelector('#zoom').value};});
  assert(fitted.fits);assert(Number(fitted.zoom)>=0.03125);
  await page.locator('#zoom').selectOption('2');
  await page.evaluate(()=>{window.scrollTo(0,0);const el=document.querySelector('#map-scroll');el.scrollLeft=0;el.scrollTop=0;});
  const initial=await page.evaluate(()=>map.document.planes[0].entries[0]);
  const tile=(initial&1023)===1?2:1;
  await page.locator('#tiles').click({position:{x:tile*16+8,y:8}});
  await page.locator('#map').click({position:{x:8,y:8}});
  assert.notEqual(await page.evaluate(()=>map.document.planes[0].entries[0]),initial);
  await page.locator('#undo').click();assert.equal(await page.evaluate(()=>map.document.planes[0].entries[0]),initial);
  await page.locator('#redo').click();assert.equal((await page.evaluate(()=>map.document.planes[0].entries[0]))&1023,tile);
  await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved editable'));
  let saved=JSON.parse(fs.readFileSync(session.root+'/maps/editable/MAP01_A.KMP.json'));assert.equal(saved.planes[0].entries[0]&1023,tile);
  await page.locator('#reload').click();await page.waitForFunction(()=>document.querySelector('#script-info').textContent.includes('literal calls editable')&&!busy);
  assert.equal((await page.evaluate(()=>map.document.planes[0].entries[0]))&1023,tile);
  await page.locator('#modes button[data-mode="collision"]').click();await page.locator('#attribute').fill('7');await page.locator('#map').click({position:{x:8,y:8}});
  await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved editable'));
  saved=JSON.parse(fs.readFileSync(session.root+'/maps/editable/MAP01_A.KMP.json'));assert.equal(saved.attributes.entries[0],7);
  await page.locator('#modes button[data-mode="events"]').click();
  const index=await page.evaluate(()=>script.calls.findIndex(c=>c.function==='SprSet'&&c.editable&&c.arguments.map(a=>a.value).join(',')==='1,0,256'));
  assert(index>=0);await page.locator('#calls').selectOption(String(index));
  assert((await page.locator('#arguments').textContent()).includes('X (pixels, signed 16-bit)'));
  await page.locator('#sprite-guide').check();
  const guidePixel=()=>page.evaluate(()=>Array.from(document.querySelector('#map').getContext('2d').getImageData(256*2,200*2,1,1).data));
  assert.deepEqual(await guidePixel(),[255,223,0,255]);
  await page.locator('#arguments input').nth(2).fill('-1');await page.locator('#arguments input').nth(2).press('Tab');
  assert.notDeepEqual(await guidePixel(),[255,223,0,255]);
  await page.locator('#undo').click();
  assert.deepEqual(await guidePixel(),[255,223,0,255]);
  await page.locator('#sprite-guide').uncheck();
  await page.locator('#arguments input').nth(2).fill('0');await page.locator('#arguments input').nth(2).press('Tab');
  await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved editable'));
  const event=JSON.parse(fs.readFileSync(session.root+'/maps/events/MAP01_A.SPC.json'));assert.equal(Object.values(event.arguments)[0],0);
  await page.locator('#layer').selectOption('0');
  fs.mkdirSync(output,{recursive:true});
  await page.screenshot({path:output+'/editor.png',fullPage:true});
  await page.locator('#scripts').selectOption('D0_BOSS.SPC');
  await page.waitForFunction(()=>script?.name==='D0_BOSS.SPC'&&!busy);
  const hitIndex=await page.evaluate(()=>script.calls.findIndex(c=>c.function==='HitInit'&&c.editable&&c.arguments.map(a=>a.value).join(',')==='1,270,60,60,24'));
  assert(hitIndex>=0);await page.locator('#calls').selectOption(String(hitIndex));
  assert((await page.locator('#arguments').textContent()).includes('Width (pixels, signed 16-bit)'));
  await page.locator('#hit-preview').check();
  const hitPixel=await page.evaluate(()=>Array.from(document.querySelector('#map').getContext('2d').getImageData(270*2,80*2,1,1).data));
  assert.deepEqual(hitPixel,[0,255,255,255]);
  await page.locator('#arguments input').nth(1).fill('260');await page.locator('#arguments input').nth(1).press('Tab');
  const changedPixel=await page.evaluate(()=>Array.from(document.querySelector('#map').getContext('2d').getImageData(260*2,80*2,1,1).data));
  assert.deepEqual(changedPixel,[0,255,255,255]);
  await page.locator('#undo').click();
  assert.equal(await page.locator('#arguments input').nth(1).inputValue(),'270');
  await page.locator('#hit-preview').uncheck();
  // Undo restores data but keeps the conservative unsaved flag.
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('#maps').selectOption('MAP27_A.KMP');await page.waitForFunction(()=>map?.name==='MAP27_A.KMP'&&!busy);
  const unresolved=await page.evaluate(()=>map.unresolved.length);assert.equal(unresolved,0);
  const resolved=await page.evaluate(()=>map.resolved_cells.length);assert.equal(resolved,1);
  assert((await page.locator('#status').textContent()).includes('resolved'));
  assert.deepEqual(errors,[]);
  const proof={sprite_coordinate_guide:true,sprite_guide_edit_undo:true,sprite_coordinate_labels:true,wheel_zoom:true,cursor_anchor:true,zoom_limits:true,fit_whole_map:true,wheel_outside_viewport:true,tile_paint:true,undo_redo:true,save_reload:true,attribute_save:true,event_save:true,hit_rectangle_preview:true,hit_labels:true,hit_preview_undo:true,resolved_external_cells:resolved,unresolved_cells:unresolved,page_errors:errors};
  fs.writeFileSync(output+'/browser-proof.json',JSON.stringify(proof,null,2)+'\n');
  console.log(JSON.stringify(proof));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
