@ ROM 0B80C0..0C00C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000B80C0, "a"
	.incbin "build/sound/samples/0B6F60.bin", 4448, 820

	.section .rom.000B83F4, "a"
	.incbin "build/sound/samples/0B83F4.bin", 0, 14104

	.section .rom.000BBB0C, "a"
	.incbin "build/sound/samples/0BBB0C.bin", 0, 8836

	.section .rom.000BDD90, "a"
	.incbin "build/sound/samples/0BDD90.bin", 0, 9008
