@ ROM 0D00C0..0D80C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000D00C0, "a"
	.incbin "build/sound/samples/0CFC68.bin", 1112, 26940

	.section .rom.000D69FC, "a"
	.incbin "build/sound/samples/0D69FC.bin", 0, 5828
