@ ROM 1880C0..1900C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001880C0, "a"
	.incbin "build/sound/samples/185E8C.bin", 8756, 1352

	.section .rom.00188608, "a"
	.incbin "build/sound/samples/188608.bin", 0, 7668

	.section .rom.0018A3FC, "a"
	.incbin "build/sound/samples/18A3FC.bin", 0, 8964

	.section .rom.0018C700, "a"
	.incbin "build/sound/samples/18C700.bin", 0, 3684

	.section .rom.0018D564, "a"
	.incbin "build/sound/samples/18D564.bin", 0, 836

	.section .rom.0018D8A8, "a"
	.incbin "build/sound/samples/18D8A8.bin", 0, 4452

	.section .rom.0018EA0C, "a"
	.incbin "build/sound/samples/18EA0C.bin", 0, 5812
