@ ROM 1700C0..1780C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001700C0, "a"
	.incbin "build/sound/samples/16D8CC.bin", 10228, 192

	.section .rom.00170180, "a"
	.incbin "build/sound/samples/170180.bin", 0, 10604

	.section .rom.00172AEC, "a"
	.incbin "build/sound/samples/172AEC.bin", 0, 21972
