@ ROM 1300C0..1380C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001300C0, "a"
	.incbin "build/sound/samples/12FD0C.bin", 948, 8784

	.section .rom.00132310, "a"
	.incbin "build/sound/samples/132310.bin", 0, 20872

	.section .rom.00137498, "a"
	.incbin "build/sound/samples/137498.bin", 0, 3112
