@ ROM 1200C0..1280C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001200C0, "a"
	.incbin "build/sound/samples/11D424.bin", 11420, 8760

	.section .rom.001222F8, "a"
	.incbin "build/sound/samples/1222F8.bin", 0, 22164

	.section .rom.0012798C, "a"
	.incbin "build/sound/samples/12798C.bin", 0, 1844
