@ ROM 1580C0..1600C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001580C0, "a"
	.incbin "build/sound/samples/153F00.bin", 16832, 3412

	.section .rom.00158E14, "a"
	.incbin "build/sound/samples/158E14.bin", 0, 9492

	.section .rom.0015B328, "a"
	.incbin "build/sound/samples/15B328.bin", 0, 7444

	.section .rom.0015D03C, "a"
	.incbin "build/sound/samples/15D03C.bin", 0, 12420
