@ ROM 1A80C0..1B0000
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


@ 1A80C0..1A8164 is decompiled as gSong020Track9(); see src/decompiled.json

@ 1A8164..1A8190 is decompiled as gSongHeader_020(); see src/decompiled.json

@ 1A8190..1A81E9 is decompiled as gSong021Track1(); see src/decompiled.json

@ 1A81E9..1A8328 is decompiled as gSong021Track2(); see src/decompiled.json

@ 1A8328..1A83D1 is decompiled as gSong021Track3(); see src/decompiled.json

@ 1A83D1..1A841F is decompiled as gSong021Track4(); see src/decompiled.json

@ 1A841F..1A8539 is decompiled as gSong021Track5(); see src/decompiled.json

@ 1A8539..1A8565 is decompiled as gSong021Track6(); see src/decompiled.json

@ 1A8565..1A8620 is decompiled as gSong021Track7(); see src/decompiled.json

@ 1A8620..1A8674 is decompiled as gSong021Track8(); see src/decompiled.json

@ 1A8674..1A8838 is decompiled as gSong021Track9(); see src/decompiled.json

@ 1A8838..1A8864 is decompiled as gSongHeader_021(); see src/decompiled.json

@ 1A8864..1A8A6F is decompiled as gSong022Track1(); see src/decompiled.json

@ 1A8A6F..1A8B05 is decompiled as gSong022Track2(); see src/decompiled.json

@ 1A8B05..1A8B5A is decompiled as gSong022Track3(); see src/decompiled.json

@ 1A8B5A..1A8BEA is decompiled as gSong022Track4(); see src/decompiled.json

@ 1A8BEA..1A8C14 is decompiled as gSong022Track5(); see src/decompiled.json

@ 1A8C14..1A8C30 is decompiled as gSongHeader_022(); see src/decompiled.json

@ 1A8C30..1A8CFA is decompiled as gSong023Track1(); see src/decompiled.json

@ 1A8CFA..1A8D46 is decompiled as gSong023Track2(); see src/decompiled.json

@ 1A8D46..1A8DC1 is decompiled as gSong023Track3(); see src/decompiled.json

@ 1A8DC1..1A8DEC is decompiled as gSong023Track4(); see src/decompiled.json

@ 1A8DEC..1A8E58 is decompiled as gSong023Track5(); see src/decompiled.json

@ 1A8E58..1A8E74 is decompiled as gSongHeader_023(); see src/decompiled.json

@ 1A8E74..1A8F65 is decompiled as gSong024Track1(); see src/decompiled.json

@ 1A8F65..1A8F9C is decompiled as gSong024Track2(); see src/decompiled.json

@ 1A8F9C..1A916D is decompiled as gSong024Track3(); see src/decompiled.json

@ 1A916D..1A9210 is decompiled as gSong024Track4(); see src/decompiled.json

@ 1A9210..1A9228 is decompiled as gSongHeader_024(); see src/decompiled.json

@ 1A9228..1A9432 is decompiled as gSong026Track1(); see src/decompiled.json

@ 1A9432..1A9503 is decompiled as gSong026Track2(); see src/decompiled.json

@ 1A9503..1A9550 is decompiled as gSong026Track3(); see src/decompiled.json

@ 1A9550..1A967E is decompiled as gSong026Track4(); see src/decompiled.json

@ 1A967E..1A96C7 is decompiled as gSong026Track5(); see src/decompiled.json

@ 1A96C7..1A9722 is decompiled as gSong026Track6(); see src/decompiled.json

@ 1A9722..1A98A4 is decompiled as gSong026Track7(); see src/decompiled.json

@ 1A98A4..1A9920 is decompiled as gSong026Track8(); see src/decompiled.json

@ 1A9920..1A9948 is decompiled as gSongHeader_026(); see src/decompiled.json

@ 1A9948..1A9A7C is decompiled as gSong027Track1(); see src/decompiled.json

@ 1A9A7C..1A9B30 is decompiled as gSong027Track2(); see src/decompiled.json

@ 1A9B30..1A9B80 is decompiled as gSong027Track3(); see src/decompiled.json

@ 1A9B80..1A9BCC is decompiled as gSong027Track4(); see src/decompiled.json

@ 1A9BCC..1A9C27 is decompiled as gSong027Track5(); see src/decompiled.json

@ 1A9C27..1A9C76 is decompiled as gSong027Track6(); see src/decompiled.json

@ 1A9C76..1A9D1F is decompiled as gSong027Track7(); see src/decompiled.json

@ 1A9D1F..1A9DBC is decompiled as gSong027Track8(); see src/decompiled.json

@ 1A9DBC..1A9E6C is decompiled as gSong027Track9(); see src/decompiled.json

@ 1A9E6C..1A9EB8 is decompiled as gSong027Track10(); see src/decompiled.json

@ 1A9EB8..1A9EE8 is decompiled as gSongHeader_027(); see src/decompiled.json

@ 1A9EE8..1A9F4B is decompiled as gSong028Track1(); see src/decompiled.json

@ 1A9F4B..1A9F93 is decompiled as gSong028Track2(); see src/decompiled.json

@ 1A9F93..1A9FD0 is decompiled as gSong028Track3(); see src/decompiled.json

@ 1A9FD0..1A9FF6 is decompiled as gSong028Track4(); see src/decompiled.json

@ 1A9FF6..1AA04B is decompiled as gSong028Track5(); see src/decompiled.json

@ 1AA04B..1AA140 is decompiled as gSong028Track6(); see src/decompiled.json

@ 1AA140..1AA160 is decompiled as gSongHeader_028(); see src/decompiled.json

@ 1AA160..1AA221 is decompiled as gSong030Track1(); see src/decompiled.json

@ 1AA221..1AA2C8 is decompiled as gSong030Track2(); see src/decompiled.json

@ 1AA2C8..1AA42D is decompiled as gSong030Track3(); see src/decompiled.json

@ 1AA42D..1AA4C3 is decompiled as gSong030Track4(); see src/decompiled.json

@ 1AA4C3..1AA52C is decompiled as gSong030Track5(); see src/decompiled.json

@ 1AA52C..1AA6C8 is decompiled as gSong030Track6(); see src/decompiled.json

@ 1AA6C8..1AA6E8 is decompiled as gSongHeader_030(); see src/decompiled.json

@ 1AA6E8..1AA803 is decompiled as gSong031Track1(); see src/decompiled.json

@ 1AA803..1AA8FE is decompiled as gSong031Track2(); see src/decompiled.json

@ 1AA8FE..1AAA57 is decompiled as gSong031Track3(); see src/decompiled.json

@ 1AAA57..1AAC23 is decompiled as gSong031Track4(); see src/decompiled.json

@ 1AAC23..1AADB7 is decompiled as gSong031Track5(); see src/decompiled.json

@ 1AADB7..1AAEDC is decompiled as gSong031Track6(); see src/decompiled.json

@ 1AAEDC..1AB173 is decompiled as gSong031Track7(); see src/decompiled.json

@ 1AB173..1AB350 is decompiled as gSong031Track8(); see src/decompiled.json

@ 1AB350..1AB378 is decompiled as gSongHeader_031(); see src/decompiled.json

@ 1AB378..1AB3F9 is decompiled as gSong032Track1(); see src/decompiled.json

@ 1AB3F9..1AB430 is decompiled as gSong032Track2(); see src/decompiled.json

@ 1AB430..1AB4FB is decompiled as gSong032Track3(); see src/decompiled.json

@ 1AB4FB..1AB571 is decompiled as gSong032Track4(); see src/decompiled.json

@ 1AB571..1AB5C0 is decompiled as gSong032Track5(); see src/decompiled.json

@ 1AB5C0..1AB6C0 is decompiled as gSong032Track6(); see src/decompiled.json

@ 1AB6C0..1AB6E0 is decompiled as gSongHeader_032(); see src/decompiled.json

@ 1AB6E0..1AB6F4 is decompiled as gSong101Track1(); see src/decompiled.json

@ 1AB6F4..1AB700 is decompiled as gSongHeader_101(); see src/decompiled.json

@ 1AB700..1AB714 is decompiled as gSong102Track1(); see src/decompiled.json

@ 1AB714..1AB720 is decompiled as gSongHeader_102(); see src/decompiled.json

@ 1AB720..1AB73C is decompiled as gSong103Track1(); see src/decompiled.json

@ 1AB73C..1AB748 is decompiled as gSongHeader_103(); see src/decompiled.json

@ 1AB748..1AB764 is decompiled as gSong104Track1(); see src/decompiled.json

@ 1AB764..1AB770 is decompiled as gSongHeader_104(); see src/decompiled.json

@ 1AB770..1AB780 is decompiled as gSong105Track1(); see src/decompiled.json

@ 1AB780..1AB78C is decompiled as gSongHeader_105(); see src/decompiled.json

@ 1AB78C..1AB79C is decompiled as gSong106Track1(); see src/decompiled.json

@ 1AB79C..1AB7A8 is decompiled as gSongHeader_106(); see src/decompiled.json

@ 1AB7A8..1AB7B8 is decompiled as gSong107Track1(); see src/decompiled.json

@ 1AB7B8..1AB7C4 is decompiled as gSongHeader_107(); see src/decompiled.json

@ 1AB7C4..1AB7F1 is decompiled as gSong109Track1(); see src/decompiled.json

@ 1AB7F1..1AB814 is decompiled as gSong109Track2(); see src/decompiled.json

@ 1AB814..1AB849 is decompiled as gSong109Track3(); see src/decompiled.json

@ 1AB849..1AB862 is decompiled as gSong109Track4(); see src/decompiled.json

@ 1AB862..1AB873 is decompiled as gSong109Track5(); see src/decompiled.json

@ 1AB873..1AB888 is decompiled as gSong109Track6(); see src/decompiled.json

@ 1AB888..1AB8A8 is decompiled as gSongHeader_109(); see src/decompiled.json

@ 1AB8A8..1AB8D1 is decompiled as gSong110Track1(); see src/decompiled.json

@ 1AB8D1..1AB8F0 is decompiled as gSong110Track2(); see src/decompiled.json

@ 1AB8F0..1AB903 is decompiled as gSong110Track3(); see src/decompiled.json

@ 1AB903..1AB91C is decompiled as gSong110Track4(); see src/decompiled.json

@ 1AB91C..1AB934 is decompiled as gSongHeader_110(); see src/decompiled.json

@ 1AB934..1AB944 is decompiled as gSong111Track1(); see src/decompiled.json

@ 1AB944..1AB950 is decompiled as gSongHeader_111(); see src/decompiled.json

@ 1AB950..1AB960 is decompiled as gSong112Track1(); see src/decompiled.json

@ 1AB960..1AB96C is decompiled as gSongHeader_112(); see src/decompiled.json

@ 1AB96C..1AB97C is decompiled as gSong113Track1(); see src/decompiled.json

@ 1AB97C..1AB988 is decompiled as gSongHeader_113(); see src/decompiled.json

@ 1AB988..1AB998 is decompiled as gSong115Track1(); see src/decompiled.json

@ 1AB998..1AB9A4 is decompiled as gSongHeader_115(); see src/decompiled.json

@ 1AB9A4..1AB9B4 is decompiled as gSong116Track1(); see src/decompiled.json

@ 1AB9B4..1AB9C0 is decompiled as gSongHeader_116(); see src/decompiled.json

@ 1AB9C0..1AB9D0 is decompiled as gSong117Track1(); see src/decompiled.json

@ 1AB9D0..1AB9DC is decompiled as gSongHeader_117(); see src/decompiled.json

@ 1AB9DC..1AB9EC is decompiled as gSong118Track1(); see src/decompiled.json

@ 1AB9EC..1AB9F8 is decompiled as gSongHeader_118(); see src/decompiled.json

@ 1AB9F8..1ABA08 is decompiled as gSong119Track1(); see src/decompiled.json

@ 1ABA08..1ABA14 is decompiled as gSongHeader_119(); see src/decompiled.json

@ 1ABA14..1ABA30 is decompiled as gSong120Track1(); see src/decompiled.json

@ 1ABA30..1ABA59 is decompiled as gSong120Track2(); see src/decompiled.json

@ 1ABA59..1ABA74 is decompiled as gSong120Track3(); see src/decompiled.json

@ 1ABA74..1ABA88 is decompiled as gSongHeader_120(); see src/decompiled.json

@ 1ABA88..1ABA98 is decompiled as gSong121Track1(); see src/decompiled.json

@ 1ABA98..1ABAA4 is decompiled as gSongHeader_121(); see src/decompiled.json

@ 1ABAA4..1ABAB4 is decompiled as gSong122Track1(); see src/decompiled.json

@ 1ABAB4..1ABAC0 is decompiled as gSongHeader_122(); see src/decompiled.json

@ 1ABAC0..1ABAD8 is decompiled as gSong123Track1(); see src/decompiled.json

@ 1ABAD8..1ABAE4 is decompiled as gSongHeader_123(); see src/decompiled.json

@ 1ABAE4..1ABAFC is decompiled as gSong124Track1(); see src/decompiled.json

@ 1ABAFC..1ABB08 is decompiled as gSongHeader_124(); see src/decompiled.json

@ 1ABB08..1ABB3C is decompiled as gSong125Track1(); see src/decompiled.json

@ 1ABB3C..1ABB6C is decompiled as gSong125Track2(); see src/decompiled.json

@ 1ABB6C..1ABBED is decompiled as gSong125Track3(); see src/decompiled.json

@ 1ABBED..1ABC3F is decompiled as gSong125Track4(); see src/decompiled.json

@ 1ABC3F..1ABCDA is decompiled as gSong125Track5(); see src/decompiled.json

@ 1ABCDA..1ABD2C is decompiled as gSong125Track6(); see src/decompiled.json

@ 1ABD2C..1ABDA4 is decompiled as gSong125Track7(); see src/decompiled.json

@ 1ABDA4..1ABDC8 is decompiled as gSongHeader_125(); see src/decompiled.json

@ 1ABDC8..1ABDFA is decompiled as gSong126Track1(); see src/decompiled.json

@ 1ABDFA..1ABE0B is decompiled as gSong126Track2(); see src/decompiled.json

@ 1ABE0B..1ABE1C is decompiled as gSong126Track3(); see src/decompiled.json

@ 1ABE1C..1ABE30 is decompiled as gSongHeader_126(); see src/decompiled.json

@ 1ABE30..1ABE62 is decompiled as gSong127Track1(); see src/decompiled.json

@ 1ABE62..1ABE7C is decompiled as gSong127Track2(); see src/decompiled.json

@ 1ABE7C..1ABE8C is decompiled as gSongHeader_127(); see src/decompiled.json

@ 1ABE8C..1ABECE is decompiled as gSong128Track1(); see src/decompiled.json

@ 1ABECE..1ABEE3 is decompiled as gSong128Track2(); see src/decompiled.json

@ 1ABEE3..1ABF0B is decompiled as gSong128Track3(); see src/decompiled.json

@ 1ABF0B..1ABF26 is decompiled as gSong128Track4(); see src/decompiled.json

@ 1ABF26..1ABF40 is decompiled as gSong128Track5(); see src/decompiled.json

@ 1ABF40..1ABF5C is decompiled as gSongHeader_128(); see src/decompiled.json

@ 1ABF5C..1ABFA0 is decompiled as gSong129Track1(); see src/decompiled.json

@ 1ABFA0..1ABFD1 is decompiled as gSong129Track2(); see src/decompiled.json

@ 1ABFD1..1ABFEC is decompiled as gSong129Track3(); see src/decompiled.json

@ 1ABFEC..1ABFFF is decompiled as gSong129Track4(); see src/decompiled.json

@ 1ABFFF..1AC028 is decompiled as gSong129Track5(); see src/decompiled.json

@ 1AC028..1AC044 is decompiled as gSongHeader_129(); see src/decompiled.json

@ 1AC044..1AC054 is decompiled as gSong130Track1(); see src/decompiled.json

@ 1AC054..1AC060 is decompiled as gSongHeader_130(); see src/decompiled.json

@ 1AC060..1AC070 is decompiled as gSong131Track1(); see src/decompiled.json

@ 1AC070..1AC07C is decompiled as gSongHeader_131(); see src/decompiled.json

@ 1AC07C..1AC08C is decompiled as gSong132Track1(); see src/decompiled.json

@ 1AC08C..1AC098 is decompiled as gSongHeader_132(); see src/decompiled.json

@ 1AC098..1AC0A8 is decompiled as gSong133Track1(); see src/decompiled.json

@ 1AC0A8..1AC0B4 is decompiled as gSongHeader_133(); see src/decompiled.json

@ 1AC0B4..1AC0C4 is decompiled as gSong134Track1(); see src/decompiled.json

@ 1AC0C4..1AC0D0 is decompiled as gSongHeader_134(); see src/decompiled.json

@ 1AC0D0..1AC0E0 is decompiled as gSong135Track1(); see src/decompiled.json

@ 1AC0E0..1AC0EC is decompiled as gSongHeader_135(); see src/decompiled.json

@ 1AC0EC..1AC0FC is decompiled as gSong140Track1(); see src/decompiled.json

@ 1AC0FC..1AC108 is decompiled as gSongHeader_140(); see src/decompiled.json

@ 1AC108..1AC118 is decompiled as gSong141Track1(); see src/decompiled.json

@ 1AC118..1AC124 is decompiled as gSongHeader_141(); see src/decompiled.json

@ 1AC124..1AC134 is decompiled as gSong142Track1(); see src/decompiled.json

@ 1AC134..1AC140 is decompiled as gSongHeader_142(); see src/decompiled.json

@ 1AC140..1AC15D is decompiled as gSong143Track1(); see src/decompiled.json

@ 1AC15D..1AC188 is decompiled as gSong143Track2(); see src/decompiled.json

@ 1AC188..1AC198 is decompiled as gSongHeader_143(); see src/decompiled.json

@ 1AC198..1AC1A8 is decompiled as gSong150Track1(); see src/decompiled.json

@ 1AC1A8..1AC1B4 is decompiled as gSongHeader_150(); see src/decompiled.json

@ 1AC1B4..1AC1C4 is decompiled as gSong151Track1(); see src/decompiled.json

@ 1AC1C4..1AC1D0 is decompiled as gSongHeader_151(); see src/decompiled.json

@ 1AC1D0..1AC208 is decompiled as gSong152Track1(); see src/decompiled.json

@ 1AC208..1AC214 is decompiled as gSongHeader_152(); see src/decompiled.json

@ 1AC214..1AC224 is decompiled as gSong160Track1(); see src/decompiled.json

@ 1AC224..1AC230 is decompiled as gSongHeader_160(); see src/decompiled.json

@ 1AC230..1AC240 is decompiled as gSong161Track1(); see src/decompiled.json

@ 1AC240..1AC24C is decompiled as gSongHeader_161(); see src/decompiled.json

@ 1AC24C..1AC25C is decompiled as gSong162Track1(); see src/decompiled.json

@ 1AC25C..1AC268 is decompiled as gSongHeader_162(); see src/decompiled.json

@ 1AC268..1AC278 is decompiled as gSong163Track1(); see src/decompiled.json

@ 1AC278..1AC284 is decompiled as gSongHeader_163(); see src/decompiled.json

@ 1AC284..1AC294 is decompiled as gSong170Track1(); see src/decompiled.json

@ 1AC294..1AC2A0 is decompiled as gSongHeader_170(); see src/decompiled.json

@ 1AC2A0..1AC2B0 is decompiled as gSong171Track1(); see src/decompiled.json

@ 1AC2B0..1AC2BC is decompiled as gSongHeader_171(); see src/decompiled.json

@ 1AC2BC..1AC2CC is decompiled as gSong172Track1(); see src/decompiled.json

@ 1AC2CC..1AC2D8 is decompiled as gSongHeader_172(); see src/decompiled.json

@ 1AC2D8..1AC2E8 is decompiled as gSong180Track1(); see src/decompiled.json

@ 1AC2E8..1AC2F4 is decompiled as gSongHeader_180(); see src/decompiled.json

@ 1AC2F4..1AC304 is decompiled as gSong181Track1(); see src/decompiled.json

@ 1AC304..1AC310 is decompiled as gSongHeader_181(); see src/decompiled.json

@ 1AC310..1AC340 is decompiled as gSong182Track1(); see src/decompiled.json

@ 1AC340..1AC34C is decompiled as gSongHeader_182(); see src/decompiled.json

@ 1AC34C..1AC35C is decompiled as gSong190Track1(); see src/decompiled.json

@ 1AC35C..1AC368 is decompiled as gSongHeader_190(); see src/decompiled.json

@ 1AC368..1AC378 is decompiled as gSong191Track1(); see src/decompiled.json

@ 1AC378..1AC384 is decompiled as gSongHeader_191(); see src/decompiled.json

@ 1AC384..1AC394 is decompiled as gSong192Track1(); see src/decompiled.json

@ 1AC394..1AC3A0 is decompiled as gSongHeader_192(); see src/decompiled.json

@ 1AC3A0..1AC3B0 is decompiled as gSong200Track1(); see src/decompiled.json

@ 1AC3B0..1AC3BC is decompiled as gSongHeader_200(); see src/decompiled.json

@ 1AC3BC..1AC3CC is decompiled as gSong201Track1(); see src/decompiled.json

@ 1AC3CC..1AC3D8 is decompiled as gSongHeader_201(); see src/decompiled.json

@ 1AC3D8..1AC3E8 is decompiled as gSong202Track1(); see src/decompiled.json

@ 1AC3E8..1AC3F4 is decompiled as gSongHeader_202(); see src/decompiled.json

@ 1AC3F4..1AC404 is decompiled as gSong203Track1(); see src/decompiled.json

@ 1AC404..1AC410 is decompiled as gSongHeader_203(); see src/decompiled.json

@ 1AC410..1AC420 is decompiled as gSong204Track1(); see src/decompiled.json

@ 1AC420..1AC42C is decompiled as gSongHeader_204(); see src/decompiled.json

@ 1AC42C..1AC43C is decompiled as gSong205Track1(); see src/decompiled.json

@ 1AC43C..1AC448 is decompiled as gSongHeader_205(); see src/decompiled.json

@ 1AC448..1AC458 is decompiled as gSong206Track1(); see src/decompiled.json

@ 1AC458..1AC464 is decompiled as gSongHeader_206(); see src/decompiled.json

@ 1AC464..1AC494 is decompiled as gSong207Track1(); see src/decompiled.json

@ 1AC494..1AC4A0 is decompiled as gSongHeader_207(); see src/decompiled.json

@ 1AC4A0..1AC4B0 is decompiled as gSong208Track1(); see src/decompiled.json

@ 1AC4B0..1AC4BC is decompiled as gSongHeader_208(); see src/decompiled.json

@ 1AC4BC..1AC4CC is decompiled as gSong209Track1(); see src/decompiled.json

@ 1AC4CC..1AC4D8 is decompiled as gSongHeader_209(); see src/decompiled.json

@ 1AC4D8..1AC4E8 is decompiled as gSong210Track1(); see src/decompiled.json

@ 1AC4E8..1AC4F4 is decompiled as gSongHeader_210(); see src/decompiled.json

@ 1AC4F4..1AC508 is decompiled as gSong211Track1(); see src/decompiled.json

@ 1AC508..1AC514 is decompiled as gSongHeader_211(); see src/decompiled.json

@ 1AC514..1AC528 is decompiled as gSong212Track1(); see src/decompiled.json

@ 1AC528..1AC534 is decompiled as gSongHeader_212(); see src/decompiled.json

@ 1AC534..1AC544 is decompiled as gSong213Track1(); see src/decompiled.json

@ 1AC544..1AC550 is decompiled as gSongHeader_213(); see src/decompiled.json

@ 1AC550..1AC564 is decompiled as gSong214Track1(); see src/decompiled.json

@ 1AC564..1AC570 is decompiled as gSongHeader_214(); see src/decompiled.json

@ 1AC570..1AC580 is decompiled as gSong215Track1(); see src/decompiled.json

@ 1AC580..1AC58C is decompiled as gSongHeader_215(); see src/decompiled.json

@ 1AC58C..1AC59C is decompiled as gSong216Track1(); see src/decompiled.json

@ 1AC59C..1AC5A8 is decompiled as gSongHeader_216(); see src/decompiled.json

@ 1AC5A8..1AC5B8 is decompiled as gSong217Track1(); see src/decompiled.json

@ 1AC5B8..1AC5C4 is decompiled as gSongHeader_217(); see src/decompiled.json

@ 1AC5C4..1AC5D4 is decompiled as gSong218Track1(); see src/decompiled.json

@ 1AC5D4..1AC5E0 is decompiled as gSongHeader_218(); see src/decompiled.json

@ 1AC5E0..1AC5F0 is decompiled as gSong219Track1(); see src/decompiled.json

@ 1AC5F0..1AC5FC is decompiled as gSongHeader_219(); see src/decompiled.json

@ 1AC5FC..1AC60C is decompiled as gSong220Track1(); see src/decompiled.json

@ 1AC60C..1AC618 is decompiled as gSongHeader_220(); see src/decompiled.json

	.section .rom.001AC618, "ax"
	.syntax unified
	.thumb
	strh r3, [r2, r1]
	.inst.n 0x4D41
	mov r7, r11
	ldrsb r7, [r3, r1]
	adds r0, #49
	movs r3, r6
	ldr r6, [sp, #884]
	lsrs r7, r0, #32
	.inst.n 0x4EA8
	lsls r0, r0, #12
	ldr r7, [sp, #116]
	lsrs r7, r0, #32
	str r0, [r0, #16]
	lsls r0, r0, #12
	.inst.n 0x4EA9
	lsls r0, r0, #12
	ldr r7, [sp, #372]
	lsrs r7, r0, #32
	ldr r6, _081AC660
	lsls r0, r0, #12
	ldr r7, [sp, #676]
	lsrs r7, r0, #32
	str r4, [r0, #16]
	lsls r0, r0, #12
	ldr r6, _081AC670

	.thumb_func
	.thumb
	.global sub_081AC64A
sub_081AC64A:
	lsls r0, r0, #12
	str r4, [r0, #16]
	lsls r0, r0, #12
	muls r3, r2
	str r2, [r2, r1]
	movs r0, r0
	movs r0, r0
	.inst.n 0x4F43
	cmp r4, r8
	movs r0, r0
	movs r0, r0
	.global _081AC660
_081AC660:
	.4byte 0x4D524554
	.4byte 0x00000000
	.4byte 0x5241564E
	.4byte 0x00000000
	.global _081AC670
_081AC670:
	.4byte 0x52415653
	.4byte 0x00000000
	.4byte 0x434E5546
	.4byte 0x00000000
	.4byte 0x454E494C
	.4byte 0x00000000
	.4byte 0x75736572
	.4byte 0x0000746C
	.4byte 0x6E726373
	.4byte 0x00656D61
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00006425

@ 1AC6A8..1AC6B0 is decompiled as gScriptBuiltinNameResurn(); see src/decompiled.json

@ 1AC6B0..1AC6B8 is decompiled as gScriptBuiltinNameExit(); see src/decompiled.json

@ 1AC6B8..1AC6C0 is decompiled as gScriptBuiltinNameCall(); see src/decompiled.json

@ 1AC6C0..1AC6C8 is decompiled as gScriptBuiltinNameExec(); see src/decompiled.json

@ 1AC6C8..1AC6D0 is decompiled as gScriptBuiltinNameChain(); see src/decompiled.json

@ 1AC6D0..1AC6D8 is decompiled as gScriptBuiltinNameStrmid(); see src/decompiled.json

@ 1AC6D8..1AC6E4 is decompiled as gScriptBuiltinNameStrright(); see src/decompiled.json

@ 1AC6E4..1AC6EC is decompiled as gScriptBuiltinNameStrleft(); see src/decompiled.json

@ 1AC6EC..1AC6F4 is decompiled as gScriptBuiltinNameStrlen(); see src/decompiled.json

@ 1AC6F4..1AC6FC is decompiled as gScriptBuiltinNameStrcmp(); see src/decompiled.json

@ 1AC6FC..1AC700 is decompiled as gScriptBuiltinNameVal(); see src/decompiled.json

@ 1AC700..1AC704 is decompiled as gScriptBuiltinNameStr(); see src/decompiled.json

@ 1AC704..1AC70C is decompiled as gScriptBuiltinNameSrand(); see src/decompiled.json

@ 1AC70C..1AC714 is decompiled as gScriptBuiltinNameRand(); see src/decompiled.json

@ 1AC714..1AC718 is decompiled as gScriptBuiltinNameMin(); see src/decompiled.json

@ 1AC718..1AC71C is decompiled as gScriptBuiltinNameMax(); see src/decompiled.json

@ 1AC71C..1AC720 is decompiled as gScriptBuiltinNameChr(); see src/decompiled.json

@ 1AC720..1AC724 is decompiled as gScriptBuiltinNameAsc(); see src/decompiled.json

@ 1AC724..1AC728 is decompiled as gScriptBuiltinNameAbs(); see src/decompiled.json

@ 1AC728..1AC7A2 is decompiled as gVfprintfConstants(); see src/decompiled.json

	.section .rom.001AC7A2, "ax"
	.syntax unified
	.byte 0x00
	.byte 0x00

	.thumb_func
	.thumb
	.global sub_081AC7A4
sub_081AC7A4:
	movs r0, #0
	movs r0, #32
	.global _081AC7A8
_081AC7A8:
	.4byte 0x20202020
	movs r0, #32
	cmp r0, #40
	cmp r0, #40
	movs r0, #40
	movs r0, #32
	movs r0, #32
	movs r0, #32
	movs r0, #32
	movs r0, #32
	movs r0, #32
	movs r0, #32
	movs r0, #32
	.global _081AC7C4
_081AC7C4:
	.4byte 0x10108820
	asrs r0, r2, #32
	asrs r0, r2, #32
	asrs r0, r2, #32
	asrs r0, r2, #32
	asrs r0, r2, #32
	asrs r0, r2, #32
	lsls r0, r2, #16
	lsls r4, r0, #16
	lsls r4, r0, #16
	lsls r4, r0, #16
	lsls r4, r0, #16
	asrs r4, r0, #32
	.global _081AC7E0
_081AC7E0:
	.4byte 0x10101010
	asrs r0, r2, #32
	adcs r1, r0
	adcs r1, r0
	adcs r1, r0
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	asrs r0, r2, #32
	asrs r0, r2, #32
	asrs r0, r2, #32
	negs r2, r0
	negs r2, r0
	negs r2, r0
	lsls r2, r0, #8
	lsls r2, r0, #8
	lsls r2, r0, #8
	lsls r2, r0, #8
	lsls r2, r0, #8
	lsls r2, r0, #8
	lsls r2, r0, #8
	lsls r2, r0, #8
	.global _081AC81C
_081AC81C:
	.4byte 0x02020202  @ EWRAM+0x20202
	asrs r0, r2, #32
	asrs r0, r2, #32
	movs r0, r4
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	.global _081AC838
_081AC838:
	.4byte 0x00000000
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	.global _081AC854
_081AC854:
	.4byte 0x00000000
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	.global _081AC870
_081AC870:
	.4byte 0x00000000
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	.global _081AC890
_081AC890:
	.4byte 0x00000000
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0

@ 1AC8A8..1AC8BA is decompiled as gDtoaConstants(); see src/decompiled.json

	.section .rom.001AC8BA, "ax"
	.syntax unified
	.thumb
	movs r0, r0
	lsls r3, r0, #1
	movs r0, r0

@ 1AC8C0..1AC8FA is decompiled as gLocaleConstants(); see src/decompiled.json

	.section .rom.001AC8FA, "ax"
	.syntax unified
	.thumb
	movs r0, r0

@ 1AC8FC..1ACA20 is decompiled as gMultiprecisionConstants(); see src/decompiled.json

@ 1ACA20..1ACA45 is decompiled as gNewlibSyscallStrings(); see src/decompiled.json

	.section .rom.001ACA45, "ax"
	.syntax unified
	.byte 0x00
	.byte 0x00
	.byte 0x00
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.global _081ACAD8
_081ACAD8:
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.global _081ACB3C
_081ACB3C:
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x10000800
	.4byte 0x20001000
	.4byte 0x04000100
	.4byte 0x40001000

@ 1ACB58..1ACB7C is decompiled as gTileRemainderMasks();
@ see src/decompiled.json

	.section .rom.001ACB7C, "ax"
	.syntax unified
	.4byte 0x08086B50
	.4byte 0x08005B2D
	.4byte 0x08086B4C
	.4byte 0x08005B35
	.4byte 0x08086B44
	.4byte 0x08005B45
	.4byte 0x08086B3C
	.4byte 0x08005B59
	.4byte 0x08086B34
	.4byte 0x08005B6D
	.4byte 0x08086B2C
	.4byte 0x08005B7D
	.4byte 0x08086B24
	.4byte 0x08005B91
	.4byte 0x08086B1C
	.4byte 0x08005BA1
	.4byte 0x08086B10
	.4byte 0x08005BCD
	.4byte 0x08086B04
	.4byte 0x08005BE1
	.4byte 0x08086AFC
	.4byte 0x08005C15
	.4byte 0x08086AF0
	.4byte 0x08005C39
	.4byte 0x08086AE4
	.4byte 0x08005C5D
	.4byte 0x08086AD8
	.4byte 0x08005C75
	.4byte 0x08086ACC
	.4byte 0x08005C89
	.4byte 0x08086AC0
	.4byte 0x08005CDD
	.4byte 0x08086AB8
	.4byte 0x08005D51
	.4byte 0x08086AB0
	.4byte 0x08005D25
	.4byte 0x08086AA8
	.4byte 0x08005E51
	.4byte 0x08086A9C
	.4byte 0x08005E65
	.4byte 0x08086A94
	.4byte 0x08005D79
	.4byte 0x08086A88
	.4byte 0x08005D99
	.4byte 0x08086A80
	.4byte 0x08005DAD
	.4byte 0x08086A74
	.4byte 0x08005E3D
	.4byte 0x00000000
	.4byte 0x00000000

@ 1ACC44..1ACC50 is decompiled as gDynamicSoundPlayerOrder(); see src/decompiled.json

@ 1ACC50..1ACC70 is decompiled as gBattleRuntimePresetA(); see src/decompiled.json

@ 1ACC70..1ACC90 is decompiled as gBattleRuntimePresetB(); see src/decompiled.json

@ 1ACC90..1ACCA0 is decompiled as gFriendArmOwnershipBits(); see src/decompiled.json

@ 1ACCA0..1ACCB0 is decompiled as gBattlePartyDefaults(); see src/decompiled.json

@ 1ACCB0..1AD3A0 is decompiled as gBattleActionHandlers(); see src/decompiled.json

@ 1AD3A0..1AD460 is decompiled as gTwoDigitResourceNames(); see src/decompiled.json

@ 1AD460..1AD494 is decompiled as gGeneratedEffectNames(); see src/decompiled.json

@ 1AD494..1AD49C is decompiled as gResourceSlotIndices(); see src/decompiled.json

@ 1AD49C..1AD4A4 is decompiled as gResourceSlotMasks(); see src/decompiled.json

@ 1AD4A4..1AD634 is decompiled as gCharacterGrowthThresholds(); see src/decompiled.json

@ 1AD634..1AFE84 is decompiled as gBattleCharacterDefinitions(); see src/decompiled.json

@ 1AFE84..1AFEA4 is decompiled as gEngineStartupHandlers(); see src/decompiled.json

@ 1AFEA4..1B0000 is decompiled as gScriptNativeCommands(); see src/decompiled.json
