@ ROM 1400C0..1480C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001400C0, "a"
	.incbin "build/sound/samples/13F560.bin", 2912, 6328

	.section .rom.00141978, "a"
	.incbin "build/sound/samples/141978.bin", 0, 22548

	.section .rom.0014718C, "a"
	.incbin "build/sound/samples/14718C.bin", 0, 3892
