@ ROM 1180C0..1200C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001180C0, "a"
	.incbin "build/sound/samples/116F9C.bin", 4388, 21348

	.section .rom.0011D424, "a"
	.incbin "build/sound/samples/11D424.bin", 0, 11420
