@ ROM 0A80C0..0B00C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000A80C0, "a"
	.incbin "build/sound/samples/0A7D4C.bin", 884, 6248

	.section .rom.000A9928, "a"
	.incbin "build/sound/samples/0A9928.bin", 0, 5436

	.section .rom.000AAE64, "a"
	.incbin "build/sound/samples/0AAE64.bin", 0, 8708

	.section .rom.000AD068, "a"
	.incbin "build/sound/samples/0AD068.bin", 0, 4420

	.section .rom.000AE1AC, "a"
	.incbin "build/sound/samples/0AE1AC.bin", 0, 4916

	.section .rom.000AF4E0, "a"
	.incbin "build/sound/samples/0AF4E0.bin", 0, 3040
