@ ROM 1980C0..1A00C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001980C0, "a"
	.incbin "build/sound/samples/196338.bin", 7560, 3756

	.section .rom.00198F6C, "a"
	.incbin "build/sound/samples/198F6C.bin", 0, 8884

	.section .rom.0019B220, "a"
	.incbin "build/sound/samples/19B220.bin", 0, 772

	.section .rom.0019B524, "a"
	.incbin "build/sound/samples/19B524.bin", 0, 3460

	.section .rom.0019C2A8, "a"
	.incbin "build/sound/samples/19C2A8.bin", 0, 8380

	.section .rom.0019E364, "a"
	.incbin "build/sound/samples/19E364.bin", 0, 2924

	.section .rom.0019EED0, "a"
	.incbin "build/sound/samples/19EED0.bin", 0, 4592
