@ ROM 1480C0..1500C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001480C0, "a"
	.incbin "build/sound/samples/14718C.bin", 3892, 432

	.section .rom.00148270, "a"
	.incbin "build/sound/samples/148270.bin", 0, 23744

	.section .rom.0014DF30, "a"
	.incbin "build/sound/samples/14DF30.bin", 0, 8592
