@ ROM 0C00C0..0C80C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000C00C0, "a"
	.incbin "build/sound/samples/0BDD90.bin", 9008, 8676

	.section .rom.000C22A4, "a"
	.incbin "build/sound/samples/0C22A4.bin", 0, 6600

	.section .rom.000C3C6C, "a"
	.incbin "build/sound/samples/0C3C6C.bin", 0, 17492
