@ ROM 0D80C0..0E00C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000D80C0, "a"
	.incbin "build/sound/samples/0D69FC.bin", 5828, 2320

	.section .rom.000D89D0, "a"
	.incbin "build/sound/samples/0D89D0.bin", 0, 28052

	.section .rom.000DF764, "a"
	.incbin "build/sound/samples/0DF764.bin", 0, 2396
