@ ROM 0A00C0..0A80C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000A00C0, "a"
	.incbin "build/sound/samples/09FCBC.bin", 1028, 12796

	.section .rom.000A32BC, "a"
	.incbin "build/sound/samples/0A32BC.bin", 0, 9876

	.section .rom.000A5950, "a"
	.incbin "build/sound/samples/0A5950.bin", 0, 9212

	.section .rom.000A7D4C, "a"
	.incbin "build/sound/samples/0A7D4C.bin", 0, 884
