@ ROM 0F00C0..0F80C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000F00C0, "a"
	.incbin "build/sound/samples/0EF9A8.bin", 1816, 5552

	.section .rom.000F1670, "a"
	.incbin "build/sound/samples/0F1670.bin", 0, 6716

	.section .rom.000F30AC, "a"
	.incbin "build/sound/samples/0F30AC.bin", 0, 1316

	.section .rom.000F35D0, "a"
	.incbin "build/sound/samples/0F35D0.bin", 0, 2228

	.section .rom.000F3E84, "a"
	.incbin "build/sound/samples/0F3E84.bin", 0, 13396

	.section .rom.000F72D8, "a"
	.incbin "build/sound/samples/0F72D8.bin", 0, 3560
