@ ROM 1600C0..1680C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001600C0, "a"
	.incbin "build/sound/samples/15D03C.bin", 12420, 4624

	.section .rom.001612D0, "a"
	.incbin "build/sound/samples/1612D0.bin", 0, 8852

	.section .rom.00163564, "a"
	.incbin "build/sound/samples/163564.bin", 0, 19292
