@ ROM 0C80C0..0D00C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000C80C0, "a"
	.incbin "build/sound/samples/0C3C6C.bin", 17492, 1344

	.section .rom.000C8600, "a"
	.incbin "build/sound/samples/0C8600.bin", 0, 11860

	.section .rom.000CB454, "a"
	.incbin "build/sound/samples/0CB454.bin", 0, 10680

	.section .rom.000CDE0C, "a"
	.incbin "build/sound/samples/0CDE0C.bin", 0, 7772

	.section .rom.000CFC68, "a"
	.incbin "build/sound/samples/0CFC68.bin", 0, 1112
