@ ROM 1080C0..1100C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001080C0, "a"
	.incbin "build/sound/samples/107414.bin", 3244, 9380

	.section .rom.0010A564, "a"
	.incbin "build/sound/samples/10A564.bin", 0, 3272

	.section .rom.0010B22C, "a"
	.incbin "build/sound/samples/10B22C.bin", 0, 5244

	.section .rom.0010C6A8, "a"
	.incbin "build/sound/samples/10C6A8.bin", 0, 7188

	.section .rom.0010E2BC, "a"
	.incbin "build/sound/samples/10E2BC.bin", 0, 7684
