@ ROM 1000C0..1080C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001000C0, "a"
	.incbin "build/sound/samples/0FF6C8.bin", 2552, 12316

	.section .rom.001030DC, "a"
	.incbin "build/sound/samples/1030DC.bin", 0, 10352

	.section .rom.0010594C, "a"
	.incbin "build/sound/samples/10594C.bin", 0, 2776

	.section .rom.00106424, "a"
	.incbin "build/sound/samples/106424.bin", 0, 4080

	.section .rom.00107414, "a"
	.incbin "build/sound/samples/107414.bin", 0, 3244
