@ ROM 1280C0..1300C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001280C0, "a"
	.incbin "build/sound/samples/12798C.bin", 1844, 496

	.section .rom.001282B0, "a"
	.incbin "build/sound/samples/1282B0.bin", 0, 10420

	.section .rom.0012AB64, "a"
	.incbin "build/sound/samples/12AB64.bin", 0, 16756

	.section .rom.0012ECD8, "a"
	.incbin "build/sound/samples/12ECD8.bin", 0, 4148

	.section .rom.0012FD0C, "a"
	.incbin "build/sound/samples/12FD0C.bin", 0, 948
