@ ROM 1380C0..1400C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001380C0, "a"
	.incbin "build/sound/samples/137498.bin", 3112, 384

	.section .rom.00138240, "a"
	.incbin "build/sound/samples/138240.bin", 0, 1264

	.section .rom.00138730, "a"
	.incbin "build/sound/samples/138730.bin", 0, 15148

	.section .rom.0013C25C, "a"
	.incbin "build/sound/samples/13C25C.bin", 0, 4212

	.section .rom.0013D2D0, "a"
	.incbin "build/sound/samples/13D2D0.bin", 0, 3644

	.section .rom.0013E10C, "a"
	.incbin "build/sound/samples/13E10C.bin", 0, 5204

	.section .rom.0013F560, "a"
	.incbin "build/sound/samples/13F560.bin", 0, 2912
