@ ROM 0900C0..0980C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000900C0, "a"
	.incbin "build/sound/samples/08F9AC.bin", 1812, 7872

	.section .rom.00091F80, "a"
	.incbin "build/sound/samples/091F80.bin", 0, 11428

	.section .rom.00094C24, "a"
	.incbin "build/sound/samples/094C24.bin", 0, 13468
