@ ROM 0E00C0..0E80C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000E00C0, "a"
	.incbin "build/sound/samples/0DF764.bin", 2396, 5036

	.section .rom.000E146C, "a"
	.incbin "build/sound/samples/0E146C.bin", 0, 204

	.section .rom.000E1538, "a"
	.incbin "build/sound/samples/0E1538.bin", 0, 11096

	.section .rom.000E4090, "a"
	.incbin "build/sound/samples/0E4090.bin", 0, 4228

	.section .rom.000E5114, "a"
	.incbin "build/sound/samples/0E5114.bin", 0, 5388

	.section .rom.000E6620, "a"
	.incbin "build/sound/samples/0E6620.bin", 0, 3544

	.section .rom.000E73F8, "a"
	.incbin "build/sound/samples/0E73F8.bin", 0, 2836

	.section .rom.000E7F0C, "a"
	.incbin "build/sound/samples/0E7F0C.bin", 0, 436
