@ ROM 1780C0..1800C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001780C0, "a"
	.incbin "build/sound/samples/172AEC.bin", 21972, 21892

	.section .rom.0017D644, "a"
	.incbin "build/sound/samples/17D644.bin", 0, 10876
