@ ROM 1680C0..1700C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001680C0, "a"
	.incbin "build/sound/samples/163564.bin", 19292, 22540

	.section .rom.0016D8CC, "a"
	.incbin "build/sound/samples/16D8CC.bin", 0, 10228
