@ ROM 1800C0..1880C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001800C0, "a"
	.incbin "build/sound/samples/17D644.bin", 10876, 13048

	.section .rom.001833B8, "a"
	.incbin "build/sound/samples/1833B8.bin", 0, 10964

	.section .rom.00185E8C, "a"
	.incbin "build/sound/samples/185E8C.bin", 0, 8756
