@ ROM 0F80C0..1000C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000F80C0, "a"
	.incbin "build/sound/samples/0F72D8.bin", 3560, 13356

	.section .rom.000FB4EC, "a"
	.incbin "build/sound/samples/0FB4EC.bin", 0, 2088

	.section .rom.000FBD14, "a"
	.incbin "build/sound/samples/0FBD14.bin", 0, 14772

	.section .rom.000FF6C8, "a"
	.incbin "build/sound/samples/0FF6C8.bin", 0, 2552
