@ ROM 1900C0..1980C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001900C0, "a"
	.incbin "build/sound/samples/18EA0C.bin", 5812, 12272

	.section .rom.001930B0, "a"
	.incbin "build/sound/samples/1930B0.bin", 0, 6932

	.section .rom.00194BC4, "a"
	.incbin "build/sound/samples/194BC4.bin", 0, 6004

	.section .rom.00196338, "a"
	.incbin "build/sound/samples/196338.bin", 0, 7560
