@ ROM 0880C0..0900C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000880C0, "ax"
	.syntax unified
	.thumb
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r1]
	ldrsh r5, [r1, r5]
	cmp r6, r9
	adds r4, #51
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r1]
	ldrsh r5, [r1, r5]
	cmp r6, r9
	adds r5, #51
	.global _080880D8
_080880D8:
	.4byte 0x00000000
	.4byte 0x4E5F5053
	.4byte 0x00353345
	.4byte 0x5F4D5241
	.4byte 0x3633454E
	.4byte 0x00000000
	.4byte 0x5F4D5241

	.thumb_func
	.thumb
	.global sub_080880F4
sub_080880F4:
	cmp r6, r9

	.thumb_func
	.thumb
	.global sub_080880F6
sub_080880F6:
	subs r0, #51
	.global _080880F8
_080880F8:
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x3933454E
	.global _08088104
_08088104:
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x3933454E
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x3134454E
	.global _0808811C
_0808811C:
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x31314E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x30255750
	.global _08088134
_08088134:
	.4byte 0x00006432
	.4byte 0x5F4D5241
	.4byte 0x39395750
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x30304253
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x31304253
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x32304253
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x33304253
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x31304B53
	.global _0808817C
_0808817C:
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x38304E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x32304B53
	.4byte 0x00000000
	.4byte 0x2E52414D
	.4byte 0x0050464E
	.4byte 0x32304B53
	.4byte 0x4743542E

	.thumb_func
	.thumb
	.global sub_080881A8
sub_080881A8:
	movs r0, r0
	movs r0, r0
	ldr r3, sub_080882FC
	adds r2, #48
	movs r5, #95
	adds r2, #48
	cmp r6, #100
	strh r4, [r2, r5]
	lsls r3, r0, #1
	movs r0, r0
	ldr r3, _0808830C
	adds r2, #48
	strb r6, [r5, r0]
	ldr r4, _080882D0
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r1]
	ldrsh r5, [r1, r5]
	.global _080881CC
_080881CC:
	.4byte 0x33304B53
	.4byte 0x00000000
	.4byte 0x2E52414D
	.4byte 0x0050464E
	.4byte 0x33304B53
	.4byte 0x4743542E
	.4byte 0x00000000
	.4byte 0x33304B53
	.4byte 0x3230255F
	.4byte 0x53542E64
	.4byte 0x00000043
	.4byte 0x33304B53
	.4byte 0x4C43542E
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x32304E53
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x38304E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x34304E53
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x37304E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x35304E53
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x38304E45
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x30314E45
	.4byte 0x00000000
	.4byte 0x2E52414D
	.4byte 0x0050464E
	.4byte 0x36304E53
	.4byte 0x4743542E
	.4byte 0x00000000
	.4byte 0x36304E53
	.4byte 0x4353542E
	.4byte 0x00000000
	.4byte 0x36304E53
	.4byte 0x4C43542E
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x36304E53
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x32314E45
	.4byte 0x00000000
	.4byte 0x304E5353
	.4byte 0x43542E37
	.4byte 0x00000047
	.4byte 0x37304E53
	.4byte 0x4743542E
	.4byte 0x00000000
	.4byte 0x304E5353
	.4byte 0x2E425F37
	.4byte 0x00435354
	.4byte 0x304E5353
	.4byte 0x2E415F37
	.4byte 0x00435354
	.4byte 0x37304E53
	.global _080882D0
_080882D0:
	.4byte 0x542E425F
	.4byte 0x00004353
	.4byte 0x37304E53
	.4byte 0x542E415F
	.4byte 0x00004353
	.4byte 0x304E5353
	.4byte 0x43542E37
	.4byte 0x0000004C
	.4byte 0x37304E53
	.4byte 0x4C43542E
	.4byte 0x00000000

	.thumb_func
	.thumb
	.global sub_080882FC
sub_080882FC:
	.4byte 0x5F4D5241

	.thumb_func
	.thumb
	.global sub_08088300
sub_08088300:
	ldr r6, _08088450
	adds r7, #48
	movs r0, r0
	movs r0, r0
	adcs r5, r1
	cmp r6, #82
	.global _0808830C
_0808830C:
	.4byte 0x0050464E
	.4byte 0x5F4D5241
	.4byte 0x64255455
	.4byte 0x00006425
	.4byte 0x5F4D5241
	.4byte 0x31304557
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x37304E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x34304557
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x36304E45
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x37304E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x35304557
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x31304557
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x39304557
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x36304E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x31314557
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x30314557
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x34304E45
	.4byte 0x00000000
	.4byte 0xC18FCD82
	.4byte 0xC482A682
	.4byte 0xDC82B582
	.4byte 0xDC82A282
	.4byte 0x4081B782
	.4byte 0xEB82E682
	.4byte 0xA282B582
	.4byte 0xB782C582
	.4byte 0x4881A982
	.4byte 0x00000000
	.4byte 0x67835883
	.4byte 0x8A835B81
	.4byte 0x82835B81
	.4byte 0x68835B81
	.4byte 0xC48DF082
	.4byte 0xB7824A8A
	.4byte 0xC682E982
	.4byte 0x5B815A83
	.4byte 0x66837583
	.4byte 0x5E835B81
	.4byte 0x00000000
	.4byte 0x93835F83
	.4byte 0x87835783
	.4byte 0x54929383
	.4byte 0x8692F58D
	.4byte 0x5A83CC82
	.4byte 0x75835B81
	.4byte 0x5B816683
	.4byte 0xAA825E83
	.4byte 0xE882A082
	.4byte 0xB782DC82
	.4byte 0x00000000
	.4byte 0x00000042
	.4byte 0x54545F54
	.4byte 0x2E36304C
	.4byte 0x00504D4B
	.4byte 0x4C4D5F54
	.4byte 0x2E47425F
	.4byte 0x00504D4B
	.4byte 0x54545F54
	.4byte 0x0035304C
	.global _08088450
_08088450:
	.4byte 0x30303054
	.4byte 0x30432030
	.4byte 0x20343046
	.4byte 0x00007325

@ 088460..0885B0 is decompiled as MenuTextConstants(); see src/decompiled.json

	.section .rom.000885B0, "ax"
	.syntax unified
	.4byte 0x00005882
	.4byte 0x00005782
	.4byte 0x00005682
	.4byte 0x00005582
	.4byte 0x00005482
	.4byte 0x00005382
	.4byte 0x00005282
	.4byte 0x00005182
	.4byte 0x00005082
	.4byte 0x00004F82
	.4byte 0xE08BA492
	.4byte 0x0000748E
	.4byte 0x43834183
	.4byte 0x80836583
	.4byte 0x0000AE89
	.4byte 0x718256F0
	.4byte 0xAE896C82
	.4byte 0x00000000
	.4byte 0xE08BA492
	.4byte 0xB396CD82
	.4byte 0xC5829D97
	.4byte 0xCC82B782
	.4byte 0x0000F182
	.4byte 0xF182A982
	.4byte 0xAB82D882
	.4byte 0xB782C582
	.4byte 0xF182CC82
	.4byte 0xAB824181
	.4byte 0xC682C182
	.4byte 0x00000000
	.4byte 0xAB82C582
	.4byte 0xB582DC82
	.4byte 0xCC82BD82
	.4byte 0xF1825B81
	.4byte 0x00004981
	.4byte 0xE8828494
	.4byte 0xB582DC82
	.4byte 0x4281BD82
	.4byte 0x00000000
	.4byte 0x0000F082
	.4byte 0xE08BA492
	.4byte 0xBF97DE8D
	.4byte 0xED82AA82
	.4byte 0xE882A982
	.4byte 0xB582DC82
	.4byte 0xCC82BD82
	.4byte 0x4981F182
	.4byte 0x00000000
	.4byte 0x0000CC82
	.4byte 0xBF97DE8D
	.4byte 0xAB91AA82
	.4byte 0xC882E882
	.4byte 0xC582A282
	.4byte 0xCC82B782
	.4byte 0x0000F182
	.4byte 0xE08BA492
	.4byte 0xE982B782
	.4byte 0xB782C582
	.4byte 0xF182CC82
	.4byte 0x00004881
	.4byte 0xEA82B182
	.4byte 0xAF82BE82
	.4byte 0xDE8DCC82
	.4byte 0xAA82BF97
	.4byte 0xE982A282
	.4byte 0xF182CC82
	.4byte 0x00000000
	.4byte 0xA482C782
	.4byte 0xA282BE82
	.4byte 0x00004881
	.4byte 0xC5826F82
	.4byte 0xA2828394
	.4byte 0xE882C682
	.4byte 0xB782DC82
	.4byte 0x00004281
	.4byte 0xEA82B182
	.4byte 0xE38FC888
	.4byte 0xBF82E082
	.4byte 0xEA82AB82
	.4byte 0xB982DC82
	.4byte 0x0000F182
	.4byte 0x85837383
	.4byte 0x5E837C81
	.4byte 0xAA825B81
	.4byte 0xE882BD82
	.4byte 0xB982DC82
	.4byte 0x0000F182
	.4byte 0xA2828394
	.4byte 0xB582DC82
	.4byte 0x4281BD82
	.4byte 0x00000000
	.4byte 0xC9826F82
	.4byte 0xE882C882
	.4byte 0xB782DC82
	.4byte 0x00004281
	.4byte 0x67835883
	.4byte 0x4E836283
	.4byte 0x00000000
	.4byte 0xB182C782
	.4byte 0xE782A982
	.4byte 0xE882E68E
	.4byte 0xB782DC82
	.4byte 0x4881A982
	.4byte 0x00000000
	.4byte 0xA6829D91
	.4byte 0xB582DC82
	.4byte 0x4281BD82
	.4byte 0x00000000
	.4byte 0xE48C6896
	.4byte 0xAA82CD97
	.4byte 0x00000000
	.4byte 0x828C558D
	.4byte 0xAA82CD97
	.4byte 0x00000000
	.4byte 0xCD978296
	.4byte 0x0000AA82
	.4byte 0xCD97CC91
	.4byte 0x0000AA82
	.4byte 0x93835F83
	.4byte 0x87835783
	.4byte 0x82839383
	.4byte 0x68835B81
	.4byte 0xCD82C582
	.4byte 0x7097678E
	.4byte 0xAB82C582
	.4byte 0xB982DC82
	.4byte 0x0000F182
	.4byte 0xEA82BB82
	.4byte 0x678ECD82
	.4byte 0xC5827097
	.4byte 0xDC82AB82
	.4byte 0xF182B982
	.4byte 0x00000000
	.4byte 0xEA82BE82
	.4byte 0xC282C982
	.4byte 0xA482A982
	.4byte 0x00004881
	.4byte 0x00000000
	.4byte 0x2E52414D
	.4byte 0x0050464E
	.4byte 0x2E41574D
	.4byte 0x00504D4B
	.4byte 0x425F4441
	.4byte 0x2E323047
	.4byte 0x00504D4B
	.4byte 0xE082BD89
	.4byte 0xE882A082
	.4byte 0xB982DC82
	.4byte 0x4281F182
	.4byte 0x00000000
	.4byte 0x4D465741
	.4byte 0x32302543
	.4byte 0x00000064
	.4byte 0x30303054
	.4byte 0x30432030
	.4byte 0x20343046
	.4byte 0x20646D25
	.4byte 0x00007325
	.4byte 0x30303054
	.4byte 0x30432030
	.4byte 0x20343046
	.4byte 0x00007325
	.4byte 0x30303054
	.4byte 0x30432030
	.4byte 0x20343046
	.4byte 0x73257325
	.4byte 0x00000000
	.4byte 0x4E5F5053
	.4byte 0x00000042
	.4byte 0x4E4F4349
	.4byte 0x00000000
	.4byte 0xEA82BE82
	.4byte 0x6683CC82
	.4byte 0x4C836283
	.4byte 0xD682F082
	.4byte 0xB582F182
	.4byte 0xA482E382
	.4byte 0xDC82B582
	.4byte 0xA982B782
	.4byte 0x00004881
	.4byte 0x8A834E83
	.4byte 0xB7824183
	.4byte 0xC682E982
	.4byte 0xA682678E
	.4byte 0xE682E982
	.4byte 0xC982A482
	.4byte 0xE882C882
	.4byte 0xB782DC82
	.4byte 0x00004281
	.4byte 0x93835F83
	.4byte 0x87835783
	.4byte 0xE0939383
	.4byte 0xE88EC582
	.4byte 0xFC93C982
	.4byte 0xBD82EA82
	.4byte 0x718256F0
	.4byte 0xC5826C82
	.4byte 0x0000B782
	.4byte 0x5B817083
	.4byte 0x42836583
	.4byte 0xF0825B81
	.4byte 0xF182D682
	.4byte 0xA482B182
	.4byte 0xDC82B582
	.4byte 0x0000B782
	.4byte 0x718256F0
	.4byte 0xCC826C82
	.4byte 0x58838A83
	.4byte 0xF0826783
	.4byte 0xDC82DD82
	.4byte 0x0000B782
	.4byte 0x65835883
	.4byte 0x5E835B81
	.4byte 0xF0825883
	.4byte 0xDC82DD82
	.4byte 0x0000B782
	.4byte 0x43834183
	.4byte 0x80836583
	.4byte 0xC282F082
	.4byte 0xA282A982
	.4byte 0xB782DC82
	.4byte 0x00000000
	.4byte 0x718256F0
	.4byte 0xCC826C82
	.4byte 0x62836683
	.4byte 0xF0824C83
	.4byte 0xF182D682
	.4byte 0xE382B582
	.4byte 0xB582A482
	.4byte 0xB782DC82
	.4byte 0x00000000
	.4byte 0x53435F43
	.4byte 0x0000004C
	.4byte 0x425F4D43
	.4byte 0x2E313047
	.4byte 0x00504D4B
	.4byte 0x425F4D43
	.4byte 0x2E323047
	.byte 0x4B
	.byte 0x4D

	.thumb_func
	.thumb
	.global sub_0808896A
sub_0808896A:
	lsls r0, r2, #1
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70
	movs r4, r6
	ldr r5, _08088A88
	ldr r5, _08088AF8
	ldr r6, _08088A94
	lsls r5, r2, #1
	ldrsb r1, [r0, r5]
	ldr r5, _08088A9C
	lsls r3, r0, #1
	movs r0, r0
	ldr r5, _08088A98
	strh r7, [r3, r5]
	.2byte 0x4747
	adds r1, #48
	movs r0, r0
	movs r0, r0
	ldr r5, _08088AA4
	strh r7, [r3, r5]
	.2byte 0x4747
	adds r2, #48
	movs r0, r0
	movs r0, r0
	lsls r1, r0, #1
	movs r0, r0
	strb r3, [r0, #18]
	lsls r3, r0
	str r3, [sp, #524]
	str r3, [r0, #120]
	strh r3, [r0, #4]
	movs r0, r0
	sbcs r3, r0
	ldrh r3, [r0, #28]
	str r4, [sp, #524]
	cmp r3, r0
	ldr r3, [r0, r2]
	movs r0, r0
	ldr r3, [r0, #24]
	ldr r3, [r0, #24]
	ldrsb r3, [r0, r2]
	movs r0, r0
	ldr r3, [r0, #8]
	ldrh r3, [r0, #44]
	ldrsb r3, [r0, r2]
	ldrh r1, [r0, r6]
	movs r0, r0
	movs r0, r0
	.2byte 0x4783
	ldr r3, [r0, #8]
	ldrh r3, [r0, #60]
	ldrh r1, [r0, r6]
	ldr r3, [r0, #8]
	movs r0, r0
	ldr r3, [r0, r2]
	ldr r3, [r0, #88]
	cmp r11, r0
	movs r0, r0
	ldrsb r3, [r0, r6]
	strh r3, [r0, #28]
	str r3, [r0, #40]
	ldr r6, _08088BF8
	movs r0, r0
	movs r0, r0
	ldr r5, _08088C00
	str r3, [sp, #524]
	ldrsh r3, [r0, r2]
	movs r0, r0
	adds r0, #48
	adds r0, #48
	adds r0, #48
	adds r0, #48
	movs r0, r0
	movs r0, r0
	movs r1, r7
	movs r0, r0
	movs r0, r7
	movs r0, r0
	movs r7, r6
	movs r0, r0
	movs r6, r6
	movs r0, r0
	movs r5, r6
	movs r0, r0
	movs r4, r6
	movs r0, r0
	movs r3, r6
	movs r0, r0
	movs r2, r6
	movs r0, r0
	movs r1, r6
	movs r0, r0
	movs r0, r6
	movs r0, r0
	adds r7, #71
	subs r6, #65
	.2byte 0x474A
	ldr r0, _08088B98
	movs r0, r0
	movs r0, r0
	ldr r3, [r2, r5]
	ldrsh r3, [r2, r5]
	strb r2, [r0, r1]
	lsls r6, r1, #1
	ldrsh r4, [r0, r5]

	.thumb_func
	.thumb
	.global sub_08088A42
sub_08088A42:
	ldr r0, _08088B50
	movs r0, r0
	movs r0, r0
	ldr r6, _08088B9C
	lsls r7, r3, #1
	muls r1, r1
	ldr r6, _08088B8C
	ldr r1, _08088B88
	ldr r1, _08088B8C
	movs r0, r0
	movs r0, r0
	add r1, r8
	ldr r6, _08088BD8
	strh r2, [r0, r5]
	movs r0, r0
	ldr r4, _08088B70
	add r7, r11
	movs r0, r0
	movs r0, r0
	add r1, r8
	negs r7, r3
	adds r0, #71
	cmp r6, #49
	ldr r5, _08088BA0
	lsls r0, r2, #1
	strh r1, [r0, r1]
	lsls r5, r1, #1
	muls r1, r1
	ldr r6, _08088BB8
	movs r0, r0
	movs r0, r0
	strh r1, [r2, r6]
	stmia r4!, {r1, r7}
	add r1, sp, #568
	add r2, sp, #596
	.global _08088A88
_08088A88:
	.4byte 0x6683CC82
	.4byte 0x4C836283
	.4byte 0x9D8EC982
	.global _08088A94
_08088A94:
	.4byte 0xC482C182
	.global _08088A98
_08088A98:
	.4byte 0xDC82A282
	.global _08088A9C
_08088A9C:
	.4byte 0x0000B782
	.4byte 0x62836683
	.global _08088AA4
_08088AA4:
	.4byte 0xC9824C83
	.4byte 0xAB82F38B
	.4byte 0xA082AA82
	.4byte 0xDC82E882
	.4byte 0xF182B982
	.4byte 0x00000000

	.thumb_func
	.thumb
	.global sub_08088ABC
sub_08088ABC:
	strh r6, [r2, #20]
	ldmia r5!, {r0, r1, r2, r4, r7}
	add r2, sp, #520
	pop {r1, r7, pc}
	.4byte 0xDC82E882
	.4byte 0xF182B982
	.4byte 0x00000000
	.4byte 0xE891E296
	.4byte 0xB582C882
	.4byte 0x00000000

	.thumb_func
	.thumb
	.global sub_08088ADC
sub_08088ADC:
	strh r1, [r0, r5]
	negs r7, r3
	adds r0, #71
	cmp r6, #50
	ldr r5, _08088C14
	lsls r0, r2, #1
	ldr r3, [r2, r5]
	ldrsh r3, [r2, r5]
	strb r2, [r0, r1]
	lsls r6, r1, #1
	muls r1, r1
	ldr r6, _08088C30
	ldr r1, _08088C2C
	ldr r1, _08088C30
	.global _08088AF8
_08088AF8:
	.4byte 0x00000000
	add r1, r8
	ldr r6, _08088C7C
	strh r2, [r0, r5]
	movs r0, r0
	ldr r5, _08088C14
	ldr r6, _08088C84
	lsls r1, r0, #1
	movs r0, r0
	ldr r5, _08088C1C
	ldr r6, _08088C8C
	lsls r2, r0, #1
	movs r0, r0
	ldr r4, _08088C24
	add r7, r11
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r5]
	muls r7, r3
	ldr r4, _08088C70
	movs r0, r0
	ldr r6, _08088C78
	lsls r7, r3, #1
	strh r1, [r0, r5]
	add r7, r11
	ldr r6, _08088C54
	adcs r7, r3
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r5]
	negs r7, r3
	adds r0, #71
	cmp r6, #49
	ldr r5, _08088C6C
	lsls r0, r2, #1
	strh r1, [r0, r1]
	lsls r5, r1, #1
	muls r1, r1
	ldr r6, _08088C84
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r5]
	negs r7, r3
	.global _08088B50
_08088B50:
	.4byte 0x00313058
	ldrsb r1, [r0, r5]
	ldrsh r6, [r0, r5]
	movs r0, r0
	movs r0, r0
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70
	movs r4, r6
	strb r1, [r1, r1]
	negs r7, r3
	adds r0, #71
	cmp r6, #50
	.global _08088B70
_08088B70:
	.4byte 0x00504D4B
	strb r1, [r1, r1]
	ldrsb r7, [r3, r5]

	.thumb_func
	.thumb
	.global sub_08088B78
sub_08088B78:
	ldr r6, _08088CA0
	lsls r5, r1, #1
	ldrsh r3, [r0, r5]
	strh r3, [r0, r5]
	lsls r4, r1, #1
	movs r0, r0
	strb r1, [r1, r1]
	negs r7, r3
	.global _08088B88
_08088B88:
	.4byte 0x2E313047
	.global _08088B8C
_08088B8C:
	.4byte 0x00504D4B
	ldrsb r1, [r0, r5]
	ldr r5, _08088CAC
	lsls r3, r0, #1
	movs r0, r0
	.global _08088B98
_08088B98:
	.4byte 0x535F4D43
	.global _08088B9C
_08088B9C:
	.4byte 0x31304747
	.global _08088BA0
_08088BA0:
	.4byte 0x00000000
	ldr r5, _08088CB4
	strh r7, [r3, r5]
	.2byte 0x4747
	adds r2, #48
	movs r0, r0
	movs r0, r0
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	.global _08088BB8
_08088BB8:
	.4byte 0x20343046
	strb r5, [r4, #12]
	movs r0, r0
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70
	movs r0, #52
	strb r5, [r4, #12]
	movs r0, #32
	ldr r5, [r4, #80]
	movs r0, #100
	movs r5, #32
	lsls r3, r6, #1
	.global _08088BD8
_08088BD8:
	.4byte 0x575F5350
	adds r0, #75
	movs r2, r6
	ldr r3, [r2, r5]
	ldrsh r3, [r2, r5]
	strb r2, [r0, r1]
	lsls r6, r1, #1
	ldr r5, _08088CF8
	strh r7, [r3, r5]
	.2byte 0x4747
	adds r1, #48
	movs r0, r0
	movs r0, r0
	ldr r5, _08088D04
	strh r7, [r3, r5]
	.global _08088BF8
_08088BF8:
	.4byte 0x32304747
	movs r0, r0
	movs r0, r0
	.global _08088C00
_08088C00:
	.4byte 0x00000041
	lsls r2, r0, #1
	movs r0, r0
	strh r4, [r0, r5]
	negs r7, r3
	adds r0, #71
	cmp r6, #49
	ldr r5, _08088D40
	lsls r0, r2, #1
	.global _08088C14
_08088C14:
	.4byte 0x42465741
	.4byte 0x0000005F
	.global _08088C1C
_08088C1C:
	.4byte 0x5F465741
	.4byte 0x00000000
	.global _08088C24
_08088C24:
	.4byte 0x48435F44
	.4byte 0x00003939
	.global _08088C2C
_08088C2C:
	.4byte 0x48435F44
	.global _08088C30
_08088C30:
	.4byte 0x00000000
	.4byte 0x005F4E54
	.4byte 0x42465741
	.4byte 0x0039395F
	.4byte 0x42465741
	.4byte 0x0031305F
	.4byte 0x5F465741
	.4byte 0x00003939
	.byte 0x41
	.byte 0x57

	.thumb_func
	.thumb
	.global sub_08088C52
sub_08088C52:
	ldrsh r6, [r0, r5]
	.global _08088C54
_08088C54:
	.4byte 0x00003130
	.4byte 0x425F5453
	.4byte 0x2E313047
	.4byte 0x00504D4B
	.4byte 0x425F5453
	.4byte 0x2E323047
	.global _08088C6C
_08088C6C:
	.4byte 0x00504D4B
	.global _08088C70
_08088C70:
	.2byte 0x4349

	.thumb_func
	.thumb
	.global sub_08088C72
sub_08088C72:
	ldr r6, _08088DB0
	ldr r1, _08088DAC
	ldr r1, _08088DB0
	.global _08088C78
_08088C78:
	.4byte 0x00000000
	.global _08088C7C
_08088C7C:
	.4byte 0x535F5453
	.4byte 0x31304747
	.global _08088C84
_08088C84:
	.4byte 0x00000000
	.4byte 0x535F5453
	.global _08088C8C
_08088C8C:
	.4byte 0x34304747
	.4byte 0x00000000
	.4byte 0x48435F44
	.4byte 0x00000000
	.4byte 0x005F4E54
	.global _08088CA0
_08088CA0:
	.4byte 0x425F5453
	.4byte 0x2E333047
	.global _08088CA8
_08088CA8:
	.4byte 0x00504D4B
	.global _08088CAC
_08088CAC:
	.4byte 0x004D5241
	.4byte 0x5F535953
	.global _08088CB4
_08088CB4:
	.4byte 0x004E5442
	.4byte 0x4E4F4349
	.global _08088CBC
_08088CBC:
	.4byte 0x494E494D
	.4byte 0x00000000
	.4byte 0x4E5F4441
	.4byte 0x00005342
	.4byte 0x525F4C41
	.4byte 0x00000057
	.4byte 0x4C415F54
	.4byte 0x00000054
	.4byte 0x534D5F54
	.4byte 0x0000004C
	.4byte 0x425F4C41
	.4byte 0x2E313047
	.4byte 0x00504D4B
	.4byte 0x425F4C4D
	.4byte 0x2E313047
	.global _08088CF8
_08088CF8:
	.4byte 0x00504D4B
	.4byte 0x425F4C41
	.4byte 0x2E323047
	.global _08088D04
_08088D04:
	.4byte 0x00504D4B
	.4byte 0x40814081
	.4byte 0x00000000
	.4byte 0x7C817C81
	.4byte 0x7C817C81
	.4byte 0x00000000
	.4byte 0x004D5241
	.4byte 0x445F4C43
	.4byte 0x00000000
	.4byte 0x4E4F4349
	.4byte 0x00000000
	.4byte 0x30303054
	.4byte 0x30432030
	.4byte 0x00343046
	.4byte 0x5F535953
	.global _08088D40
_08088D40:
	.4byte 0x004E5442
	.4byte 0x4E5F4441
	.4byte 0x00005342
	.4byte 0x4E5F4D43
	.4byte 0x00000041
	.4byte 0x4E5F4D43
	.4byte 0x00000042
	.4byte 0x425F5053
	.global _08088D60
_08088D60:
	adds r1, #71
	cmp r6, #49
	ldr r5, _08088E94
	lsls r0, r2, #1
	str r3, [r2, r1]
	negs r7, r3
	adds r1, #71
	cmp r6, #50
	ldr r5, _08088EA0
	lsls r0, r2, #1
	strh r1, [r0, r1]
	movs r5, #77
	adds r3, #48
	lsls r4, r4, #1
	ldr r4, _08088E8C
	add r7, r11
	movs r0, r0
	movs r0, r0
	muls r1, r1
	ldr r6, _08088EC4
	movs r0, r0
	movs r0, r0
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70
	movs r0, #52
	strb r5, [r4, #12]
	movs r0, r0
	ldr r7, _08088EE0
	lsls r0, r2, #1
	ldrsh r3, [r0, r5]
	strh r3, [r0, r5]
	lsls r4, r1, #1
	movs r0, r0
	strh r1, [r0, r5]
	negs r7, r3
	.global _08088DAC
_08088DAC:
	.4byte 0x2E323047
	.global _08088DB0
_08088DB0:
	.4byte 0x00504D4B
	ldrsh r4, [r2, r5]
	strh r1, [r1, r5]
	lsls r0, r2, #1
	movs r0, r0
	muls r1, r1
	ldr r6, _08088EFC
	ldr r1, _08088EF8

	.thumb_func
	.thumb
	.global sub_08088DC2
sub_08088DC2:
	ldr r1, _08088EFC
	movs r0, r0
	movs r0, r0
	add r1, r8
	ldr r6, _08088F48
	strh r2, [r0, r5]
	movs r0, r0
	ldr r5, _08088EE0
	ldr r6, _08088F50
	lsls r1, r0, #1
	movs r0, r0
	ldr r5, _08088EE8
	ldr r6, _08088F58
	lsls r2, r0, #1
	movs r0, r0
	ldr r4, _08088EF0
	add r7, r11
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r5]
	muls r7, r3
	ldr r4, _08088F3C
	movs r0, r0
	str r3, [r2, r1]
	negs r7, r3
	adds r0, #71
	cmp r6, #49
	ldr r5, _08088F28
	lsls r0, r2, #1
	strh r1, [r0, r1]
	movs r5, #77
	adds r3, #48
	lsls r4, r4, #1
	muls r1, r1
	ldr r6, _08088F44
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r5]
	negs r7, r3
	adds r0, #88
	movs r1, r6
	ldrsb r1, [r0, r5]
	ldrsh r6, [r0, r5]
	movs r0, r0
	movs r0, r0
	add r1, r8
	ldr r6, _08088F9C
	strh r2, [r0, r5]
	movs r0, r0
	ldr r5, _08088F34
	ldr r6, _08088FA4
	lsls r2, r0, #1
	movs r0, r0
	str r3, [r2, r1]
	negs r7, r3

	.thumb_func
	.thumb
	.global sub_08088E30
sub_08088E30:
	adds r2, #71
	cmp r6, #50
	ldr r5, _08088F64
	lsls r0, r2, #1
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70
	movs r0, #52
	strb r5, [r4, #12]
	movs r0, r0
	ldrsh r4, [r2, r5]
	strh r1, [r0, r5]

	.thumb_func
	.thumb
	.global sub_08088E4C
sub_08088E4C:
	lsls r0, r2, #1
	movs r0, r0
	str r3, [r2, r1]
	negs r7, r3
	adds r2, #71
	cmp r6, #49
	ldr r5, _08088F88
	lsls r0, r2, #1
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70
	movs r0, #52
	strb r5, [r4, #12]
	movs r0, r0
	pop {r0, r3, r7, pc}
	.byte 0x82
	.byte 0xE0
	.4byte 0xE882A082
	.4byte 0xB982DC82
	.4byte 0x4281F182

	.thumb_func
	.thumb
	.global sub_08088E7C
sub_08088E7C:
	movs r0, r0
	movs r0, r0
	ldr r3, [r2, r5]
	ldrsh r3, [r2, r5]
	strb r2, [r0, r1]
	lsls r6, r1, #1
	ldrsb r0, [r2, r5]
	ldr r6, _08089008
	.global _08088E8C
_08088E8C:
	.4byte 0x00000042
	.4byte 0x4E5F5750
	.global _08088E94
_08088E94:
	.4byte 0x00313042
	.4byte 0x425F5750
	.4byte 0x2E313047
	.global _08088EA0
_08088EA0:
	.4byte 0x00504D4B
	.4byte 0x425F5750
	.4byte 0x4B2E584F
	.4byte 0x0000504D
	.4byte 0x435F5750
	.4byte 0x00004C53
	.4byte 0x5F535953
	.4byte 0x004E5442
	.byte 0x49
	.byte 0x43

	.thumb_func
	.thumb
	.global sub_08088EC2
sub_08088EC2:
	ldr r6, _08089000
	.global _08088EC4
_08088EC4:
	.4byte 0x494E494D
	.4byte 0x00000000
	.4byte 0x4E5F4441
	.4byte 0x00005342
	.4byte 0x4E5F4D43
	.4byte 0x00000041
	.4byte 0x4E5F4D43
	.global _08088EE0
_08088EE0:
	.4byte 0x00000042
	.4byte 0x425F4D53
	.global _08088EE8
_08088EE8:
	.4byte 0x00323147
	.4byte 0x53435F43
	.global _08088EF0
_08088EF0:
	.4byte 0x0000004C
	.4byte 0x425F4D53
	.global _08088EF8
_08088EF8:
	.4byte 0x2E313047
	.global _08088EFC
_08088EFC:
	.4byte 0x00504D4B
	.4byte 0x425F5053
	.global _08088F04
_08088F04:
	adds r1, #71
	cmp r6, #50
	ldr r5, _08089038
	lsls r0, r2, #1
	strh r1, [r0, r1]
	movs r5, #77
	adds r3, #48
	lsls r4, r4, #1
	ldr r4, _08089024
	add r7, r11
	movs r0, r0
	movs r0, r0
	ldr r3, [r2, r5]
	ldrsh r3, [r2, r5]
	strb r2, [r0, r1]
	lsls r6, r1, #1
	strh r4, [r0, r5]
	muls r7, r3
	.global _08088F28
_08088F28:
	.4byte 0x00004C53
	.4byte 0x445F5344
	.byte 0x52
	.byte 0x00
	.global _08088F32
_08088F32:
	movs r0, r0
	.global _08088F34
_08088F34:
	.4byte 0x425F5344
	.byte 0x47
	.byte 0x30
	.global _08088F3A
_08088F3A:
	cmp r6, #49
	.global _08088F3C
_08088F3C:
	.4byte 0x00504D4B
	.4byte 0x425F5344
	.global _08088F44
_08088F44:
	.4byte 0x2E323047
	.global _08088F48
_08088F48:
	.4byte 0x00504D4B
	.4byte 0x425F5344
	.global _08088F50
_08088F50:
	.4byte 0x00303247
	.4byte 0x475F5344
	.global _08088F58
_08088F58:
	.4byte 0x0031304E
	.4byte 0x00000041
	.4byte 0x00000042
	.global _08088F64
_08088F64:
	.4byte 0x4E4F4349
	.4byte 0x494E494D
	.4byte 0x00000000
	.4byte 0x5F535953
	.4byte 0x004E5442
	.4byte 0x4E5F4D43
	.4byte 0x00000041
	.4byte 0x425F4147
	.4byte 0x2E313047
	.global _08088F88
_08088F88:
	.4byte 0x00504D4B
	.4byte 0x254D5241
	.4byte 0x00643330
	.4byte 0x4E4F4349
	.4byte 0x00000000
	.global _08088F9C
_08088F9C:
	.4byte 0x43835E83
	.4byte 0x41838083
	.global _08088FA4
_08088FA4:
	.4byte 0x67834583
	.4byte 0xDC82B582
	.4byte 0xBD82B582
	.4byte 0x00000000
	.4byte 0x5B815083
	.4byte 0x8B837583
	.4byte 0xCA82F082
	.4byte 0xC882A982
	.4byte 0xC582A282
	.4byte 0xB382BA89
	.4byte 0x0000A282
	.4byte 0xA482C282
	.4byte 0xF182B582
	.4byte 0xC5828692
	.4byte 0x4281B782
	.4byte 0x00000000
	.byte 0x82
	.byte 0x61
	.global _08088FE6
_08088FE6:
	ldrb r3, [r0, #14]
	ldrsh r3, [r0, r2]
	str r3, [sp, #524]
	stmia r5!, {r1, r7}
	.inst.n 0x4C83  @ ldr r4, _080891FC
	strh r3, [r0, #28]
	str r3, [sp, #524]
	ldrh r3, [r0, r2]
	ldrh r3, [r0, #28]
	stmia r5!, {r1, r7}
	add r3, sp, #520
	bgt _08088F04
	.global _08088FFE
_08088FFE:
	.2byte 0xB782
	.global _08089000
_08089000:
	.4byte 0x00004281
	str r2, [r0, #8]
	ldrb r3, [r0, #14]
	.global _08089008
_08089008:
	.4byte 0x93835E83
	.2byte 0xF082
	add r0, sp, #520
	push {r1, r7, lr}
	stmia r4!, {r1, r7}
	add r5, sp, #520
	.2byte 0xBE82
	.2byte 0xB382
	.inst.n 0xA282  @ adr r2, _08089224
	movs r0, r0
	movs r0, r0
	stmia r2!, {r1, r7}
	.inst.n 0xA482  @ adr r4, _0808922C
	.global _08089024
_08089024:
	.4byte 0xF182B582
	.2byte 0xF082
	bgt _08088F32
	stmia r1!, {r1, r7}
	stmia r4!, {r1, r7}
	.inst.n 0xA282  @ adr r2, _0808923C
	bgt _08088F3A
	.2byte 0xB782
	cmp r1, r0
	.global _08089038
_08089038:
	.4byte 0x00000000
	.2byte 0xF38E
	add r7, sp, #520
	b _08088D60
	.byte 0x82
	.byte 0xE8
	.4byte 0xAA82A491
	.4byte 0xBF829D8E
	.4byte 0xEA82AB82
	.4byte 0xB982DC82
	.4byte 0x4281F182
	.4byte 0x00000000
	.4byte 0xBF829D8E
	.4byte 0xEA82AB82
	.4byte 0xB982DC82
	.4byte 0x4281F182
	.4byte 0x00000000
	.4byte 0xA482B182
	.4byte 0xF182A982
	.4byte 0xB191F082
	.4byte 0xDC82AF82
	.4byte 0xA982B782
	.4byte 0x00004881
	.4byte 0xA482C282
	.4byte 0xF182B582
	.4byte 0xB88EC982
	.4byte 0xB5827394
	.4byte 0xB582DC82
	.4byte 0x4281BD82
	.4byte 0x00000000
	.4byte 0xAD82A882
	.4byte 0xEA82E782
	.4byte 0xAB82C482
	.4byte 0xB582DC82
	.4byte 0x4281BD82
	.4byte 0x00000000
	.4byte 0x0000AA82
	.4byte 0xCD827581

	.thumb_func
	.thumb
	.global sub_080890C4
sub_080890C4:
	.2byte 0xB682
	swi #130
	.2byte 0xE982
	strb r1, [r0, #26]
	stmia r5!, {r1, r7}
	stmia r2!, {r1, r7}
	.inst.n 0xA482  @ adr r4, _080892DC

	.thumb_func
	.thumb
	.global sub_080890D2
sub_080890D2:
	push {r1, r7, lr}
	.2byte 0xF182
	.2byte 0xF082
	ldmia r5!, {r1, r7}
	.2byte 0xB682
	swi #130
	bgt _08088FE6
	.2byte 0xB782

	.thumb_func
	.thumb
	.global sub_080890E2
sub_080890E2:
	cmp r1, r0
	movs r0, r0
	movs r0, r0
	.2byte 0xB182
	.inst.n 0xA482  @ adr r4, _080892F4
	add r1, sp, #520
	.2byte 0xF182
	.inst.n 0xC982  @ ldmia r1!, {r1, r7}
	ldr r7, [r1, #120]
	push {r1, r7, lr}
	bgt _08088FFE
	.2byte 0xB782
	sbcs r1, r0
	.global _080890FC
_080890FC:
	.2byte 0xB682

	.thumb_func
	.thumb
	.global sub_080890FE
sub_080890FE:
	b _08089806
	.4byte 0xD182F182
	.byte 0x82
	.byte 0xAA

	.thumb_func
	.thumb
	.global sub_08089106
sub_08089106:
	stmia r5!, {r1, r7}
	add r3, sp, #520

	.thumb_func
	.thumb
	.global sub_0808910A
sub_0808910A:
	pop {r1, r7, pc}
	.4byte 0x0000E782

	.thumb_func
	.thumb
	.global sub_08089110
sub_08089110:
	.2byte 0xF082

	.thumb_func
	.thumb
	.global sub_08089112
sub_08089112:
	movs r0, r0
	strh r1, [r0, r5]

	.thumb_func
	.thumb
	.global sub_08089116
sub_08089116:
	negs r7, r3
	adds r0, #71
	cmp r6, #50
	.inst.n 0x4D4B  @ ldr r5, _0808924C
	lsls r0, r2, #1
	ldr r3, [r2, r5]
	ldrsh r3, [r2, r5]
	strb r2, [r0, r1]
	lsls r6, r1, #1
	muls r1, r1
	.inst.n 0x4E4F  @ ldr r6, _08089268
	.inst.n 0x494D  @ ldr r1, _08089264
	.inst.n 0x494E  @ ldr r1, _08089268
	movs r0, r0
	movs r0, r0
	.inst.n 0x4D43  @ ldr r5, _08089244
	.inst.n 0x4E5F  @ ldr r6, _080892B4
	lsls r1, r0, #1
	movs r0, r0
	.inst.n 0x4C43  @ ldr r4, _0808924C
	add r7, r11
	movs r0, r0
	movs r0, r0
	add r1, r8
	.inst.n 0x4E5F  @ ldr r6, _080892C4
	strh r2, [r0, r5]
	movs r0, r0
	strh r1, [r0, r5]
	muls r7, r3

	.thumb_func
	.thumb
	.global sub_08089150
sub_08089150:
	.inst.n 0x4C53  @ ldr r4, _080892A0
	movs r0, r0
	strh r1, [r0, r1]
	movs r5, #77
	adds r3, #48
	lsls r4, r4, #1
	adcs r7, r0
	negs r7, r3
	adds r0, #71
	cmp r6, #49
	.inst.n 0x4D4B  @ ldr r5, _08089294
	lsls r0, r2, #1
	muls r1, r1
	.inst.n 0x4E4F  @ ldr r6, _080892A8
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r5]
	negs r7, r3
	adds r0, #88
	movs r1, r6
	ldrsb r1, [r0, r5]
	ldrsh r6, [r0, r5]
	movs r0, r0
	movs r0, r0
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70
	movs r0, #52
	strb r5, [r4, #12]
	movs r5, #32
	lsls r3, r6, #1
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_08089194
sub_08089194:
	adds r0, #84
	adds r0, #48
	movs r0, #48
	adds r0, #67
	adds r0, #70

	.thumb_func
	.thumb
	.global sub_0808919E
sub_0808919E:
	movs r0, #52
	strb r5, [r4, #12]
	movs r0, r0
	adcs r5, r1
	ldrsh r2, [r2, r5]
	.inst.n 0x4953  @ ldr r1, _080892F8
	strb r7, [r1, r1]
	add r2, r10
	movs r0, r0
	ldrsh r4, [r2, r5]
	adds r0, #67
	cmp r6, #50
	.inst.n 0x4D4B  @ ldr r5, _080892E4
	lsls r0, r2, #1
	movs r0, r0
	ldrsh r4, [r2, r5]
	adds r0, #67
	cmp r6, #49
	.inst.n 0x4D4B  @ ldr r5, _080892F0
	lsls r0, r2, #1
	movs r0, r0
	str r4, [sp, #524]
	mov r11, r0
	ldr r3, [r0, r2]
	str r3, [r0, #120]
	ldrh r3, [r0, #20]
	movs r0, r0
	ldrh r3, [r0, #28]
	ldrb r3, [r0, #2]
	ldrh r3, [r0, #20]
	sbcs r3, r0
	ldmia r4!, {r1, r7}
	bmi _080890FC
	movs r0, r0
	movs r0, r0
	ldrb r3, [r0, #6]
	ldrh r3, [r0, #20]
	.inst.n 0x4A83  @ ldr r2, _080893F8
	movs r0, r0
	ldr r5, [r2, r2]
	ldmia r4!, {r1, r7}
	.2byte 0xE98F
	movs r0, r0
	strb r3, [r0, #2]
	str r3, [r0, #72]
	ldrsh r3, [r0, r2]
	cmp r11, r0
	.global _080891FC
_080891FC:
	.4byte 0x00009383
	ldrsb r3, [r0, r6]
	strh r3, [r0, #28]
	str r3, [r0, #40]
	.inst.n 0x4E83  @ ldr r6, _08089414
	ldmia r4!, {r1, r7}
	stmia r6!, {r0, r3, r7}
	movs r0, r0
	movs r0, r0
	ldr r3, [r0, #120]
	str r3, [r0, #40]
	ldrb r3, [r0, #14]
	.global _08089216
_08089216:
	ldmia r4!, {r1, r7}
	.inst.n 0xA282  @ adr r2, _08089424
	.2byte 0xB982
	add r3, sp, #520
	movs r0, r0
	ldrh r3, [r0, #12]
	str r3, [sp, #524]
	.global _08089224
_08089224:
	.4byte 0x80835F83
	movs r0, r0
	movs r0, r0
	.global _0808922C
_0808922C:
	.4byte 0xB48C9091
	movs r0, r0
	movs r0, r0
	ldrsb r3, [r0, r6]
	strh r3, [r0, #28]
	str r3, [r0, #40]
	.inst.n 0x4E83  @ ldr r6, _08089448
	.global _0808923C
_0808923C:
	.4byte 0xA894CC82
	movs r0, r0
	movs r0, r0
	.global _08089244
_08089244:
	.4byte 0x5F54454E
	adds r6, #50
	adcs r7, r3
	.global _0808924C
_0808924C:
	.4byte 0x00000000
	cmp r6, r9
	ldrsh r4, [r2, r5]
	adds r5, #50
	.global _08089256
_08089256:
	adcs r7, r3
	movs r0, r0
	movs r0, r0
	cmp r6, r9
	ldrsh r4, [r2, r5]
	adds r4, #50
	adcs r7, r3
	.global _08089264
_08089264:
	.4byte 0x00000000
	.global _08089268
_08089268:
	.4byte 0x5F54454E
	adds r7, #48
	adcs r7, r3
	movs r0, r0
	movs r0, r0
	cmp r6, r9
	ldrsh r4, [r2, r5]
	add r1, r8
	adcs r7, r3
	movs r0, r0
	movs r0, r0
	cmp r6, r9
	ldrsh r4, [r2, r5]
	adds r5, #48
	adcs r7, r3
	movs r0, r0
	movs r0, r0
	cmp r6, r9
	ldrsh r4, [r2, r5]
	adds r4, #48
	.global _08089292
_08089292:
	adcs r7, r3
	.global _08089294
_08089294:
	.4byte 0x00000000
	cmp r6, r9
	ldrsh r4, [r2, r5]
	adds r0, #48
	adcs r7, r3
	.global _080892A0
_080892A0:
	.4byte 0x00000000
	.global _080892A4
_080892A4:
	cmp r6, r9
	ldrsh r4, [r2, r5]
	.global _080892A8
_080892A8:
	.4byte 0x415F3330
	movs r0, r0
	movs r0, r0
	strh r6, [r2, r5]
	adcs r5, r1
	.global _080892B4
_080892B4:
	.4byte 0x00313050
	adcs r5, r1
	ldrsh r2, [r2, r5]
	.inst.n 0x4953  @ ldr r1, _0808940C
	.inst.n 0x4D4F  @ ldr r5, _080893FC
	str r1, [r0, r1]
	movs r0, r0
	.global _080892C4
_080892C4:
	.4byte 0x425F4D57
	adds r0, #71
	cmp r6, #49
	.inst.n 0x4D4B  @ ldr r5, _080893FC
	lsls r0, r2, #1
	.inst.n 0x4D57  @ ldr r5, _08089430
	negs r7, r3
	adds r0, #71
	cmp r6, #50
	.inst.n 0x4D4B  @ ldr r5, _08089408
	lsls r0, r2, #1
	.global _080892DC
_080892DC:
	.4byte 0x435F4D57
	.inst.n 0x4C53  @ ldr r4, _08089430
	movs r0, r0
	.global _080892E4
_080892E4:
	.4byte 0xF182CE82
	.byte 0x82
	.byte 0xB2

	.thumb_func
	.thumb
	.global sub_080892EA
sub_080892EA:
	.inst.n 0xA482  @ adr r4, _080894F4
	movs r0, r0
	movs r0, r0
	.global _080892F0
_080892F0:
	.4byte 0x58835283
	.global _080892F4
_080892F4:
	.4byte 0x00006783
	.global _080892F8
_080892F8:
	.4byte 0x89834E83
	.4byte 0x00005883
	.4byte 0xAD82BC82
	.4byte 0xA282B982
	.byte 0x00
	.byte 0x00

	.thumb_func
	.thumb
	.global sub_0808930A
sub_0808930A:
	movs r0, r0
	ldmia r0!, {r1, r7}
	bgt _08089216
	.inst.n 0xA682  @ adr r6, _0808951C
	movs r0, r0
	strb r3, [r2, r1]
	muls r7, r3
	.inst.n 0x4E4F  @ ldr r6, _08089458
	movs r0, r0
	strb r3, [r2, r1]
	negs r7, r3
	adds r1, #71
	cmp r6, #49
	.inst.n 0x4D4B  @ ldr r5, _08089454
	lsls r0, r2, #1
	adcs r5, r1
	.inst.n 0x4852  @ ldr r0, _08089474
	adcs r5, r0
	cmp r6, r10
	adds r0, #78
	adds r0, #48
	adds r0, #48
	movs r0, r6
	add r5, sp, #556
	.inst.n 0xA790  @ adr r7, _0808957C
	.inst.n 0x4993  @ ldr r1, _0808958C
	.inst.n 0xC982  @ ldmia r1!, {r1, r7}
	ldrsh r3, [r0, r2]
	bics r3, r0
	str r3, [r0, #120]
	ldrh r3, [r0, #28]
	.inst.n 0xC982  @ ldmia r1!, {r1, r7}
	swi #150
	.2byte 0xE882

	.thumb_func
	.thumb
	.global sub_0808934E
sub_0808934E:
	bgt _08089256
	.2byte 0xB782
	cmp r1, r0
	movs r0, r0
	movs r0, r0
	ldrsh r3, [r0, r6]
	str r3, [sp, #524]
	ldrsb r3, [r0, r6]
	strh r3, [r0, #60]
	str r3, [sp, #524]
	strh r3, [r0, #20]
	ldrh r1, [r0, r6]
	ldr r3, [r0, #8]
	stmia r5!, {r1, r7}
	ldmia r5!, {r1, r7}
	ldrh r3, [r0, r2]
	ldrh r1, [r0, r6]
	strb r3, [r0, #22]
	.2byte 0xF082
	.2byte 0xB782
	.2byte 0xE982
	stmia r6!, {r1, r7}
	movs r0, r0
	str r3, [r0, r6]
	ldrh r1, [r0, r6]
	strh r3, [r0, #4]
	.2byte 0xF082
	stmia r2!, {r1, r7}
	stmia r3!, {r1, r7}
	add r7, sp, #520
	bgt _08089292
	.2byte 0xB782
	add r1, sp, #520
	.inst.n 0x4881  @ ldr r0, _08089598
	movs r0, r0
	ldrh r3, [r0, r2]
	ldrh r1, [r0, r6]
	strb r3, [r0, #22]
	push {r1, r7, lr}
	bgt _080892A4
	push {r1, r7, lr}
	pop {r1, r7, pc}
	.byte 0x00
	.byte 0x00
	.4byte 0xF182C582
	.4byte 0xF182B082
	.4byte 0xAB82F082
	.4byte 0xC882E782
	.4byte 0xC582A282
	.4byte 0xBE82AD82
	.4byte 0xA282B382
	.4byte 0x00000000
	.4byte 0x5B815A83
	.4byte 0x86927583
	.4byte 0xB782C582
	.4byte 0x00000000
	.4byte 0x4F916981
	.4byte 0x6683CC82
	.4byte 0x5E835B81
	.4byte 0xE38FC982
	.4byte 0xAB82918F
	.4byte 0xDC82B582
	.4byte 0x6A81B782
	.4byte 0x00000000
	.4byte 0x5B815A83
	.global _080893F8
_080893F8:
	.4byte 0xB5827583
	.global _080893FC
_080893FC:
	.4byte 0xB782DC82
	.4byte 0x4881A982
	.4byte 0x00000000
	.global _08089408
_08089408:
	.4byte 0x30303054
	.global _0808940C
_0808940C:
	.4byte 0x30432030
	.4byte 0x20343046
	.global _08089414
_08089414:
	.4byte 0x00007325
	.4byte 0x00000041
	.4byte 0x00000042
	.4byte 0x4E5F504D
	.global _08089424
_08089424:
	.4byte 0x00454D41
	.4byte 0x46415453
	.4byte 0x00333046
	.global _08089430
_08089430:
	.4byte 0x46415453
	.4byte 0x00323046
	.4byte 0x46415453
	.global _0808943C
_0808943C:
	.4byte 0x00313046
	.4byte 0x46415453
	.4byte 0x00303046
	.global _08089448
_08089448:
	.4byte 0x305F504F
	.4byte 0x2E415F36
	.4byte 0x00504D4B
	.global _08089454
_08089454:
	.4byte 0x41504C43
	.global _08089458
_08089458:
	.4byte 0x4B2E5353
	.4byte 0x0000504D
	.4byte 0x504D4B2E
	.4byte 0x00000000
	.4byte 0x2E52414D
	.4byte 0x0050464E
	.4byte 0x0000555F
	.global _08089474
_08089474:
	.4byte 0x0000445F
	.4byte 0x414B4154
	.4byte 0x00004152
	.4byte 0x415F4441
	.4byte 0x4F5F4C4C
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x38304142
	.4byte 0x00000000
	.4byte 0x425F5053
	.4byte 0x00343041
	.4byte 0x5F4D5241
	.4byte 0x32304544
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x39304E45
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x31314147
	.4byte 0x00000000
	.4byte 0x5F4D5241
	.4byte 0x32314147
	.4byte 0x00000000
	.4byte 0x475F4645
	.4byte 0x32304E45
	.byte 0x00
	.byte 0x00

	.thumb_func
	.thumb
	.global sub_080894DA
sub_080894DA:
	movs r0, r0
	strh r1, [r0, r1]
	ldrsh r5, [r1, r5]
	cmp r6, r9
	adds r3, #50
	movs r0, r0
	movs r0, r0
	str r3, [r2, r1]
	negs r7, r3
	adds r0, #65
	movs r4, r6
	strh r1, [r0, r1]
	ldrsh r5, [r1, r5]
	.global _080894F4
_080894F4:
	.4byte 0x31304E53
	movs r0, r0
	movs r0, r0
	strh r1, [r0, r1]
	ldrsh r5, [r1, r5]
	.inst.n 0x4B53  @ ldr r3, _08089650
	adds r0, #48
	movs r0, r0
	movs r0, r0
	strb r2, [r0, r1]
	strh r7, [r3, r5]
	strb r5, [r0, r1]
	adds r1, #48
	movs r0, r0
	movs r0, r0
	adds r6, #55
	adds r0, #65
	ldrsh r3, [r6, r4]
	movs r0, r0
	.global _0808951C
_0808951C:
	.4byte 0x30413737
	ldrsh r3, [r6, r4]
	movs r0, r0
	str r3, [r2, r1]
	negs r7, r3

	.thumb_func
	.thumb
	.global sub_08089528
sub_08089528:
	adds r0, #65
	movs r4, r6
	cmp r4, r10
	strb r3, [r2, r1]
	cmp r7, r11
	adds r2, #48
	movs r0, r0
	movs r0, r0
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	strh r5, [r3, #16]
	lsrs r7, r0, #32
	strh r5, [r7, #16]
	lsrs r7, r0, #32

	.thumb_func
	.thumb
	.global sub_08089544
sub_08089544:
	strh r1, [r3, #18]
	lsrs r7, r0, #32
	strh r5, [r5, #18]
	lsrs r7, r0, #32
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	strh r5, [r5, #12]

	.thumb_func
	.thumb
	.global sub_08089552
sub_08089552:
	lsrs r7, r0, #32
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	strh r5, [r3, #20]
	lsrs r7, r0, #32
	strh r1, [r5, #20]
	lsrs r7, r0, #32
	strh r5, [r7, #20]
	lsrs r7, r0, #32
	strh r1, [r2, #22]
	lsrs r7, r0, #32
	strh r1, [r0, #24]
	lsrs r7, r0, #32
	strh r5, [r2, #24]
	lsrs r7, r0, #32
	strh r1, [r5, #24]
	lsrs r7, r0, #32
	strh r5, [r7, #24]
	lsrs r7, r0, #32
	.global _0808957C
_0808957C:
	.4byte 0x08078921  @ ROM+0x78921
	strh r1, [r2, #26]
	lsrs r7, r0, #32
	ldrh r5, [r6, #8]
	lsrs r7, r0, #32
	strh r5, [r3, #26]
	lsrs r7, r0, #32
	.global _0808958C
_0808958C:
	.4byte 0x080781AD  @ ROM+0x781AD
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	strh r5, [r6, #26]
	lsrs r7, r0, #32
	.global _08089598
_08089598:
	.4byte 0x080781AD  @ ROM+0x781AD
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	strh r1, [r1, #28]
	lsrs r7, r0, #32
	strh r5, [r5, #12]
	lsrs r7, r0, #32
	ldrh r1, [r7, #4]
	lsrs r7, r0, #32
	ldrh r1, [r7, #52]
	lsrs r7, r0, #32
	strh r5, [r0, #50]
	lsrs r7, r0, #32
	str r2, [sp, #516]
	lsrs r7, r0, #32
	str r3, [sp, #292]
	lsrs r7, r0, #32
	strh r5, [r1, #12]
	lsrs r7, r0, #32
	strh r5, [r6, #10]
	lsrs r7, r0, #32
	b _0808998C
	.byte 0xE2
	.byte 0xE3
	.4byte 0xE7E6E5E4
	.4byte 0xEBEAE9E8
	.4byte 0xD3D2D1D0
	.4byte 0xD7D6D5D4
	.4byte 0xDBDAD9D8
	.4byte 0xC3C2C1C0
	.4byte 0xC7C6C5C4
	.4byte 0xCBCAC9C8
	.4byte 0xB3B2B1B0
	.4byte 0xB7B6B5B4
	.4byte 0xBBBAB9B8
	.4byte 0xA3A2A1A0
	.4byte 0xA7A6A5A4
	.4byte 0xABAAA9A8
	.4byte 0x93929190
	.4byte 0x97969594
	.4byte 0x9B9A9998
	.4byte 0x83828180
	.4byte 0x87868584
	.4byte 0x8B8A8988
	.4byte 0x73727170
	.4byte 0x77767574
	.4byte 0x7B7A7978
	.4byte 0x63626160
	.4byte 0x67666564
	.4byte 0x6B6A6968
	.4byte 0x53525150
	.4byte 0x57565554
	.4byte 0x5B5A5958
	.4byte 0x43424140
	.global _08089644
_08089644:
	.4byte 0x47464544
	.4byte 0x4B4A4948
	.4byte 0x33323130
	.global _08089650
_08089650:
	.4byte 0x37363534
	.4byte 0x3B3A3938
	.4byte 0x23222120
	.4byte 0x27262524
	.4byte 0x2B2A2928
	.4byte 0x13121110
	.4byte 0x17161514
	.4byte 0x1B1A1918
	.4byte 0x03020100
	.4byte 0x07060504
	.4byte 0x0B0A0908
	.4byte 0x80000000
	.4byte 0x879C7C97
	.4byte 0x8FACD61E
	.4byte 0x9837F052
	.4byte 0xA14517CC
	.4byte 0xAADC0848
	.4byte 0xB504F334
	.4byte 0xBFC886BB
	.4byte 0xCB2FF52A
	.4byte 0xD744FCCB
	.4byte 0xE411F03A
	.4byte 0xF1A1BF39
	.4byte 0x00840060
	.4byte 0x00E000B0
	.4byte 0x01300108
	.4byte 0x01C00160
	.4byte 0x02600210
	.4byte 0x02C002A0
	.4byte 0x03020100
	.4byte 0x07060504
	.4byte 0x0B0A0908
	.4byte 0x13121110
	.4byte 0x17161514
	.4byte 0x1B1A1918
	.4byte 0x23222120
	.4byte 0x27262524
	.4byte 0x2B2A2928
	.4byte 0x33323130
	.4byte 0x37363534
	.4byte 0x3B3A3938
	.4byte 0x43424140
	.4byte 0x47464544
	.4byte 0x4B4A4948
	.4byte 0x53525150
	.4byte 0x57565554
	.4byte 0x5B5A5958
	.4byte 0x63626160
	.4byte 0x67666564
	.4byte 0x6B6A6968
	.4byte 0x73727170
	.4byte 0x77767574
	.4byte 0x7B7A7978
	.4byte 0x83828180
	.4byte 0x87868584
	.4byte 0x8B8A8988
	.4byte 0x93929190
	.4byte 0x97969594
	.4byte 0x9B9A9998
	.4byte 0xA3A2A1A0
	.4byte 0xA7A6A5A4
	.4byte 0xABAAA9A8
	.4byte 0xF89DF82C
	.4byte 0xF96BF907
	.4byte 0xFA23F9C9
	.4byte 0xFAC7FA77
	.4byte 0xFB58FB12
	.4byte 0xFBDAFB9B
	.4byte 0xD4D5D6D7
	.4byte 0xC4C5C6C7
	.4byte 0xB4B5B6B7
	.4byte 0xA4A5A6A7
	.4byte 0x94959697
	.4byte 0x84858687
	.4byte 0x74757677
	.4byte 0x64656667
	.4byte 0x54555657
	.4byte 0x44454647
	.4byte 0x34353637
	.4byte 0x24252627
	.4byte 0x14151617
	.4byte 0x04050607
	.4byte 0x00010203
	.4byte 0x60600000
	.4byte 0x40406060
	.4byte 0x80804040
	.4byte 0x20208080
	.4byte 0x03020100
	.4byte 0x07060504
	.4byte 0x0B0A0908
	.byte 0x0C
	.byte 0x0D
	.global _080897BA
_080897BA:
	lsrs r6, r1, #28
	asrs r0, r2, #4
	asrs r2, r2, #12
	asrs r4, r2, #20
	asrs r6, r2, #28
	adds r0, r3, #0
	movs r0, #30
	cmp r0, #36
	cmp r4, #42
	adds r4, #48
	subs r0, #54
	ands r4, r7
	add r2, r8
	.inst.n 0x4C48  @ ldr r4, _080898F8
	str r6, [r1, r1]
	ldr r4, [r2, r1]
	ldrb r2, [r3, r1]
	lsls r0, r4, #1
	movs r0, r0
	ldr r5, [sp, #596]
	lsrs r7, r0, #32
	ldr r5, [sp, #676]
	lsrs r7, r0, #32
	ldr r5, [sp, #964]
	lsrs r7, r0, #32
	ldr r5, [sp, #596]
	lsrs r7, r0, #32
	ldr r6, [sp, #20]
	lsrs r7, r0, #32
	ldr r6, [sp, #100]
	lsrs r7, r0, #32
	ldr r6, [sp, #180]
	lsrs r7, r0, #32
	ldr r6, [sp, #260]
	lsrs r7, r0, #32
	ldr r6, [sp, #340]
	.global _08089802
_08089802:
	lsrs r7, r0, #32
	ldr r6, [sp, #388]
	.global _08089806
_08089806:
	lsrs r7, r0, #32
	ldr r6, [sp, #436]
	lsrs r7, r0, #32
	ldr r6, [sp, #516]
	lsrs r7, r0, #32
	subs r4, #0
	movs r0, r0
	.2byte 0xB89C
	lsrs r0, r1, #32

	.thumb_func
	.thumb
	.global sub_08089818
sub_08089818:
	ldrb r7, [r7, #31]
	.global _0808981A
_0808981A:
	bhi _080897BA
	subs r4, #3
	movs r0, r0
	add sp, #208
	lsrs r0, r1, #32
	movs r0, r0
	.global _08089826
_08089826:
	lsls r4, r1, #12
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	lsls r0, r0, #4
	lsls r0, r1, #16
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	lsls r0, r0, #24
	movs r0, r0
	subs r4, #2
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r6, r1
	subs r4, #1
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r6, r0
	subs r4, #0
	movs r0, r0
	.2byte 0xE990
	lsrs r0, r1, #32
	ldrb r7, [r7, #31]
	bhi _08089802
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	.2byte 0xF9AC
	lsrs r0, r1, #32
	ldrb r7, [r7, #31]
	bhi _0808981A
	subs r4, #0
	movs r0, r0
	.inst.n 0x1F80  @ subs r0, r0, #6
	lsrs r1, r1, #32
	ldrb r7, [r7, #31]
	bhi _08089826
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	.inst.n 0x4C24  @ ldr r4, _08089968
	lsrs r1, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	strh r0, [r3, #32]
	lsrs r1, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	add r0, sp, #720
	lsrs r1, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	.global _080898F8
_080898F8:
	.4byte 0x00000002
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	.global _08089968
_08089968:
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.global _0808998C
_0808998C:
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	bcc _08089968
	lsrs r1, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	.2byte 0xFCBC
	lsrs r1, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	adds r2, #188
	lsrs r2, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	ldr r0, [r2, r5]
	lsrs r2, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	ldrb r4, [r1, #21]

	.thumb_func
	.thumb
	.global sub_08089A6E
sub_08089A6E:
	lsrs r2, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	ldr r1, [sp, #160]
	lsrs r2, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	add r6, sp, #400
	lsrs r2, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	beq _08089B70
	lsrs r2, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	b _08089E04
	.byte 0x0A
	.byte 0x08
	.4byte 0xCCCE7FFF
	.4byte 0x00003C00
	.4byte 0x080AF4E0
	.4byte 0xCCCE7FFF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C00
	.4byte 0x080B2BBC
	.4byte 0xBCCE7F25
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C00
	.4byte 0x080B3FF0
	.4byte 0xBCCE7FFF
	.4byte 0x00003C01
	.byte 0x02
	.byte 0x00

	.thumb_func
	.thumb
	.global sub_08089AFE
sub_08089AFE:
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1

	.thumb_func
	.thumb
	.global sub_08089B06
sub_08089B06:
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	str r4, [r0, r5]
	lsrs r3, r1, #32
	ldrb r7, [r7, #31]
	pop {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	strh r4, [r3, r7]
	lsrs r3, r1, #32
	ldrb r7, [r7, #31]
	pop {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	ldrb r4, [r3, r1]
	lsrs r3, r1, #32
	ldrb r7, [r7, #31]
	pop {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	ldr r0, [r4, #116]
	lsrs r3, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	.global _08089B70
_08089B70:
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	strh r4, [r6, #30]
	lsrs r3, r1, #32
	ldrb r7, [r7, #31]
	pop {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	.global _08089BB8
_08089BB8:
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	.2byte 0xBB0C
	lsrs r3, r1, #32
	ldrb r7, [r7, #31]
	pop {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	ble _08089BB8
	lsrs r3, r1, #32
	ldrb r7, [r7, #31]
	pop {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	movs r2, #164
	lsrs r4, r1, #32
	ldrb r7, [r7, #31]
	.2byte 0xF2CE
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	subs r4, #108
	lsrs r4, r1, #32
	pop {r0, r1, r2, r3, r4, r5, r6, r7}
	bhi _08089CCC
	.global _08089CCC
_08089CCC:
	subs r4, #0
	movs r0, r0
	strh r0, [r0, #48]
	lsrs r4, r1, #32
	pop {r0, r1, r2, r3, r4, r5, r6, r7}
	bhi _08089CD8
	.global _08089CD8
_08089CD8:
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	.global _08089CFA
_08089CFA:
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_08089D54
sub_08089D54:
	push {r2, r4, r6}
	lsrs r4, r1, #32
	ldrb r7, [r7, #31]
	bhi _08089CFA
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	.2byte 0xDE0C
	.byte 0x0C
	.byte 0x08
	.4byte 0xD8CE7FFF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.byte 0x02
	.byte 0x00

	.thumb_func
	.thumb
	.global sub_08089D9E
sub_08089D9E:
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	.2byte 0xFC68
	lsrs r4, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	ldr r4, [r7, #28]
	lsrs r5, r1, #32
	ldrb r7, [r7, #31]
	pop {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	ldrh r0, [r2, #14]
	lsrs r5, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	.global _08089E04
_08089E04:
	lsls r0, r0, #2
	movs r0, r0
	ldr r4, [sp, #960]
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1

	.thumb_func
	.thumb
	.global sub_08089E2A
sub_08089E2A:
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r0, r1, #0
	.2byte 0xC000
	.2byte 0xF764
	lsrs r5, r1, #32
	lsls r7, r7, #3
	bhi _08089E58
	.global _08089E58
_08089E58:
	subs r4, #8
	movs r0, r0
	asrs r4, r5, #17
	lsrs r6, r1, #32
	lsls r7, r7, #3
	adr r5, _0808A260
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	asrs r0, r7, #20
	lsrs r6, r1, #32
	ldrb r7, [r7, #31]
	adr r5, _0808A1C0
	subs r4, #8
	movs r0, r0
	lsls r0, r2
	lsrs r6, r1, #32
	lsls r7, r7, #3
	.inst.n 0xCCFF  @ ldmia r4!, {r0, r1, r2, r3, r4, r5, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	str r4, [r2, r4]
	lsrs r6, r1, #32
	lsls r7, r7, #3
	adr r5, _0808A2A8
	subs r4, #8
	movs r0, r0
	str r0, [r4, #96]
	lsrs r6, r1, #32
	lsls r7, r7, #3
	adr r5, _0808A2B4
	subs r4, #8
	movs r0, r0
	strb r0, [r7, #15]
	lsrs r6, r1, #32
	lsls r7, r7, #3
	ldrb r7, [r7, #31]
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	ldrb r4, [r1, #28]
	lsrs r6, r1, #32
	adr r5, _0808A2F0
	movs r6, #255
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	strh r0, [r1, #32]
	lsrs r6, r1, #32
	adr r5, _0808A320
	movs r6, #255
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	ldr r0, [sp, #624]
	lsrs r6, r1, #32
	lsls r7, r7, #3
	pop {r1, r2, r3, r6, r7}
	subs r4, #8
	movs r0, r0
	.2byte 0xB138
	lsrs r6, r1, #32
	pop {r0, r1, r2, r3, r4, r5, r6, r7}
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0

	.thumb_func
	.thumb
	.global sub_0808A026
sub_0808A026:
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	.2byte 0xF5CC
	lsrs r6, r1, #32
	ldrb r7, [r7, #31]
	adr r5, _0808A3F4
	subs r4, #8
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808A0C0
sub_0808A0C0:
	.2byte 0xF9A8
	lsrs r6, r1, #32
	ldrb r7, [r7, #31]
	.global _0808A0C6
_0808A0C6:
	.2byte 0xF2CE
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	.global _0808A0D2
_0808A0D2:
	movs r7, r1
	subs r4, #8
	movs r0, r0
	asrs r0, r6, #25
	lsrs r7, r1, #32
	ldrb r7, [r7, #31]

	.thumb_func
	.thumb
	.global sub_0808A0DE
sub_0808A0DE:
	.2byte 0xF2CE
	subs r4, #4
	movs r0, r0
	movs r1, r0

	.thumb_func
	.thumb
	.global sub_0808A0E6
sub_0808A0E6:
	movs r0, r0
	movs r0, r0
	lsls r4, r1, #16
	subs r4, #3
	movs r0, r0
	add sp, #208
	lsrs r0, r1, #32
	lsls r0, r0, #4
	movs r4, r1
	subs r4, #3
	movs r0, r0
	add sp, #400
	lsrs r0, r1, #32
	movs r0, r0
	movs r4, r1
	subs r4, #0
	movs r0, r0
	adds r0, #172
	lsrs r7, r1, #32
	ldrb r0, [r0, #29]
	adr r5, _0808A448
	subs r4, #0
	movs r0, r0
	adds r5, #208
	lsrs r7, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}

	.thumb_func
	.thumb
	.global sub_0808A11C
sub_0808A11C:
	subs r4, #0
	movs r0, r0
	subs r6, #132
	lsrs r7, r1, #32
	movs r6, #64
	bhi _0808A0C6
	subs r4, #0
	movs r0, r0
	strb r0, [r3, #11]
	lsrs r7, r1, #32
	movs r6, #255
	bhi _0808A0D2
	subs r4, #0
	movs r0, r0
	push {r2, r3, r5, r6, r7}
	lsrs r7, r1, #32
	ldrb r7, [r7, #31]
	ldmia r4!, {r1, r2, r3, r6, r7}
	subs r4, #0
	movs r0, r0
	pop {r2, r4, pc}
	.byte 0x0F
	.byte 0x08
	.4byte 0xCCCE7FFF
	.4byte 0x00003C00
	.4byte 0x080FF6C8
	.4byte 0xCCCE7FFF
	.4byte 0x00003C00
	.4byte 0x081030DC
	.4byte 0xCCCE7FFF
	.4byte 0x00003C00
	.4byte 0x0810594C
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x08106424
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x08107414
	.4byte 0x7FCE7FFF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C00
	.4byte 0x0810A564
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x0810B22C
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x0810C6A8
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x0810E2BC
	.global _0808A1C0
_0808A1C0:
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x08110EBC
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x08112BD0
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x08115A24
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x081165D4
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x08116F9C
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x0811D424
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x081222F8
	.4byte 0x7FCE7FFF
	.4byte 0x00003C00
	.4byte 0x0812798C
	.4byte 0x7FE77FFF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C00
	.4byte 0x081282B0
	.4byte 0xCCE77FFF
	.4byte 0x00003C00
	.4byte 0x0812AB64
	.4byte 0xCCE77FFF
	.4byte 0x00003C00
	.4byte 0x0812ECD8
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x0812FD0C
	.4byte 0x7FE77FFF
	.global _0808A260
_0808A260:
	.4byte 0x00003C00
	.4byte 0x08132310
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x08137498
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x08138240
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x08138730
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x0813C25C
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x0813D2D0
	.4byte 0x7FE77FFF
	.global _0808A2A8
_0808A2A8:
	.4byte 0x00003C00
	.4byte 0x0813E10C
	.4byte 0x7FE77FFF
	.global _0808A2B4
_0808A2B4:
	.4byte 0x00003C00
	.4byte 0x0813F560
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x08141978
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x0814718C
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x08148270
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x0814DF30
	.4byte 0x7FE77FFF
	.global _0808A2F0
_0808A2F0:
	.4byte 0x00003C00
	.4byte 0x08151FA4
	.4byte 0x7FE77FFF
	.global _0808A2FC
_0808A2FC:
	subs r4, #0
	movs r0, r0
	subs r7, #0
	lsrs r5, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	ldrh r4, [r2, #48]
	lsrs r5, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	.2byte 0xB328
	lsrs r5, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	.global _0808A320
_0808A320:
	.4byte 0x00003C00
	.4byte 0x0815D03C

	.thumb_func
	.thumb
	.global sub_0808A328
sub_0808A328:
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	asrs r0, r2, #11
	lsrs r6, r2, #32

	.thumb_func
	.thumb
	.global sub_0808A334
sub_0808A334:
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	.global _0808A338
_0808A338:
	subs r4, #0
	movs r0, r0
	adds r5, #100
	lsrs r6, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	bhi _0808A2FC
	lsrs r6, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	lsls r0, r0, #6
	lsrs r7, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	cmp r2, #236
	lsrs r7, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	bvs _0808A410
	lsrs r7, r2, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	adds r3, #184
	lsrs r0, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #8
	movs r0, r0
	ldrsh r4, [r1, r2]
	lsrs r0, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	strh r0, [r1, #48]
	lsrs r0, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	adr r3, _0808A7A8
	lsrs r0, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	.2byte 0xC700
	lsrs r0, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	bpl _0808A498
	lsrs r0, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	bhi _0808A338
	lsrs r0, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	.2byte 0xEA0C
	lsrs r0, r3, #32
	.global _0808A3F4
_0808A3F4:
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x081930B0
	.4byte 0x7FE77FFF
	.4byte 0x00003C00
	.4byte 0x08194BC4
	.4byte 0x7FE77FFF
	.global _0808A410
_0808A410:
	subs r4, #0
	movs r0, r0
	str r0, [r7, #48]
	lsrs r1, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	ldrh r4, [r5, #58]
	lsrs r1, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	.2byte 0xB220
	lsrs r1, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #0
	movs r0, r0
	push {r2, r5, lr}
	lsrs r1, r3, #32
	ldrb r7, [r7, #31]
	ldrb r7, [r4, #31]
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	.global _0808A448
_0808A448:
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.global _0808A498
_0808A498:
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808A6A2
sub_0808A6A2:
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #4
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	lsls r4, r1, #4
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #2
	movs r0, r0
	movs r3, r0
	movs r0, r0
	lsls r0, r0, #4
	movs r4, r1
	subs r4, #1
	movs r0, r0
	movs r3, r0
	movs r0, r0
	lsls r0, r0, #8
	lsls r1, r1, #16
	subs r4, #2
	movs r0, r0
	movs r2, r0
	movs r0, r0
	lsls r0, r0, #8
	lsls r1, r1, #20
	subs r4, #1
	movs r0, r0
	movs r0, r0
	movs r0, r0
	lsls r0, r0, #8
	lsls r2, r1, #16
	subs r4, #3
	movs r0, r0
	add sp, #336
	lsrs r0, r1, #32
	lsls r0, r0, #24
	lsls r4, r1, #8
	subs r4, #2
	movs r0, r0
	movs r1, r0
	movs r0, r0
	lsls r0, r0, #8
	lsls r4, r1, #16
	subs r4, #4
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	lsls r4, r1, #8
	subs r4, #3
	movs r0, r0
	sub sp, #144
	lsrs r0, r1, #32
	lsls r0, r0, #16
	lsls r6, r0, #24
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	.global _0808A7A8
_0808A7A8:
	.4byte 0x000F0000
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808A8EC
sub_0808A8EC:
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0

	.thumb_func
	.thumb
	.global sub_0808A956
sub_0808A956:
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1

	.thumb_func
	.thumb
	.global sub_0808A9A6
sub_0808A9A6:
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1

	.thumb_func
	.thumb
	.global sub_0808AAAC
sub_0808AAAC:
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	lsls r0, r0, #2
	movs r0, r0
	add r3, sp, #720
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r0, r1, #0
	.2byte 0xC000
	.2byte 0xF764
	lsrs r5, r1, #32
	lsls r7, r7, #3
	bhi _0808AD1C
	.global _0808AD1C
_0808AD1C:
	subs r4, #8
	movs r0, r0
	asrs r4, r5, #17
	lsrs r6, r1, #32
	lsls r7, r7, #3
	.inst.n 0xA5FF  @ adr r5, _0808B124
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #0
	movs r0, r0
	asrs r0, r7, #20
	lsrs r6, r1, #32
	ldrb r7, [r7, #31]
	.inst.n 0xA5CE  @ adr r5, _0808B084
	subs r4, #8
	movs r0, r0
	lsls r0, r2
	lsrs r6, r1, #32
	lsls r7, r7, #3
	.inst.n 0xCCFF  @ ldmia r4!, {r0, r1, r2, r3, r4, r5, r6, r7}
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	stmia r2!, {r3, r5, r7}
	lsrs r1, r3, #32
	lsls r7, r7, #3
	.inst.n 0xA5FF  @ adr r5, _0808B16C
	subs r4, #8
	movs r0, r0
	str r0, [r4, #96]
	lsrs r6, r1, #32
	lsls r7, r7, #3
	.inst.n 0xA5FF  @ adr r5, _0808B178
	subs r4, #8
	movs r0, r0
	b _0808B44C
	.byte 0x19
	.byte 0x08
	.4byte 0x7FFF00FF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C08
	.4byte 0x080E7F0C
	.4byte 0x26FFA5FF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C08
	.4byte 0x080E8408
	.4byte 0x26FFA5FF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C08
	.4byte 0x080E989C
	.4byte 0xBCCE00FF
	.4byte 0x00003C08
	.4byte 0x0819EED0
	.4byte 0xE2CEBCFF
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.4byte 0x000F0000
	.4byte 0x00003C01
	.4byte 0x00000002
	.byte 0x00
	.byte 0x00

	.thumb_func
	.thumb
	.global sub_0808AEEE
sub_0808AEEE:
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	.2byte 0xF5CC
	lsrs r6, r1, #32
	ldrb r7, [r7, #31]
	.inst.n 0xA5CE  @ adr r5, _0808B2B8
	subs r4, #8
	movs r0, r0
	.2byte 0xF9A8
	lsrs r6, r1, #32
	ldrb r7, [r7, #31]
	.2byte 0xF2CE
	subs r4, #1
	movs r0, r0
	movs r2, r0
	movs r0, r0
	movs r0, r0
	movs r7, r1
	subs r4, #8
	movs r0, r0
	asrs r0, r6, #25
	lsrs r7, r1, #32
	ldrb r7, [r7, #31]
	.2byte 0xF2CE
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B000
sub_0808B000:
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	movs r0, r0
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	lsls r1, r0, #4
	strb r7, [r6, #29]
	asrs r0, r6, #9
	ldrh r5, [r6, #8]
	.2byte 0xDEAC
	.4byte 0x65A9DCFE
	.4byte 0x77770031
	.4byte 0x67452301
	.4byte 0xEFCDAB89
	.4byte 0x98BADCFE
	.4byte 0x10325476
	.4byte 0xDCEDFE0F
	.4byte 0x98A9BACB
	.4byte 0x54657687
	.4byte 0x10213243
	.4byte 0xBADCFE00
	.4byte 0x88888899
	.4byte 0x66777777
	.4byte 0x00103254
	.4byte 0x0000FFFF
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.global _0808B084
_0808B084:
	.4byte 0xFFFFFFFF
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0xFFFFFFFF
	.4byte 0x0000FFFF
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0xFFFFFFFF
	.4byte 0xFFFFFFFF
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0xCCDDEEFF
	.4byte 0xCCBBAABB
	.4byte 0xEEFFEEDD
	.4byte 0xAABBCCDD

	.thumb_func
	.thumb
	.global sub_0808B0C4
sub_0808B0C4:
	movs r0, r0
	adds r3, #17
	strb r5, [r2, r5]
	asrs r3, r6, #4
	add r2, sp, #680
	pop {r0, r1, r3, r5, r7}
	.2byte 0xDECD
	.byte 0xEF
	.byte 0xFF
	.4byte 0x09009A9A
	.4byte 0x9A00A0A9
	.4byte 0xA909009A
	.4byte 0xFFFF0FA0
	.4byte 0x65241302
	.4byte 0xAC9B8776
	.4byte 0xBCCDDEBE
	.4byte 0x65789AAB
	.4byte 0x00000000
	.4byte 0xAA000000
	.4byte 0xAAAAAAAA
	.4byte 0xAAAAAAAA
	.4byte 0x57130000

	.thumb_func
	.thumb
	.global sub_0808B108
sub_0808B108:
	ldrsb r7, [r2, r6]
	swi #155
	.2byte 0xFFFF
	bls sub_0808B108
	adds r1, #117
	movs r0, r0
	ldr r7, [sp, #36]
	ldrb r7, [r6, #23]
	ldrh r5, [r2, r7]
	ldr r7, [sp, #740]
	subs r2, #243
	asrs r1, r4, #6
	movs r0, r0
	movs r0, r0
	.global _0808B124
_0808B124:
	.4byte 0x34231201
	.4byte 0x78675645
	.4byte 0x54657687
	.4byte 0x10213243
	.4byte 0x12707777
	.4byte 0xDEAC8935
	.4byte 0x65A9DCFE
	.4byte 0x77770031
	.4byte 0x03005F30
	.4byte 0x03004048
	.4byte 0x0000000D
	.4byte 0x03005FB0
	.4byte 0x03004458
	.4byte 0x00000003
	.4byte 0x03005FF0
	.4byte 0x03004548
	.4byte 0x00000003
	.4byte 0x030060C0
	.global _0808B16C
_0808B16C:
	.4byte 0x03004638  @ IWRAM+0x4638
	.4byte 0x00000003
	.byte 0x30
	.byte 0x60

	.thumb_func
	.thumb
	.global sub_0808B176
sub_0808B176:
	lsls r0, r0, #12
	.global _0808B178
_0808B178:
	.4byte 0x03004728  @ IWRAM+0x4728
	.4byte 0x00000003
	.4byte 0x03005EB0
	.4byte 0x03004818
	.4byte 0x00000003
	.4byte 0x03005EF0
	.4byte 0x03004908
	.4byte 0x0000000A
	.4byte 0x03005F70
	.4byte 0x03004C28
	.4byte 0x00000003
	.4byte 0x03006080
	.4byte 0x03004D18
	.4byte 0x00000003
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081A2BD4
	.4byte 0x00000000
	.4byte 0x081A3104
	.4byte 0x00000000
	.4byte 0x081A33C0
	.4byte 0x00000000
	.4byte 0x081A3978
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081A3C24
	.4byte 0x00000000
	.4byte 0x081A41AC
	.4byte 0x00000000
	.4byte 0x081A4928
	.4byte 0x00000000
	.4byte 0x081A4E40
	.4byte 0x00000000
	.4byte 0x081A514C
	.4byte 0x00000000
	.4byte 0x081A5690
	.4byte 0x00000000
	.4byte 0x081A5BB0
	.4byte 0x00000000
	.4byte 0x081A60F4
	.4byte 0x00000000
	.4byte 0x081A6AB4
	.4byte 0x00000000
	.4byte 0x081A738C
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081A77F4
	.4byte 0x00000000
	.4byte 0x081A7A8C
	.4byte 0x00000000
	.4byte 0x081A8164
	.4byte 0x00000000
	.4byte 0x081A8838
	.4byte 0x00000000
	.4byte 0x081A8C14
	.4byte 0x00000000
	.4byte 0x081A8E58
	.4byte 0x00000000
	.4byte 0x081A9210
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081A9920
	.4byte 0x00000000
	.4byte 0x081A9EB8
	.4byte 0x00000000
	.4byte 0x081AA140
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081AA6C8
	.4byte 0x00000000
	.4byte 0x081AB350
	.global _0808B2AC
_0808B2AC:
	movs r0, r0
	movs r0, r0
	.2byte 0xB6C0
	lsrs r2, r3, #32
	movs r0, r0
	movs r0, r0
	.global _0808B2B8
_0808B2B8:
	.4byte 0x0808B898  @ ROM+0x8B898
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B2D8
sub_0808B2D8:
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B380
sub_0808B380:
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B39E
sub_0808B39E:
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B3A8
sub_0808B3A8:
	.2byte 0xB898
	lsrs r0, r1, #32

	.thumb_func
	.thumb
	.global sub_0808B3AC
sub_0808B3AC:
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898

	.thumb_func
	.thumb
	.global sub_0808B3BA
sub_0808B3BA:
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B3C0
sub_0808B3C0:
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898

	.thumb_func
	.thumb
	.global sub_0808B3D2
sub_0808B3D2:
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898

	.thumb_func
	.thumb
	.global sub_0808B3E2
sub_0808B3E2:
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B3F6
sub_0808B3F6:
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	.global _0808B44C
_0808B44C:
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0

	.thumb_func
	.thumb
	.global sub_0808B488
sub_0808B488:
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB6F4
	lsrs r2, r3, #32
	movs r1, r0
	movs r1, r0
	.2byte 0xB714
	lsrs r2, r3, #32
	movs r1, r0
	movs r1, r0
	.2byte 0xB73C
	lsrs r2, r3, #32
	movs r1, r0
	movs r1, r0
	.2byte 0xB764
	lsrs r2, r3, #32
	movs r1, r0
	movs r1, r0
	.2byte 0xB780
	lsrs r2, r3, #32
	movs r1, r0
	movs r1, r0
	.2byte 0xB79C
	lsrs r2, r3, #32
	movs r1, r0
	movs r1, r0
	.2byte 0xB7B8
	lsrs r2, r3, #32
	movs r1, r0
	movs r1, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB888
	lsrs r2, r3, #32
	movs r6, r0
	movs r6, r0
	.2byte 0xB91C
	lsrs r2, r3, #32
	movs r6, r0
	movs r6, r0
	.2byte 0xB944
	lsrs r2, r3, #32
	movs r2, r0
	movs r2, r0
	.2byte 0xB960
	lsrs r2, r3, #32
	movs r2, r0
	movs r2, r0
	.2byte 0xB97C
	lsrs r2, r3, #32
	movs r2, r0

	.thumb_func
	.thumb
	.global sub_0808B53E
sub_0808B53E:
	movs r2, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	.2byte 0xB998
	lsrs r2, r3, #32
	movs r2, r0
	movs r2, r0
	.2byte 0xB9B4
	lsrs r2, r3, #32
	movs r2, r0
	movs r2, r0
	.2byte 0xB9D0
	lsrs r2, r3, #32
	movs r2, r0
	movs r2, r0
	.2byte 0xB9EC
	lsrs r2, r3, #32
	movs r2, r0
	movs r2, r0
	.2byte 0xBA08
	lsrs r2, r3, #32
	movs r3, r0
	movs r3, r0
	.2byte 0xBA74
	lsrs r2, r3, #32
	movs r6, r0
	movs r6, r0
	.2byte 0xBA98
	lsrs r2, r3, #32
	movs r3, r0
	movs r3, r0
	.2byte 0xBAB4
	lsrs r2, r3, #32
	movs r3, r0
	movs r3, r0
	.2byte 0xBAD8
	lsrs r2, r3, #32
	movs r3, r0
	movs r3, r0
	.2byte 0xBAFC
	lsrs r2, r3, #32
	movs r3, r0
	movs r3, r0
	pop {r2, r5, r7, pc}
	.byte 0x1A
	.byte 0x08
	.4byte 0x00000000
	.4byte 0x081ABE1C
	.4byte 0x00060006
	.4byte 0x081ABE7C
	.4byte 0x00060006
	.4byte 0x081ABF40
	.4byte 0x00000000
	.4byte 0x081AC028
	.4byte 0x00060006
	.4byte 0x081AC054
	.4byte 0x00040004
	.4byte 0x081AC070
	.4byte 0x00040004
	.4byte 0x081AC08C
	.4byte 0x00040004
	.4byte 0x081AC0A8
	.4byte 0x00040004
	.4byte 0x081AC0C4
	.4byte 0x00040004
	.4byte 0x081AC0E0
	.4byte 0x00040004
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081AC0FC
	.4byte 0x00040004
	.4byte 0x081AC118
	.4byte 0x00040004
	.4byte 0x081AC134
	.4byte 0x00020002
	.4byte 0x081AC188
	.4byte 0x00050005
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081AC1A8
	.4byte 0x00040004
	.4byte 0x081AC1C4
	.4byte 0x00040004
	.4byte 0x081AC208
	.4byte 0x00050005
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081AC224
	.4byte 0x00040004
	.4byte 0x081AC240
	.4byte 0x00040004
	.4byte 0x081AC25C
	.4byte 0x00040004
	.4byte 0x081AC278
	.4byte 0x00040004
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081AC294
	.4byte 0x00040004
	.4byte 0x081AC2B0
	.4byte 0x00040004
	.4byte 0x081AC2CC
	.4byte 0x00040004
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081AC2E8
	.4byte 0x00040004
	.4byte 0x081AC304
	.4byte 0x00040004
	.4byte 0x081AC340
	.4byte 0x00050005
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x081AC35C
	.4byte 0x00040004
	.4byte 0x081AC378
	.4byte 0x00040004
	.4byte 0x081AC394
	.4byte 0x00040004
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.4byte 0x00000000
	.4byte 0x0808B898
	.global _0808B7E4
_0808B7E4:
	movs r0, r0
	movs r0, r0
	.2byte 0xB898
	lsrs r0, r1, #32
	movs r0, r0
	movs r0, r0
	stmia r3!, {r4, r5, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r3!, {r2, r3, r6, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r3!, {r3, r5, r6, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r2}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r5}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r2, r3, r4, r5}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r3, r4, r6}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r2, r4, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r4, r5, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r2, r3, r6, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r4!, {r3, r5, r6, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r5!, {r3}
	lsrs r2, r3, #32
	movs r5, r0
	movs r5, r0
	stmia r5!, {r3, r5}
	lsrs r2, r3, #32
	movs r5, r0
	movs r5, r0
	stmia r5!, {r2, r6}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r5!, {r2, r5, r6}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r5!, {r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r5!, {r2, r3, r4, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r5!, {r3, r4, r5, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r5!, {r2, r4, r6, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r5!, {r4, r5, r6, r7}
	lsrs r2, r3, #32
	movs r4, r0
	movs r4, r0
	stmia r6!, {r2, r3}
	lsrs r2, r3, #32
	movs r4, r0
	.global _0808B896
_0808B896:
	movs r4, r0
	movs r0, r0
	movs r0, r0

	.section .rom.0008B89C, "a"
	.incbin "build/sound/samples/08B89C.bin", 0, 12532

	.section .rom.0008E990, "a"
	.incbin "build/sound/samples/08E990.bin", 0, 4124

	.section .rom.0008F9AC, "a"
	.incbin "build/sound/samples/08F9AC.bin", 0, 1812
