@ ROM 0E80C0..0F00C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000E80C0, "a"
	.incbin "build/sound/samples/0E7F0C.bin", 436, 840

	.section .rom.000E8408, "a"
	.incbin "build/sound/samples/0E8408.bin", 0, 5268

	.section .rom.000E989C, "a"
	.incbin "build/sound/samples/0E989C.bin", 0, 6300

	.section .rom.000EB138, "a"
	.incbin "build/sound/samples/0EB138.bin", 0, 17556

	.section .rom.000EF5CC, "a"
	.incbin "build/sound/samples/0EF5CC.bin", 0, 988

	.section .rom.000EF9A8, "a"
	.incbin "build/sound/samples/0EF9A8.bin", 0, 1816
