@ ROM 1100C0..1180C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001100C0, "a"
	.incbin "build/sound/samples/10E2BC.bin", 7684, 3580

	.section .rom.00110EBC, "a"
	.incbin "build/sound/samples/110EBC.bin", 0, 7444

	.section .rom.00112BD0, "a"
	.incbin "build/sound/samples/112BD0.bin", 0, 11860

	.section .rom.00115A24, "a"
	.incbin "build/sound/samples/115A24.bin", 0, 2992

	.section .rom.001165D4, "a"
	.incbin "build/sound/samples/1165D4.bin", 0, 2504

	.section .rom.00116F9C, "a"
	.incbin "build/sound/samples/116F9C.bin", 0, 4388
