@ ROM 1500C0..1580C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.001500C0, "a"
	.incbin "build/sound/samples/14DF30.bin", 8592, 7908

	.section .rom.00151FA4, "a"
	.incbin "build/sound/samples/151FA4.bin", 0, 8028

	.section .rom.00153F00, "a"
	.incbin "build/sound/samples/153F00.bin", 0, 16832
