@ ROM 0980C0..0A00C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000980C0, "a"
	.incbin "build/sound/samples/094C24.bin", 13468, 856

	.section .rom.00098418, "a"
	.incbin "build/sound/samples/098418.bin", 0, 9372

	.section .rom.0009A8B4, "a"
	.incbin "build/sound/samples/09A8B4.bin", 0, 11012

	.section .rom.0009D3B8, "a"
	.incbin "build/sound/samples/09D3B8.bin", 0, 10500

	.section .rom.0009FCBC, "a"
	.incbin "build/sound/samples/09FCBC.bin", 0, 1028
