@ ROM 0B00C0..0B80C0
@ Generated by tools/split.py from the recovered layout.
@ Instructions come from recursive descent; bytes the
@ analysis could not prove are code are kept as literals
@ so this file reassembles to the original image.


	.section .rom.000B00C0, "a"
	.incbin "build/sound/samples/0AF4E0.bin", 3040, 11004

	.section .rom.000B2BBC, "a"
	.incbin "build/sound/samples/0B2BBC.bin", 0, 5172

	.section .rom.000B3FF0, "a"
	.incbin "build/sound/samples/0B3FF0.bin", 0, 4436

	.section .rom.000B5144, "a"
	.incbin "build/sound/samples/0B5144.bin", 0, 664

	.section .rom.000B53DC, "a"
	.incbin "build/sound/samples/0B53DC.bin", 0, 2176

	.section .rom.000B5C5C, "a"
	.incbin "build/sound/samples/0B5C5C.bin", 0, 4868

	.section .rom.000B6F60, "a"
	.incbin "build/sound/samples/0B6F60.bin", 0, 4448
