#!/usr/bin/env python3
"""Generate graphics_rules.mk: one explicit build rule per asset.

Modelled on pokeemerald, where every graphic states its own bit depth and
width rather than relying on a guess made at build time. The values come from
assets.json; edit that file (or a rule here) when an asset is filed wrongly or
drawn at the wrong width.
"""
import json

HEADER = """\
# Per-asset graphics rules. GENERATED by tools/gen_rules.py -- edit
# assets.json and re-run `make rules`, or override a single asset below.
#
# Each rule turns the editable PNG into raw GBA character data:
#     graphics/<kind>/<name>.png  --(bpp, width)-->  build/.../<name>.4bpp
#
# The default build stages compressed assets through tools/build_assets.py:
# unchanged decoded pixels retain their source stream; edits are recompressed.
# These raw conversion targets also let you inspect any asset on demand:
#
#     make build/graphics/backgrounds/OP_05_A.KCG.4bpp
#
# and so the bit depth and width of every asset are written down somewhere you
# can correct.

GBAGFX := $(PYTHON) tools/gbagfx.py

"""


def main():
    manifest = json.load(open("assets.json"))
    try:
        manifest += json.load(open("assets_raw.json"))
    except OSError:
        pass
    gfx = [e for e in manifest if e["kind"] not in ("script", "sound", "raw_dump", "data")]
    lines = [HEADER]
    targets = []
    for e in gfx:
        path = e["path"]
        bpp = e.get("bpp", 4)
        width = e.get("width_tiles", 16)
        out = "$(BUILD)/%s.%dbpp" % (path, bpp)
        targets.append(out)
        lines.append(
            "# %s: %d tiles, %d bpp, %d tiles wide\n"
            % (path.split("/")[-1], e["raw_size"] // (32 if bpp == 4 else 64),
               bpp, width))
        if e['kind'] == 'mapped_image':
            lines.append('%s: %s.png $(MAPPED_PNGS) $(MAPPED_LAYOUTS) $(MAPPED_UNUSED) tools/mapped_images.py\n' % (out, path))
            lines.append('\t@mkdir -p $(dir $@)\n')
            lines.append('\t$(PYTHON) tools/mapped_images.py raw --asset %s --output $@\n\n' % e['archive_name'])
            continue
        lines.append("%s: %s.png\n" % (out, path))
        lines.append("\t@mkdir -p $(dir $@)\n")
        lines.append("\t$(GBAGFX) png2tiles $< $@ --bpp %d --size %d\n\n"
                     % (bpp, e["raw_size"]))
    lines.append("# Uncompressed art is part of the ROM image itself, so the\n")
    lines.append("# main build depends on these being converted.\n")
    lines.append("RAW_GFX := \\\n")
    raw = [t for t, e in zip(targets, gfx) if e["kind"] == "raw_art"]
    lines.append(" \\\n".join("\t" + t for t in raw) + "\n\n")
    lines.append(".PHONY: graphics-convert\n")
    lines.append("graphics-convert: \\\n")
    lines.append(" \\\n".join("\t" + t for t in targets) + "\n")
    with open("graphics_rules.mk", "w") as f:
        f.writelines(lines)
    print("wrote graphics_rules.mk with %d asset rules" % len(gfx))


if __name__ == "__main__":
    main()
