#!/usr/bin/env python3
"""Generate the English build's script-placement assembly.

Two outputs, both mechanically derived (safe to regenerate on every build,
unlike tools/split.py's one-time ROM extraction):

- asm/data/script_assets_english.s: structurally identical to the checked-in
  asm/data/script_assets.s (same section names, same ROM addresses, same
  order) but pointing at build/english/scripts/nfp/ instead of
  build/scripts/nfp/, so every script's *original* ROM slot keeps its exact
  size and position -- this is what makes it safe for the base mar.gba
  build to keep using the unmodified script_assets.s/.o unchanged while
  mar_english.gba uses this variant instead (see the Makefile's filter-out
  for mar_english.elf). A script whose marscript override grew past its
  original slot still gets an (inert, unreferenced) entry here -- see
  tools/marscript_rom_build.py's plan() -- so nothing downstream shifts.

- build/english/marscript_expansion.s: one .rodata symbol per script whose
  override didn't fit its original slot (usually none), each .incbin'd from
  build/english/scripts_expansion/<name>.bin. Landing in .rodata under
  build/english/*.o means ld_english.ld's existing `.english` section
  wildcard (`build/english/*.o(.text .text.* .rodata .rodata.*)`) picks
  these up automatically -- no linker script changes needed. The matching
  half of this mechanism is resource_catalog.py --english, which points
  that one script's catalog entry at the resulting symbol instead of a
  literal offset.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_SCRIPT_ASSETS = ROOT / 'asm/data/script_assets.s'
# build/, not asm/data/ -- unlike script_assets.s (a real, checked-in
# tools/split.py extraction artifact), this file is 100% mechanically
# derived and regenerated on every build; it doesn't belong alongside
# genuinely reviewed decompilation sources.
ENGLISH_SCRIPT_ASSETS = ROOT / 'build/english/script_assets_english.s'
EXPANSION_MANIFEST = ROOT / 'build/english/scripts_expansion_manifest.json'
EXPANSION_ASM = ROOT / 'build/english/marscript_expansion.s'


def marscript_identifier(name):
    return name.replace('.', '_').replace('-', '_')


def write_script_assets_english():
    text = BASE_SCRIPT_ASSETS.read_text()
    if 'build/scripts/nfp/' not in text:
        raise ValueError(f'{BASE_SCRIPT_ASSETS}: expected .incbin paths under build/scripts/nfp/')
    text = text.replace('build/scripts/nfp/', 'build/english/scripts/nfp/')
    text = text.replace(
        '@ script assets ROM sections.\n@ Generated by tools/split.py; section names preserve ROM order.',
        '@ English-build script assets ROM sections -- see tools/split_scripts_english.py.\n'
        '@ Mechanically derived from asm/data/script_assets.s; do not hand-edit.')
    ENGLISH_SCRIPT_ASSETS.parent.mkdir(parents=True, exist_ok=True)
    ENGLISH_SCRIPT_ASSETS.write_text(text)


def write_expansion_asm():
    names = json.loads(EXPANSION_MANIFEST.read_text()) if EXPANSION_MANIFEST.exists() else []
    lines = ['@ English-build script expansion-region content.',
             '@ Generated by tools/split_scripts_english.py; do not hand-edit.', '']
    for name in names:
        ident = marscript_identifier(name)
        lines += ['\t.section .rodata',
                  f'\t.global gMarscriptScript_{ident}',
                  f'gMarscriptScript_{ident}:',
                  f'\t.incbin "build/english/scripts_expansion/{name}.bin"', '']
    EXPANSION_ASM.parent.mkdir(parents=True, exist_ok=True)
    EXPANSION_ASM.write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    write_script_assets_english()
    write_expansion_asm()
    print(f'wrote {ENGLISH_SCRIPT_ASSETS} and {EXPANSION_ASM}')
