#!/usr/bin/env python3
"""Generate the English build's script-placement assembly.

Two outputs, both mechanically derived (safe to regenerate on every build,
unlike tools/split.py's one-time ROM extraction):

- build/english/script_assets_english.s: structurally identical to the base
  script group in data/rom_data_sections.json (same section names, ROM
  addresses, and order) but pointing at build/english/scripts/nfp/ instead of
  build/scripts/nfp/, so every script's *original* ROM slot keeps its exact
  size and position -- this is what makes it safe for the base mar.gba
  build to keep using the unmodified script_assets.s/.o unchanged while
  mar_english.gba uses this variant instead (see the Makefile's filter-out
  for mar_english.elf). A script whose marscript override grew past its
  original slot still gets an (inert, unreferenced) entry here -- see
  tools/marscript_rom_build.py's plan() -- so nothing downstream shifts.

- build/english/marscript_expansion.s: one .rodata symbol per script whose
  override didn't fit its original slot (usually none), each .incbin'd from
  build/english/scripts_expansion/<name>.bin. Landing in .rodata under
  build/english/*.o means ld_english.ld's existing `.english` section
  wildcard (`build/english/*.o(.text .text.* .rodata .rodata.*)`) picks
  these up automatically -- no linker script changes needed. The matching
  half of this mechanism is resource_catalog.py --english, which points
  that one script's catalog entry at the resulting symbol instead of a
  literal offset.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'tools'))
from rom_data_sections import load_sections, write_assembly

ROM_DATA_MANIFEST = ROOT / 'data/rom_data_sections.json'
ENGLISH_SCRIPT_ASSETS = ROOT / 'build/english/script_assets_english.s'
EXPANSION_MANIFEST = ROOT / 'build/english/scripts_expansion_manifest.json'
EXPANSION_ASM = ROOT / 'build/english/marscript_expansion.s'


def marscript_identifier(name):
    return name.replace('.', '_').replace('-', '_')


def write_script_assets_english(validate_sources=True):
    sections = load_sections(ROM_DATA_MANIFEST, 'script_assets')
    write_assembly(sections, ENGLISH_SCRIPT_ASSETS, english_scripts=True,
                   validate_sources=validate_sources)


def write_expansion_asm():
    names = json.loads(EXPANSION_MANIFEST.read_text()) if EXPANSION_MANIFEST.exists() else []
    lines = ['@ English-build script expansion-region content.',
             '@ Generated by tools/split_scripts_english.py; do not hand-edit.', '']
    for name in names:
        ident = marscript_identifier(name)
        lines += ['\t.section .rodata',
                  f'\t.global gMarscriptScript_{ident}',
                  f'gMarscriptScript_{ident}:',
                  f'\t.incbin "build/english/scripts_expansion/{name}.bin"', '']
    EXPANSION_ASM.parent.mkdir(parents=True, exist_ok=True)
    EXPANSION_ASM.write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    write_script_assets_english()
    write_expansion_asm()
    print(f'wrote {ENGLISH_SCRIPT_ASSETS} and {EXPANSION_ASM}')
